function anti_imaging_filter_8_generatehdl(filtobj)
%  ANTI_IMAGING_FILTER_8_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
%  Generated on: 2026-08-27 11:11:33
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  FIRAdderStyle: tree
%  MultiplierInputPipeline: 1
%  MultiplierOutputPipeline: 1
%  OptimizeForHDL: on
%  TargetDirectory: hdlsrc/anti_imaging_filter_8
%  AddPipelineRegisters: on
%  Name: anti_imaging_filter_8
%  TargetLanguage: Verilog
%  TestBenchStimulus: step ramp chirp noise 
%  LoopUnrolling: on
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Multirate Filter (real)
%  -----------------------------------------
%  Filter Structure      : Direct-Form FIR Polyphase Interpolator
%  Interpolation Factor  : 8
%  Polyphase Length      : 3
%  Filter Length         : 20
%  Stable                : Yes
%  Linear Phase          : Yes (Type 2)
%
%  Arithmetic            : fixed
%  Numerator             : s16,15 -> [-1 1)
%  Input                 : s16,15 -> [-1 1)
%  Filter Internals      : Specify Precision
%    Output              : s16,15 -> [-1 1)
%    Product             : s31,30 -> [-1 1)
%    Accumulator         : s35,30 -> [-16 16)
%    Round Mode          : convergent
%    Overflow Mode       : wrap

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'FIRAdderStyle', 'tree',... 
               'MultiplierInputPipeline', 1,... 
               'MultiplierOutputPipeline', 1,... 
               'OptimizeForHDL', 'on',... 
               'TargetDirectory', 'hdlsrc/anti_imaging_filter_8',... 
               'AddPipelineRegisters', 'on',... 
               'Name', 'anti_imaging_filter_8',... 
               'TargetLanguage', 'Verilog',... 
               'TestBenchStimulus',  {'step', 'ramp', 'chirp', 'noise'},... 
               'LoopUnrolling', 'on',... 
               'GenerateHDLTestbench', 'on');

% [EOF]
