// -------------------------------------------------------------
//
// Module: anti_imaging_filter_5
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-08-27 11:11:18
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: hdlsrc/anti_imaging_filter_5
// AddPipelineRegisters: on
// Name: anti_imaging_filter_5
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 14
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// Input             : s16,15 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s16,14 -> [-2 2)
//   Product         : s31,30 -> [-1 1)
//   Accumulator     : s34,30 -> [-8 8)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------
// Multipliers           : 14



`timescale 1 ns / 1 ns

module anti_imaging_filter_5
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                filter_out_valid
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En14
  output  filter_out_valid;

////////////////////////////////////////////////////////////////
//Module Architecture: anti_imaging_filter_5
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000001011011111; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b0000101100101110; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b0001101111101100; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b0011010101011101; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b0101001110101101; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b0110111101011110; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b0110111101011110; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b0101001110101101; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b0011010101011101; //sfix16_En15
  parameter signed [15:0] coeff12 = 16'b0001101111101100; //sfix16_En15
  parameter signed [15:0] coeff13 = 16'b0000101100101110; //sfix16_En15
  parameter signed [15:0] coeff14 = 16'b0000001011011111; //sfix16_En15

  // Signals
  reg  signed [15:0] delay_pipeline [0:13] ; // sfix16_En15
  wire signed [30:0] product14; // sfix31_En30
  reg  signed [15:0] delay_pipeline_13_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff14_pipe; // sfix16_En15
  reg  signed [31:0] product14_pipe; // sfix32_En30
  wire signed [30:0] product13; // sfix31_En30
  reg  signed [15:0] delay_pipeline_12_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff13_pipe; // sfix16_En15
  reg  signed [31:0] product13_pipe; // sfix32_En30
  wire signed [30:0] product12; // sfix31_En30
  reg  signed [15:0] delay_pipeline_11_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff12_pipe; // sfix16_En15
  reg  signed [31:0] product12_pipe; // sfix32_En30
  wire signed [30:0] product11; // sfix31_En30
  reg  signed [15:0] delay_pipeline_10_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff11_pipe; // sfix16_En15
  reg  signed [31:0] product11_pipe; // sfix32_En30
  wire signed [30:0] product10; // sfix31_En30
  reg  signed [15:0] delay_pipeline_9_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff10_pipe; // sfix16_En15
  reg  signed [31:0] product10_pipe; // sfix32_En30
  wire signed [30:0] product9; // sfix31_En30
  reg  signed [15:0] delay_pipeline_8_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff9_pipe; // sfix16_En15
  reg  signed [31:0] product9_pipe; // sfix32_En30
  wire signed [30:0] product8; // sfix31_En30
  reg  signed [15:0] delay_pipeline_7_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff8_pipe; // sfix16_En15
  reg  signed [31:0] product8_pipe; // sfix32_En30
  wire signed [30:0] product7; // sfix31_En30
  reg  signed [15:0] delay_pipeline_6_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff7_pipe; // sfix16_En15
  reg  signed [31:0] product7_pipe; // sfix32_En30
  wire signed [30:0] product6; // sfix31_En30
  reg  signed [15:0] delay_pipeline_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff6_pipe; // sfix16_En15
  reg  signed [31:0] product6_pipe; // sfix32_En30
  wire signed [30:0] product5; // sfix31_En30
  reg  signed [15:0] delay_pipeline_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff5_pipe; // sfix16_En15
  reg  signed [31:0] product5_pipe; // sfix32_En30
  wire signed [30:0] product4; // sfix31_En30
  reg  signed [15:0] delay_pipeline_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff4_pipe; // sfix16_En15
  reg  signed [31:0] product4_pipe; // sfix32_En30
  wire signed [30:0] product3; // sfix31_En30
  reg  signed [15:0] delay_pipeline_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff3_pipe; // sfix16_En15
  reg  signed [31:0] product3_pipe; // sfix32_En30
  wire signed [30:0] product2; // sfix31_En30
  reg  signed [15:0] delay_pipeline_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff2_pipe; // sfix16_En15
  reg  signed [31:0] product2_pipe; // sfix32_En30
  wire signed [30:0] product1; // sfix31_En30
  reg  signed [15:0] delay_pipeline_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff1_pipe; // sfix16_En15
  reg  signed [31:0] product1_pipe; // sfix32_En30
  wire signed [33:0] sum_final; // sfix34_En30
  wire signed [33:0] sum1_1; // sfix34_En30
  wire signed [30:0] add_signext; // sfix31_En30
  wire signed [30:0] add_signext_1; // sfix31_En30
  wire signed [31:0] add_temp; // sfix32_En30
  reg  signed [33:0] sumpipe1_1; // sfix34_En30
  wire signed [33:0] sum1_2; // sfix34_En30
  wire signed [30:0] add_signext_2; // sfix31_En30
  wire signed [30:0] add_signext_3; // sfix31_En30
  wire signed [31:0] add_temp_1; // sfix32_En30
  reg  signed [33:0] sumpipe1_2; // sfix34_En30
  wire signed [33:0] sum1_3; // sfix34_En30
  wire signed [30:0] add_signext_4; // sfix31_En30
  wire signed [30:0] add_signext_5; // sfix31_En30
  wire signed [31:0] add_temp_2; // sfix32_En30
  reg  signed [33:0] sumpipe1_3; // sfix34_En30
  wire signed [33:0] sum1_4; // sfix34_En30
  wire signed [30:0] add_signext_6; // sfix31_En30
  wire signed [30:0] add_signext_7; // sfix31_En30
  wire signed [31:0] add_temp_3; // sfix32_En30
  reg  signed [33:0] sumpipe1_4; // sfix34_En30
  wire signed [33:0] sum1_5; // sfix34_En30
  wire signed [30:0] add_signext_8; // sfix31_En30
  wire signed [30:0] add_signext_9; // sfix31_En30
  wire signed [31:0] add_temp_4; // sfix32_En30
  reg  signed [33:0] sumpipe1_5; // sfix34_En30
  wire signed [33:0] sum1_6; // sfix34_En30
  wire signed [30:0] add_signext_10; // sfix31_En30
  wire signed [30:0] add_signext_11; // sfix31_En30
  wire signed [31:0] add_temp_5; // sfix32_En30
  reg  signed [33:0] sumpipe1_6; // sfix34_En30
  wire signed [33:0] sum1_7; // sfix34_En30
  wire signed [30:0] add_signext_12; // sfix31_En30
  wire signed [30:0] add_signext_13; // sfix31_En30
  wire signed [31:0] add_temp_6; // sfix32_En30
  reg  signed [33:0] sumpipe1_7; // sfix34_En30
  wire signed [33:0] sum2_1; // sfix34_En30
  wire signed [33:0] add_signext_14; // sfix34_En30
  wire signed [33:0] add_signext_15; // sfix34_En30
  wire signed [34:0] add_temp_7; // sfix35_En30
  reg  signed [33:0] sumpipe2_1; // sfix34_En30
  wire signed [33:0] sum2_2; // sfix34_En30
  wire signed [33:0] add_signext_16; // sfix34_En30
  wire signed [33:0] add_signext_17; // sfix34_En30
  wire signed [34:0] add_temp_8; // sfix35_En30
  reg  signed [33:0] sumpipe2_2; // sfix34_En30
  wire signed [33:0] sum2_3; // sfix34_En30
  wire signed [33:0] add_signext_18; // sfix34_En30
  wire signed [33:0] add_signext_19; // sfix34_En30
  wire signed [34:0] add_temp_9; // sfix35_En30
  reg  signed [33:0] sumpipe2_3; // sfix34_En30
  reg  signed [33:0] sumpipe2_4; // sfix34_En30
  wire signed [33:0] sum3_1; // sfix34_En30
  wire signed [33:0] add_signext_20; // sfix34_En30
  wire signed [33:0] add_signext_21; // sfix34_En30
  wire signed [34:0] add_temp_10; // sfix35_En30
  reg  signed [33:0] sumpipe3_1; // sfix34_En30
  wire signed [33:0] sum3_2; // sfix34_En30
  wire signed [33:0] add_signext_22; // sfix34_En30
  wire signed [33:0] add_signext_23; // sfix34_En30
  wire signed [34:0] add_temp_11; // sfix35_En30
  reg  signed [33:0] sumpipe3_2; // sfix34_En30
  wire signed [33:0] sum4_1; // sfix34_En30
  wire signed [33:0] add_signext_24; // sfix34_En30
  wire signed [33:0] add_signext_25; // sfix34_En30
  wire signed [34:0] add_temp_12; // sfix35_En30
  reg  signed [33:0] sumpipe4_1; // sfix34_En30
  wire signed [15:0] output_typeconvert; // sfix16_En14
  reg  signed [15:0] output_register; // sfix16_En14

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
        end
      end
    end // Delay_Pipeline_process


  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        delay_pipeline_13_under_pipe <= 0;
        coeff14_pipe <= 0;
        product14_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_13_under_pipe <= delay_pipeline[13];
          coeff14_pipe <= coeff14;

          product14_pipe <= delay_pipeline_13_under_pipe * coeff14_pipe;

        end
      end
    end // temp_process1

  assign product14 = product14_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        delay_pipeline_12_under_pipe <= 0;
        coeff13_pipe <= 0;
        product13_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_12_under_pipe <= delay_pipeline[12];
          coeff13_pipe <= coeff13;

          product13_pipe <= delay_pipeline_12_under_pipe * coeff13_pipe;

        end
      end
    end // temp_process2

  assign product13 = product13_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        delay_pipeline_11_under_pipe <= 0;
        coeff12_pipe <= 0;
        product12_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_11_under_pipe <= delay_pipeline[11];
          coeff12_pipe <= coeff12;

          product12_pipe <= delay_pipeline_11_under_pipe * coeff12_pipe;

        end
      end
    end // temp_process3

  assign product12 = product12_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        delay_pipeline_10_under_pipe <= 0;
        coeff11_pipe <= 0;
        product11_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_10_under_pipe <= delay_pipeline[10];
          coeff11_pipe <= coeff11;

          product11_pipe <= delay_pipeline_10_under_pipe * coeff11_pipe;

        end
      end
    end // temp_process4

  assign product11 = product11_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        delay_pipeline_9_under_pipe <= 0;
        coeff10_pipe <= 0;
        product10_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_9_under_pipe <= delay_pipeline[9];
          coeff10_pipe <= coeff10;

          product10_pipe <= delay_pipeline_9_under_pipe * coeff10_pipe;

        end
      end
    end // temp_process5

  assign product10 = product10_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process6
      if (reset == 1'b1) begin
        delay_pipeline_8_under_pipe <= 0;
        coeff9_pipe <= 0;
        product9_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_8_under_pipe <= delay_pipeline[8];
          coeff9_pipe <= coeff9;

          product9_pipe <= delay_pipeline_8_under_pipe * coeff9_pipe;

        end
      end
    end // temp_process6

  assign product9 = product9_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process7
      if (reset == 1'b1) begin
        delay_pipeline_7_under_pipe <= 0;
        coeff8_pipe <= 0;
        product8_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_7_under_pipe <= delay_pipeline[7];
          coeff8_pipe <= coeff8;

          product8_pipe <= delay_pipeline_7_under_pipe * coeff8_pipe;

        end
      end
    end // temp_process7

  assign product8 = product8_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process8
      if (reset == 1'b1) begin
        delay_pipeline_6_under_pipe <= 0;
        coeff7_pipe <= 0;
        product7_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_6_under_pipe <= delay_pipeline[6];
          coeff7_pipe <= coeff7;

          product7_pipe <= delay_pipeline_6_under_pipe * coeff7_pipe;

        end
      end
    end // temp_process8

  assign product7 = product7_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process9
      if (reset == 1'b1) begin
        delay_pipeline_5_under_pipe <= 0;
        coeff6_pipe <= 0;
        product6_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_5_under_pipe <= delay_pipeline[5];
          coeff6_pipe <= coeff6;

          product6_pipe <= delay_pipeline_5_under_pipe * coeff6_pipe;

        end
      end
    end // temp_process9

  assign product6 = product6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process10
      if (reset == 1'b1) begin
        delay_pipeline_4_under_pipe <= 0;
        coeff5_pipe <= 0;
        product5_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_4_under_pipe <= delay_pipeline[4];
          coeff5_pipe <= coeff5;

          product5_pipe <= delay_pipeline_4_under_pipe * coeff5_pipe;

        end
      end
    end // temp_process10

  assign product5 = product5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process11
      if (reset == 1'b1) begin
        delay_pipeline_3_under_pipe <= 0;
        coeff4_pipe <= 0;
        product4_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_3_under_pipe <= delay_pipeline[3];
          coeff4_pipe <= coeff4;

          product4_pipe <= delay_pipeline_3_under_pipe * coeff4_pipe;

        end
      end
    end // temp_process11

  assign product4 = product4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process12
      if (reset == 1'b1) begin
        delay_pipeline_2_under_pipe <= 0;
        coeff3_pipe <= 0;
        product3_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_2_under_pipe <= delay_pipeline[2];
          coeff3_pipe <= coeff3;

          product3_pipe <= delay_pipeline_2_under_pipe * coeff3_pipe;

        end
      end
    end // temp_process12

  assign product3 = product3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process13
      if (reset == 1'b1) begin
        delay_pipeline_1_under_pipe <= 0;
        coeff2_pipe <= 0;
        product2_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_1_under_pipe <= delay_pipeline[1];
          coeff2_pipe <= coeff2;

          product2_pipe <= delay_pipeline_1_under_pipe * coeff2_pipe;

        end
      end
    end // temp_process13

  assign product2 = product2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process14
      if (reset == 1'b1) begin
        delay_pipeline_0_under_pipe <= 0;
        coeff1_pipe <= 0;
        product1_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_0_under_pipe <= delay_pipeline[0];
          coeff1_pipe <= coeff1;

          product1_pipe <= delay_pipeline_0_under_pipe * coeff1_pipe;

        end
      end
    end // temp_process14

  assign product1 = product1_pipe[30:0];

  assign add_signext = product14;
  assign add_signext_1 = product13;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{2{add_temp[31]}}, add_temp});

  assign add_signext_2 = product12;
  assign add_signext_3 = product11;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{2{add_temp_1[31]}}, add_temp_1});

  assign add_signext_4 = product10;
  assign add_signext_5 = product9;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{2{add_temp_2[31]}}, add_temp_2});

  assign add_signext_6 = product8;
  assign add_signext_7 = product7;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum1_4 = $signed({{2{add_temp_3[31]}}, add_temp_3});

  assign add_signext_8 = product6;
  assign add_signext_9 = product5;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum1_5 = $signed({{2{add_temp_4[31]}}, add_temp_4});

  assign add_signext_10 = product4;
  assign add_signext_11 = product3;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum1_6 = $signed({{2{add_temp_5[31]}}, add_temp_5});

  assign add_signext_12 = product2;
  assign add_signext_13 = product1;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum1_7 = $signed({{2{add_temp_6[31]}}, add_temp_6});

  always @ (posedge clk or posedge reset)
    begin: temp_process15
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
        sumpipe1_3 <= 0;
        sumpipe1_4 <= 0;
        sumpipe1_5 <= 0;
        sumpipe1_6 <= 0;
        sumpipe1_7 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
          sumpipe1_3 <= sum1_3;
          sumpipe1_4 <= sum1_4;
          sumpipe1_5 <= sum1_5;
          sumpipe1_6 <= sum1_6;
          sumpipe1_7 <= sum1_7;
        end
      end
    end // temp_process15

  assign add_signext_14 = sumpipe1_1;
  assign add_signext_15 = sumpipe1_2;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum2_1 = add_temp_7[33:0];

  assign add_signext_16 = sumpipe1_3;
  assign add_signext_17 = sumpipe1_4;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum2_2 = add_temp_8[33:0];

  assign add_signext_18 = sumpipe1_5;
  assign add_signext_19 = sumpipe1_6;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum2_3 = add_temp_9[33:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process16
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
        sumpipe2_2 <= 0;
        sumpipe2_3 <= 0;
        sumpipe2_4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
          sumpipe2_2 <= sum2_2;
          sumpipe2_3 <= sum2_3;
          sumpipe2_4 <= sumpipe1_7;
        end
      end
    end // temp_process16

  assign add_signext_20 = sumpipe2_1;
  assign add_signext_21 = sumpipe2_2;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum3_1 = add_temp_10[33:0];

  assign add_signext_22 = sumpipe2_3;
  assign add_signext_23 = sumpipe2_4;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum3_2 = add_temp_11[33:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process17
      if (reset == 1'b1) begin
        sumpipe3_1 <= 0;
        sumpipe3_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe3_1 <= sum3_1;
          sumpipe3_2 <= sum3_2;
        end
      end
    end // temp_process17

  assign add_signext_24 = sumpipe3_1;
  assign add_signext_25 = sumpipe3_2;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum4_1 = add_temp_12[33:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process18
      if (reset == 1'b1) begin
        sumpipe4_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe4_1 <= sum4_1;
        end
      end
    end // temp_process18

  assign sum_final = sumpipe4_1;

  assign output_typeconvert = (sum_final[31:0] + {sum_final[16], {15{~sum_final[16]}}})>>>16;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;

  // filter_out_valid: output sample valid, aligned with output_register.
  // Pipeline latency = 15 clk_enable events (14-tap + under_pipe +
  // product_pipe + output_register); delay clk_enable by the same depth.
  reg [14:0] ce_delay;
  always @(posedge clk or posedge reset) begin
    if (reset == 1'b1) begin
      ce_delay <= 0;
    end
    else if (clk_enable == 1'b1) begin
      ce_delay <= {ce_delay[13:0], 1'b1};
    end
  end
  assign filter_out_valid = clk_enable & ce_delay[14];
endmodule  // anti_imaging_filter_5
