// -------------------------------------------------------------
//
// Module: anti_imaging_8_6667k
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-09-14 11:00:43
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: hdlsrc/anti_imaging_8_6667k
// AddPipelineRegisters: on
// Name: anti_imaging_8_6667k
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp noise 
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure      : Direct-Form FIR Polyphase Interpolator
// Interpolation Factor  : 8
// Polyphase Length      : 3
// Filter Length         : 21
// Stable                : Yes
// Linear Phase          : Yes (Type 1)
//
// Arithmetic            : fixed
// Numerator             : s16,15 -> [-1 1)
// Input                 : s16,15 -> [-1 1)
// Filter Internals      : Specify Precision
//   Output              : s16,15 -> [-1 1)
//   Product             : s31,30 -> [-1 1)
//   Accumulator         : s32,30 -> [-2 2)
//   Round Mode          : convergent
//   Overflow Mode       : wrap
// -------------------------------------------------------------
// Multipliers           : 3



`timescale 1 ns / 1 ns

module anti_imaging_8_6667k
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En15
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: anti_imaging_8_6667k
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b0000001000100011; //sfix16_En15
  parameter signed [15:0] coeffphase1_2 = 16'b0111000100101100; //sfix16_En15
  parameter signed [15:0] coeffphase1_3 = 16'b0010011100010100; //sfix16_En15
  parameter signed [15:0] coeffphase2_1 = 16'b0000010111111110; //sfix16_En15
  parameter signed [15:0] coeffphase2_2 = 16'b0111110000100100; //sfix16_En15
  parameter signed [15:0] coeffphase2_3 = 16'b0001100000011110; //sfix16_En15
  parameter signed [15:0] coeffphase3_1 = 16'b0000110100011111; //sfix16_En15
  parameter signed [15:0] coeffphase3_2 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeffphase3_3 = 16'b0000110100011111; //sfix16_En15
  parameter signed [15:0] coeffphase4_1 = 16'b0001100000011110; //sfix16_En15
  parameter signed [15:0] coeffphase4_2 = 16'b0111110000100100; //sfix16_En15
  parameter signed [15:0] coeffphase4_3 = 16'b0000010111111110; //sfix16_En15
  parameter signed [15:0] coeffphase5_1 = 16'b0010011100010100; //sfix16_En15
  parameter signed [15:0] coeffphase5_2 = 16'b0111000100101100; //sfix16_En15
  parameter signed [15:0] coeffphase5_3 = 16'b0000001000100011; //sfix16_En15
  parameter signed [15:0] coeffphase6_1 = 16'b0011100101010011; //sfix16_En15
  parameter signed [15:0] coeffphase6_2 = 16'b0110000011000101; //sfix16_En15
  parameter signed [15:0] coeffphase6_3 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase7_1 = 16'b0100110101001101; //sfix16_En15
  parameter signed [15:0] coeffphase7_2 = 16'b0100110101001101; //sfix16_En15
  parameter signed [15:0] coeffphase7_3 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase8_1 = 16'b0110000011000101; //sfix16_En15
  parameter signed [15:0] coeffphase8_2 = 16'b0011100101010011; //sfix16_En15
  parameter signed [15:0] coeffphase8_3 = 16'b0000000000000000; //sfix16_En15

  // Signals
  reg  [2:0] cur_count; // ufix3
  wire phase_7; // boolean
  reg  signed [15:0] delay_pipeline [0:2] ; // sfix16_En15
  wire signed [30:0] product; // sfix31_En30
  wire signed [15:0] product_mux; // sfix16_En15
  reg  signed [15:0] delay_pipeline_2_under_pipe; // sfix16_En15
  reg  signed [15:0] product_mux_pipe; // sfix16_En15
  reg  signed [31:0] product_pipe; // sfix32_En30
  wire signed [30:0] product_1; // sfix31_En30
  wire signed [15:0] product_mux_1; // sfix16_En15
  reg  signed [15:0] delay_pipeline_1_under_pipe; // sfix16_En15
  reg  signed [15:0] product_mux_1_pipe; // sfix16_En15
  reg  signed [31:0] product_1_pipe; // sfix32_En30
  wire signed [30:0] product_2; // sfix31_En30
  wire signed [15:0] product_mux_2; // sfix16_En15
  reg  signed [15:0] delay_pipeline_0_under_pipe; // sfix16_En15
  reg  signed [15:0] product_mux_2_pipe; // sfix16_En15
  reg  signed [31:0] product_2_pipe; // sfix32_En30
  wire signed [31:0] sumvector1 [0:1] ; // sfix32_En30
  wire signed [30:0] add_signext; // sfix31_En30
  wire signed [30:0] add_signext_1; // sfix31_En30
  reg  signed [31:0] sumdelay_pipeline1 [0:1] ; // sfix32_En30
  wire signed [31:0] sum2; // sfix32_En30
  wire signed [31:0] add_signext_2; // sfix32_En30
  wire signed [31:0] add_signext_3; // sfix32_En30
  wire signed [32:0] add_temp; // sfix33_En30
  wire signed [15:0] output_typeconvert; // sfix16_En15
  reg  signed [15:0] output_register; // sfix16_En15

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 3'b000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 3'b111) begin
            cur_count <= 3'b000;
          end
          else begin
            cur_count <= cur_count + 3'b001;
          end
        end
      end
    end // ce_output

  assign  phase_7 = (cur_count == 3'b111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  //   ---------------- Delay Registers ----------------

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
        end
      end
    end // Delay_Pipeline_process


  assign product_mux = (cur_count == 3'b000) ? coeffphase1_3 :
                      (cur_count == 3'b001) ? coeffphase2_3 :
                      (cur_count == 3'b010) ? coeffphase3_3 :
                      (cur_count == 3'b011) ? coeffphase4_3 :
                      (cur_count == 3'b100) ? coeffphase5_3 :
                      (cur_count == 3'b101) ? coeffphase6_3 :
                      (cur_count == 3'b110) ? coeffphase7_3 :
                      coeffphase8_3;
  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        delay_pipeline_2_under_pipe <= 0;
        product_mux_pipe <= 0;
        product_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_2_under_pipe <= delay_pipeline[2];
          product_mux_pipe <= product_mux;

          product_pipe <= delay_pipeline_2_under_pipe * product_mux_pipe;

        end
      end
    end // temp_process1

  assign product = product_pipe[30:0];

  assign product_mux_1 = (cur_count == 3'b000) ? coeffphase1_2 :
                        (cur_count == 3'b001) ? coeffphase2_2 :
                        (cur_count == 3'b010) ? coeffphase3_2 :
                        (cur_count == 3'b011) ? coeffphase4_2 :
                        (cur_count == 3'b100) ? coeffphase5_2 :
                        (cur_count == 3'b101) ? coeffphase6_2 :
                        (cur_count == 3'b110) ? coeffphase7_2 :
                        coeffphase8_2;
  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        delay_pipeline_1_under_pipe <= 0;
        product_mux_1_pipe <= 0;
        product_1_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_1_under_pipe <= delay_pipeline[1];
          product_mux_1_pipe <= product_mux_1;

          product_1_pipe <= delay_pipeline_1_under_pipe * product_mux_1_pipe;

        end
      end
    end // temp_process2

  assign product_1 = product_1_pipe[30:0];

  assign product_mux_2 = (cur_count == 3'b000) ? coeffphase1_1 :
                        (cur_count == 3'b001) ? coeffphase2_1 :
                        (cur_count == 3'b010) ? coeffphase3_1 :
                        (cur_count == 3'b011) ? coeffphase4_1 :
                        (cur_count == 3'b100) ? coeffphase5_1 :
                        (cur_count == 3'b101) ? coeffphase6_1 :
                        (cur_count == 3'b110) ? coeffphase7_1 :
                        coeffphase8_1;
  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        delay_pipeline_0_under_pipe <= 0;
        product_mux_2_pipe <= 0;
        product_2_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_0_under_pipe <= delay_pipeline[0];
          product_mux_2_pipe <= product_mux_2;

          product_2_pipe <= delay_pipeline_0_under_pipe * product_mux_2_pipe;

        end
      end
    end // temp_process3

  assign product_2 = product_2_pipe[30:0];

  assign add_signext = product;
  assign add_signext_1 = product_1;
  assign sumvector1[0] = add_signext + add_signext_1;

  assign sumvector1[1] = $signed({{1{product_2[30]}}, product_2});

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process1
      if (reset == 1'b1) begin
        sumdelay_pipeline1[0] <= 0;
        sumdelay_pipeline1[1] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumdelay_pipeline1[0] <= sumvector1[0];
          sumdelay_pipeline1[1] <= sumvector1[1];
        end
      end
    end // sumdelay_pipeline_process1

  assign add_signext_2 = sumdelay_pipeline1[0];
  assign add_signext_3 = sumdelay_pipeline1[1];
  assign add_temp = add_signext_2 + add_signext_3;
  assign sum2 = add_temp[31:0];

  assign output_typeconvert = (sum2[30:0] + {sum2[15], {14{~sum2[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign ce_out = phase_7;
  assign filter_out = output_register;
endmodule  // anti_imaging_8_6667k
