// -------------------------------------------------------------
//
// Module: rcos_filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-08-27 11:11:42
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: hdlsrc/rcos_filter
// AddPipelineRegisters: on
// Name: rcos_filter
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 65
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// Input             : s16,15 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s16,14 -> [-2 2)
//   Product         : s31,30 -> [-1 1)
//   Accumulator     : s35,30 -> [-16 16)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------
// Multipliers           : 57



`timescale 1 ns / 1 ns

module rcos_filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                filter_out_valid
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En14
  output  filter_out_valid;

////////////////////////////////////////////////////////////////
//Module Architecture: rcos_filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b1111111010100001; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b1111110100101010; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b1111101111011110; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b1111101100000110; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b1111101011100111; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b1111101110101111; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b1111110101101100; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b0000001100100000; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b0000011001011001; //sfix16_En15
  parameter signed [15:0] coeff12 = 16'b0000100100011101; //sfix16_En15
  parameter signed [15:0] coeff13 = 16'b0000101011010100; //sfix16_En15
  parameter signed [15:0] coeff14 = 16'b0000101011111011; //sfix16_En15
  parameter signed [15:0] coeff15 = 16'b0000100100111010; //sfix16_En15
  parameter signed [15:0] coeff16 = 16'b0000010101111100; //sfix16_En15
  parameter signed [15:0] coeff17 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff18 = 16'b1111100101011100; //sfix16_En15
  parameter signed [15:0] coeff19 = 16'b1111001001110100; //sfix16_En15
  parameter signed [15:0] coeff20 = 16'b1110110001101001; //sfix16_En15
  parameter signed [15:0] coeff21 = 16'b1110100001110001; //sfix16_En15
  parameter signed [15:0] coeff22 = 16'b1110011110110100; //sfix16_En15
  parameter signed [15:0] coeff23 = 16'b1110101100011100; //sfix16_En15
  parameter signed [15:0] coeff24 = 16'b1111001100110011; //sfix16_En15
  parameter signed [15:0] coeff25 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff26 = 16'b0001000011111100; //sfix16_En15
  parameter signed [15:0] coeff27 = 16'b0010010100010110; //sfix16_En15
  parameter signed [15:0] coeff28 = 16'b0011101011000111; //sfix16_En15
  parameter signed [15:0] coeff29 = 16'b0101000000111010; //sfix16_En15
  parameter signed [15:0] coeff30 = 16'b0110001110000001; //sfix16_En15
  parameter signed [15:0] coeff31 = 16'b0111001011001011; //sfix16_En15
  parameter signed [15:0] coeff32 = 16'b0111110010011101; //sfix16_En15
  parameter signed [15:0] coeff33 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeff34 = 16'b0111110010011101; //sfix16_En15
  parameter signed [15:0] coeff35 = 16'b0111001011001011; //sfix16_En15
  parameter signed [15:0] coeff36 = 16'b0110001110000001; //sfix16_En15
  parameter signed [15:0] coeff37 = 16'b0101000000111010; //sfix16_En15
  parameter signed [15:0] coeff38 = 16'b0011101011000111; //sfix16_En15
  parameter signed [15:0] coeff39 = 16'b0010010100010110; //sfix16_En15
  parameter signed [15:0] coeff40 = 16'b0001000011111100; //sfix16_En15
  parameter signed [15:0] coeff41 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff42 = 16'b1111001100110011; //sfix16_En15
  parameter signed [15:0] coeff43 = 16'b1110101100011100; //sfix16_En15
  parameter signed [15:0] coeff44 = 16'b1110011110110100; //sfix16_En15
  parameter signed [15:0] coeff45 = 16'b1110100001110001; //sfix16_En15
  parameter signed [15:0] coeff46 = 16'b1110110001101001; //sfix16_En15
  parameter signed [15:0] coeff47 = 16'b1111001001110100; //sfix16_En15
  parameter signed [15:0] coeff48 = 16'b1111100101011100; //sfix16_En15
  parameter signed [15:0] coeff49 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff50 = 16'b0000010101111100; //sfix16_En15
  parameter signed [15:0] coeff51 = 16'b0000100100111010; //sfix16_En15
  parameter signed [15:0] coeff52 = 16'b0000101011111011; //sfix16_En15
  parameter signed [15:0] coeff53 = 16'b0000101011010100; //sfix16_En15
  parameter signed [15:0] coeff54 = 16'b0000100100011101; //sfix16_En15
  parameter signed [15:0] coeff55 = 16'b0000011001011001; //sfix16_En15
  parameter signed [15:0] coeff56 = 16'b0000001100100000; //sfix16_En15
  parameter signed [15:0] coeff57 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeff58 = 16'b1111110101101100; //sfix16_En15
  parameter signed [15:0] coeff59 = 16'b1111101110101111; //sfix16_En15
  parameter signed [15:0] coeff60 = 16'b1111101011100111; //sfix16_En15
  parameter signed [15:0] coeff61 = 16'b1111101100000110; //sfix16_En15
  parameter signed [15:0] coeff62 = 16'b1111101111011110; //sfix16_En15
  parameter signed [15:0] coeff63 = 16'b1111110100101010; //sfix16_En15
  parameter signed [15:0] coeff64 = 16'b1111111010100001; //sfix16_En15
  parameter signed [15:0] coeff65 = 16'b0000000000000000; //sfix16_En15

  // Signals
  reg  signed [15:0] delay_pipeline [0:64] ; // sfix16_En15
  wire signed [30:0] product64; // sfix31_En30
  reg  signed [15:0] delay_pipeline_63_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff64_pipe; // sfix16_En15
  reg  signed [31:0] product64_pipe; // sfix32_En30
  wire signed [30:0] product63; // sfix31_En30
  reg  signed [15:0] delay_pipeline_62_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff63_pipe; // sfix16_En15
  reg  signed [31:0] product63_pipe; // sfix32_En30
  wire signed [30:0] product62; // sfix31_En30
  reg  signed [15:0] delay_pipeline_61_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff62_pipe; // sfix16_En15
  reg  signed [31:0] product62_pipe; // sfix32_En30
  wire signed [30:0] product61; // sfix31_En30
  reg  signed [15:0] delay_pipeline_60_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff61_pipe; // sfix16_En15
  reg  signed [31:0] product61_pipe; // sfix32_En30
  wire signed [30:0] product60; // sfix31_En30
  reg  signed [15:0] delay_pipeline_59_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff60_pipe; // sfix16_En15
  reg  signed [31:0] product60_pipe; // sfix32_En30
  wire signed [30:0] product59; // sfix31_En30
  reg  signed [15:0] delay_pipeline_58_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff59_pipe; // sfix16_En15
  reg  signed [31:0] product59_pipe; // sfix32_En30
  wire signed [30:0] product58; // sfix31_En30
  reg  signed [15:0] delay_pipeline_57_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff58_pipe; // sfix16_En15
  reg  signed [31:0] product58_pipe; // sfix32_En30
  wire signed [30:0] product56; // sfix31_En30
  reg  signed [15:0] delay_pipeline_55_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff56_pipe; // sfix16_En15
  reg  signed [31:0] product56_pipe; // sfix32_En30
  wire signed [30:0] product55; // sfix31_En30
  reg  signed [15:0] delay_pipeline_54_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff55_pipe; // sfix16_En15
  reg  signed [31:0] product55_pipe; // sfix32_En30
  wire signed [30:0] product54; // sfix31_En30
  reg  signed [15:0] delay_pipeline_53_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff54_pipe; // sfix16_En15
  reg  signed [31:0] product54_pipe; // sfix32_En30
  wire signed [30:0] product53; // sfix31_En30
  reg  signed [15:0] delay_pipeline_52_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff53_pipe; // sfix16_En15
  reg  signed [31:0] product53_pipe; // sfix32_En30
  wire signed [30:0] product52; // sfix31_En30
  reg  signed [15:0] delay_pipeline_51_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff52_pipe; // sfix16_En15
  reg  signed [31:0] product52_pipe; // sfix32_En30
  wire signed [30:0] product51; // sfix31_En30
  reg  signed [15:0] delay_pipeline_50_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff51_pipe; // sfix16_En15
  reg  signed [31:0] product51_pipe; // sfix32_En30
  wire signed [30:0] product50; // sfix31_En30
  reg  signed [15:0] delay_pipeline_49_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff50_pipe; // sfix16_En15
  reg  signed [31:0] product50_pipe; // sfix32_En30
  wire signed [30:0] product48; // sfix31_En30
  reg  signed [15:0] delay_pipeline_47_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff48_pipe; // sfix16_En15
  reg  signed [31:0] product48_pipe; // sfix32_En30
  wire signed [30:0] product47; // sfix31_En30
  reg  signed [15:0] delay_pipeline_46_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff47_pipe; // sfix16_En15
  reg  signed [31:0] product47_pipe; // sfix32_En30
  wire signed [30:0] product46; // sfix31_En30
  reg  signed [15:0] delay_pipeline_45_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff46_pipe; // sfix16_En15
  reg  signed [31:0] product46_pipe; // sfix32_En30
  wire signed [30:0] product45; // sfix31_En30
  reg  signed [15:0] delay_pipeline_44_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff45_pipe; // sfix16_En15
  reg  signed [31:0] product45_pipe; // sfix32_En30
  wire signed [30:0] product44; // sfix31_En30
  reg  signed [15:0] delay_pipeline_43_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff44_pipe; // sfix16_En15
  reg  signed [31:0] product44_pipe; // sfix32_En30
  wire signed [30:0] product43; // sfix31_En30
  reg  signed [15:0] delay_pipeline_42_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff43_pipe; // sfix16_En15
  reg  signed [31:0] product43_pipe; // sfix32_En30
  wire signed [30:0] product42; // sfix31_En30
  reg  signed [15:0] delay_pipeline_41_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff42_pipe; // sfix16_En15
  reg  signed [31:0] product42_pipe; // sfix32_En30
  wire signed [30:0] product40; // sfix31_En30
  reg  signed [15:0] delay_pipeline_39_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff40_pipe; // sfix16_En15
  reg  signed [31:0] product40_pipe; // sfix32_En30
  wire signed [30:0] product39; // sfix31_En30
  reg  signed [15:0] delay_pipeline_38_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff39_pipe; // sfix16_En15
  reg  signed [31:0] product39_pipe; // sfix32_En30
  wire signed [30:0] product38; // sfix31_En30
  reg  signed [15:0] delay_pipeline_37_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff38_pipe; // sfix16_En15
  reg  signed [31:0] product38_pipe; // sfix32_En30
  wire signed [30:0] product37; // sfix31_En30
  reg  signed [15:0] delay_pipeline_36_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff37_pipe; // sfix16_En15
  reg  signed [31:0] product37_pipe; // sfix32_En30
  wire signed [30:0] product36; // sfix31_En30
  reg  signed [15:0] delay_pipeline_35_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff36_pipe; // sfix16_En15
  reg  signed [31:0] product36_pipe; // sfix32_En30
  wire signed [30:0] product35; // sfix31_En30
  reg  signed [15:0] delay_pipeline_34_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff35_pipe; // sfix16_En15
  reg  signed [31:0] product35_pipe; // sfix32_En30
  wire signed [30:0] product34; // sfix31_En30
  reg  signed [15:0] delay_pipeline_33_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff34_pipe; // sfix16_En15
  reg  signed [31:0] product34_pipe; // sfix32_En30
  wire signed [30:0] product33; // sfix31_En30
  reg  signed [15:0] delay_pipeline_32_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff33_pipe; // sfix16_En15
  reg  signed [31:0] product33_pipe; // sfix32_En30
  wire signed [30:0] product32; // sfix31_En30
  reg  signed [15:0] delay_pipeline_31_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff32_pipe; // sfix16_En15
  reg  signed [31:0] product32_pipe; // sfix32_En30
  wire signed [30:0] product31; // sfix31_En30
  reg  signed [15:0] delay_pipeline_30_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff31_pipe; // sfix16_En15
  reg  signed [31:0] product31_pipe; // sfix32_En30
  wire signed [30:0] product30; // sfix31_En30
  reg  signed [15:0] delay_pipeline_29_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff30_pipe; // sfix16_En15
  reg  signed [31:0] product30_pipe; // sfix32_En30
  wire signed [30:0] product29; // sfix31_En30
  reg  signed [15:0] delay_pipeline_28_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff29_pipe; // sfix16_En15
  reg  signed [31:0] product29_pipe; // sfix32_En30
  wire signed [30:0] product28; // sfix31_En30
  reg  signed [15:0] delay_pipeline_27_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff28_pipe; // sfix16_En15
  reg  signed [31:0] product28_pipe; // sfix32_En30
  wire signed [30:0] product27; // sfix31_En30
  reg  signed [15:0] delay_pipeline_26_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff27_pipe; // sfix16_En15
  reg  signed [31:0] product27_pipe; // sfix32_En30
  wire signed [30:0] product26; // sfix31_En30
  reg  signed [15:0] delay_pipeline_25_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff26_pipe; // sfix16_En15
  reg  signed [31:0] product26_pipe; // sfix32_En30
  wire signed [30:0] product24; // sfix31_En30
  reg  signed [15:0] delay_pipeline_23_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff24_pipe; // sfix16_En15
  reg  signed [31:0] product24_pipe; // sfix32_En30
  wire signed [30:0] product23; // sfix31_En30
  reg  signed [15:0] delay_pipeline_22_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff23_pipe; // sfix16_En15
  reg  signed [31:0] product23_pipe; // sfix32_En30
  wire signed [30:0] product22; // sfix31_En30
  reg  signed [15:0] delay_pipeline_21_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff22_pipe; // sfix16_En15
  reg  signed [31:0] product22_pipe; // sfix32_En30
  wire signed [30:0] product21; // sfix31_En30
  reg  signed [15:0] delay_pipeline_20_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff21_pipe; // sfix16_En15
  reg  signed [31:0] product21_pipe; // sfix32_En30
  wire signed [30:0] product20; // sfix31_En30
  reg  signed [15:0] delay_pipeline_19_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff20_pipe; // sfix16_En15
  reg  signed [31:0] product20_pipe; // sfix32_En30
  wire signed [30:0] product19; // sfix31_En30
  reg  signed [15:0] delay_pipeline_18_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff19_pipe; // sfix16_En15
  reg  signed [31:0] product19_pipe; // sfix32_En30
  wire signed [30:0] product18; // sfix31_En30
  reg  signed [15:0] delay_pipeline_17_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff18_pipe; // sfix16_En15
  reg  signed [31:0] product18_pipe; // sfix32_En30
  wire signed [30:0] product16; // sfix31_En30
  reg  signed [15:0] delay_pipeline_15_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff16_pipe; // sfix16_En15
  reg  signed [31:0] product16_pipe; // sfix32_En30
  wire signed [30:0] product15; // sfix31_En30
  reg  signed [15:0] delay_pipeline_14_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff15_pipe; // sfix16_En15
  reg  signed [31:0] product15_pipe; // sfix32_En30
  wire signed [30:0] product14; // sfix31_En30
  reg  signed [15:0] delay_pipeline_13_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff14_pipe; // sfix16_En15
  reg  signed [31:0] product14_pipe; // sfix32_En30
  wire signed [30:0] product13; // sfix31_En30
  reg  signed [15:0] delay_pipeline_12_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff13_pipe; // sfix16_En15
  reg  signed [31:0] product13_pipe; // sfix32_En30
  wire signed [30:0] product12; // sfix31_En30
  reg  signed [15:0] delay_pipeline_11_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff12_pipe; // sfix16_En15
  reg  signed [31:0] product12_pipe; // sfix32_En30
  wire signed [30:0] product11; // sfix31_En30
  reg  signed [15:0] delay_pipeline_10_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff11_pipe; // sfix16_En15
  reg  signed [31:0] product11_pipe; // sfix32_En30
  wire signed [30:0] product10; // sfix31_En30
  reg  signed [15:0] delay_pipeline_9_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff10_pipe; // sfix16_En15
  reg  signed [31:0] product10_pipe; // sfix32_En30
  wire signed [30:0] product8; // sfix31_En30
  reg  signed [15:0] delay_pipeline_7_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff8_pipe; // sfix16_En15
  reg  signed [31:0] product8_pipe; // sfix32_En30
  wire signed [30:0] product7; // sfix31_En30
  reg  signed [15:0] delay_pipeline_6_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff7_pipe; // sfix16_En15
  reg  signed [31:0] product7_pipe; // sfix32_En30
  wire signed [30:0] product6; // sfix31_En30
  reg  signed [15:0] delay_pipeline_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff6_pipe; // sfix16_En15
  reg  signed [31:0] product6_pipe; // sfix32_En30
  wire signed [30:0] product5; // sfix31_En30
  reg  signed [15:0] delay_pipeline_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff5_pipe; // sfix16_En15
  reg  signed [31:0] product5_pipe; // sfix32_En30
  wire signed [30:0] product4; // sfix31_En30
  reg  signed [15:0] delay_pipeline_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff4_pipe; // sfix16_En15
  reg  signed [31:0] product4_pipe; // sfix32_En30
  wire signed [30:0] product3; // sfix31_En30
  reg  signed [15:0] delay_pipeline_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff3_pipe; // sfix16_En15
  reg  signed [31:0] product3_pipe; // sfix32_En30
  wire signed [30:0] product2; // sfix31_En30
  reg  signed [15:0] delay_pipeline_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff2_pipe; // sfix16_En15
  reg  signed [31:0] product2_pipe; // sfix32_En30
  wire signed [34:0] sum_final; // sfix35_En30
  wire signed [34:0] sum1_1; // sfix35_En30
  wire signed [30:0] add_signext; // sfix31_En30
  wire signed [30:0] add_signext_1; // sfix31_En30
  wire signed [31:0] add_temp; // sfix32_En30
  reg  signed [34:0] sumpipe1_1; // sfix35_En30
  wire signed [34:0] sum1_2; // sfix35_En30
  wire signed [30:0] add_signext_2; // sfix31_En30
  wire signed [30:0] add_signext_3; // sfix31_En30
  wire signed [31:0] add_temp_1; // sfix32_En30
  reg  signed [34:0] sumpipe1_2; // sfix35_En30
  wire signed [34:0] sum1_3; // sfix35_En30
  wire signed [30:0] add_signext_4; // sfix31_En30
  wire signed [30:0] add_signext_5; // sfix31_En30
  wire signed [31:0] add_temp_2; // sfix32_En30
  reg  signed [34:0] sumpipe1_3; // sfix35_En30
  wire signed [34:0] sum1_4; // sfix35_En30
  wire signed [30:0] add_signext_6; // sfix31_En30
  wire signed [30:0] add_signext_7; // sfix31_En30
  wire signed [31:0] add_temp_3; // sfix32_En30
  reg  signed [34:0] sumpipe1_4; // sfix35_En30
  wire signed [34:0] sum1_5; // sfix35_En30
  wire signed [30:0] add_signext_8; // sfix31_En30
  wire signed [30:0] add_signext_9; // sfix31_En30
  wire signed [31:0] add_temp_4; // sfix32_En30
  reg  signed [34:0] sumpipe1_5; // sfix35_En30
  wire signed [34:0] sum1_6; // sfix35_En30
  wire signed [30:0] add_signext_10; // sfix31_En30
  wire signed [30:0] add_signext_11; // sfix31_En30
  wire signed [31:0] add_temp_5; // sfix32_En30
  reg  signed [34:0] sumpipe1_6; // sfix35_En30
  wire signed [34:0] sum1_7; // sfix35_En30
  wire signed [30:0] add_signext_12; // sfix31_En30
  wire signed [30:0] add_signext_13; // sfix31_En30
  wire signed [31:0] add_temp_6; // sfix32_En30
  reg  signed [34:0] sumpipe1_7; // sfix35_En30
  wire signed [34:0] sum1_8; // sfix35_En30
  wire signed [30:0] add_signext_14; // sfix31_En30
  wire signed [30:0] add_signext_15; // sfix31_En30
  wire signed [31:0] add_temp_7; // sfix32_En30
  reg  signed [34:0] sumpipe1_8; // sfix35_En30
  wire signed [34:0] sum1_9; // sfix35_En30
  wire signed [30:0] add_signext_16; // sfix31_En30
  wire signed [30:0] add_signext_17; // sfix31_En30
  wire signed [31:0] add_temp_8; // sfix32_En30
  reg  signed [34:0] sumpipe1_9; // sfix35_En30
  wire signed [34:0] sum1_10; // sfix35_En30
  wire signed [30:0] add_signext_18; // sfix31_En30
  wire signed [30:0] add_signext_19; // sfix31_En30
  wire signed [31:0] add_temp_9; // sfix32_En30
  reg  signed [34:0] sumpipe1_10; // sfix35_En30
  wire signed [34:0] sum1_11; // sfix35_En30
  wire signed [30:0] add_signext_20; // sfix31_En30
  wire signed [30:0] add_signext_21; // sfix31_En30
  wire signed [31:0] add_temp_10; // sfix32_En30
  reg  signed [34:0] sumpipe1_11; // sfix35_En30
  wire signed [34:0] sum1_12; // sfix35_En30
  wire signed [30:0] add_signext_22; // sfix31_En30
  wire signed [30:0] add_signext_23; // sfix31_En30
  wire signed [31:0] add_temp_11; // sfix32_En30
  reg  signed [34:0] sumpipe1_12; // sfix35_En30
  wire signed [34:0] sum1_13; // sfix35_En30
  wire signed [30:0] add_signext_24; // sfix31_En30
  wire signed [30:0] add_signext_25; // sfix31_En30
  wire signed [31:0] add_temp_12; // sfix32_En30
  reg  signed [34:0] sumpipe1_13; // sfix35_En30
  wire signed [34:0] sum1_14; // sfix35_En30
  wire signed [30:0] add_signext_26; // sfix31_En30
  wire signed [30:0] add_signext_27; // sfix31_En30
  wire signed [31:0] add_temp_13; // sfix32_En30
  reg  signed [34:0] sumpipe1_14; // sfix35_En30
  wire signed [34:0] sum1_15; // sfix35_En30
  wire signed [30:0] add_signext_28; // sfix31_En30
  wire signed [30:0] add_signext_29; // sfix31_En30
  wire signed [31:0] add_temp_14; // sfix32_En30
  reg  signed [34:0] sumpipe1_15; // sfix35_En30
  wire signed [34:0] sum1_16; // sfix35_En30
  wire signed [30:0] add_signext_30; // sfix31_En30
  wire signed [30:0] add_signext_31; // sfix31_En30
  wire signed [31:0] add_temp_15; // sfix32_En30
  reg  signed [34:0] sumpipe1_16; // sfix35_En30
  wire signed [34:0] sum1_17; // sfix35_En30
  wire signed [30:0] add_signext_32; // sfix31_En30
  wire signed [30:0] add_signext_33; // sfix31_En30
  wire signed [31:0] add_temp_16; // sfix32_En30
  reg  signed [34:0] sumpipe1_17; // sfix35_En30
  wire signed [34:0] sum1_18; // sfix35_En30
  wire signed [30:0] add_signext_34; // sfix31_En30
  wire signed [30:0] add_signext_35; // sfix31_En30
  wire signed [31:0] add_temp_17; // sfix32_En30
  reg  signed [34:0] sumpipe1_18; // sfix35_En30
  wire signed [34:0] sum1_19; // sfix35_En30
  wire signed [30:0] add_signext_36; // sfix31_En30
  wire signed [30:0] add_signext_37; // sfix31_En30
  wire signed [31:0] add_temp_18; // sfix32_En30
  reg  signed [34:0] sumpipe1_19; // sfix35_En30
  wire signed [34:0] sum1_20; // sfix35_En30
  wire signed [30:0] add_signext_38; // sfix31_En30
  wire signed [30:0] add_signext_39; // sfix31_En30
  wire signed [31:0] add_temp_19; // sfix32_En30
  reg  signed [34:0] sumpipe1_20; // sfix35_En30
  wire signed [34:0] sum1_21; // sfix35_En30
  wire signed [30:0] add_signext_40; // sfix31_En30
  wire signed [30:0] add_signext_41; // sfix31_En30
  wire signed [31:0] add_temp_20; // sfix32_En30
  reg  signed [34:0] sumpipe1_21; // sfix35_En30
  wire signed [34:0] sum1_22; // sfix35_En30
  wire signed [30:0] add_signext_42; // sfix31_En30
  wire signed [30:0] add_signext_43; // sfix31_En30
  wire signed [31:0] add_temp_21; // sfix32_En30
  reg  signed [34:0] sumpipe1_22; // sfix35_En30
  wire signed [34:0] sum1_23; // sfix35_En30
  wire signed [30:0] add_signext_44; // sfix31_En30
  wire signed [30:0] add_signext_45; // sfix31_En30
  wire signed [31:0] add_temp_22; // sfix32_En30
  reg  signed [34:0] sumpipe1_23; // sfix35_En30
  wire signed [34:0] sum1_24; // sfix35_En30
  wire signed [30:0] add_signext_46; // sfix31_En30
  wire signed [30:0] add_signext_47; // sfix31_En30
  wire signed [31:0] add_temp_23; // sfix32_En30
  reg  signed [34:0] sumpipe1_24; // sfix35_En30
  wire signed [34:0] sum1_25; // sfix35_En30
  wire signed [30:0] add_signext_48; // sfix31_En30
  wire signed [30:0] add_signext_49; // sfix31_En30
  wire signed [31:0] add_temp_24; // sfix32_En30
  reg  signed [34:0] sumpipe1_25; // sfix35_En30
  wire signed [34:0] sum1_26; // sfix35_En30
  wire signed [30:0] add_signext_50; // sfix31_En30
  wire signed [30:0] add_signext_51; // sfix31_En30
  wire signed [31:0] add_temp_25; // sfix32_En30
  reg  signed [34:0] sumpipe1_26; // sfix35_En30
  wire signed [34:0] sum1_27; // sfix35_En30
  wire signed [30:0] add_signext_52; // sfix31_En30
  wire signed [30:0] add_signext_53; // sfix31_En30
  wire signed [31:0] add_temp_26; // sfix32_En30
  reg  signed [34:0] sumpipe1_27; // sfix35_En30
  wire signed [34:0] sum1_28; // sfix35_En30
  wire signed [30:0] add_signext_54; // sfix31_En30
  wire signed [30:0] add_signext_55; // sfix31_En30
  wire signed [31:0] add_temp_27; // sfix32_En30
  reg  signed [34:0] sumpipe1_28; // sfix35_En30
  reg  signed [30:0] sumpipe1_29; // sfix31_En30
  wire signed [34:0] sum2_1; // sfix35_En30
  wire signed [34:0] add_signext_56; // sfix35_En30
  wire signed [34:0] add_signext_57; // sfix35_En30
  wire signed [35:0] add_temp_28; // sfix36_En30
  reg  signed [34:0] sumpipe2_1; // sfix35_En30
  wire signed [34:0] sum2_2; // sfix35_En30
  wire signed [34:0] add_signext_58; // sfix35_En30
  wire signed [34:0] add_signext_59; // sfix35_En30
  wire signed [35:0] add_temp_29; // sfix36_En30
  reg  signed [34:0] sumpipe2_2; // sfix35_En30
  wire signed [34:0] sum2_3; // sfix35_En30
  wire signed [34:0] add_signext_60; // sfix35_En30
  wire signed [34:0] add_signext_61; // sfix35_En30
  wire signed [35:0] add_temp_30; // sfix36_En30
  reg  signed [34:0] sumpipe2_3; // sfix35_En30
  wire signed [34:0] sum2_4; // sfix35_En30
  wire signed [34:0] add_signext_62; // sfix35_En30
  wire signed [34:0] add_signext_63; // sfix35_En30
  wire signed [35:0] add_temp_31; // sfix36_En30
  reg  signed [34:0] sumpipe2_4; // sfix35_En30
  wire signed [34:0] sum2_5; // sfix35_En30
  wire signed [34:0] add_signext_64; // sfix35_En30
  wire signed [34:0] add_signext_65; // sfix35_En30
  wire signed [35:0] add_temp_32; // sfix36_En30
  reg  signed [34:0] sumpipe2_5; // sfix35_En30
  wire signed [34:0] sum2_6; // sfix35_En30
  wire signed [34:0] add_signext_66; // sfix35_En30
  wire signed [34:0] add_signext_67; // sfix35_En30
  wire signed [35:0] add_temp_33; // sfix36_En30
  reg  signed [34:0] sumpipe2_6; // sfix35_En30
  wire signed [34:0] sum2_7; // sfix35_En30
  wire signed [34:0] add_signext_68; // sfix35_En30
  wire signed [34:0] add_signext_69; // sfix35_En30
  wire signed [35:0] add_temp_34; // sfix36_En30
  reg  signed [34:0] sumpipe2_7; // sfix35_En30
  wire signed [34:0] sum2_8; // sfix35_En30
  wire signed [34:0] add_signext_70; // sfix35_En30
  wire signed [34:0] add_signext_71; // sfix35_En30
  wire signed [35:0] add_temp_35; // sfix36_En30
  reg  signed [34:0] sumpipe2_8; // sfix35_En30
  wire signed [34:0] sum2_9; // sfix35_En30
  wire signed [34:0] add_signext_72; // sfix35_En30
  wire signed [34:0] add_signext_73; // sfix35_En30
  wire signed [35:0] add_temp_36; // sfix36_En30
  reg  signed [34:0] sumpipe2_9; // sfix35_En30
  wire signed [34:0] sum2_10; // sfix35_En30
  wire signed [34:0] add_signext_74; // sfix35_En30
  wire signed [34:0] add_signext_75; // sfix35_En30
  wire signed [35:0] add_temp_37; // sfix36_En30
  reg  signed [34:0] sumpipe2_10; // sfix35_En30
  wire signed [34:0] sum2_11; // sfix35_En30
  wire signed [34:0] add_signext_76; // sfix35_En30
  wire signed [34:0] add_signext_77; // sfix35_En30
  wire signed [35:0] add_temp_38; // sfix36_En30
  reg  signed [34:0] sumpipe2_11; // sfix35_En30
  wire signed [34:0] sum2_12; // sfix35_En30
  wire signed [34:0] add_signext_78; // sfix35_En30
  wire signed [34:0] add_signext_79; // sfix35_En30
  wire signed [35:0] add_temp_39; // sfix36_En30
  reg  signed [34:0] sumpipe2_12; // sfix35_En30
  wire signed [34:0] sum2_13; // sfix35_En30
  wire signed [34:0] add_signext_80; // sfix35_En30
  wire signed [34:0] add_signext_81; // sfix35_En30
  wire signed [35:0] add_temp_40; // sfix36_En30
  reg  signed [34:0] sumpipe2_13; // sfix35_En30
  wire signed [34:0] sum2_14; // sfix35_En30
  wire signed [34:0] add_signext_82; // sfix35_En30
  wire signed [34:0] add_signext_83; // sfix35_En30
  wire signed [35:0] add_temp_41; // sfix36_En30
  reg  signed [34:0] sumpipe2_14; // sfix35_En30
  reg  signed [30:0] sumpipe2_15; // sfix31_En30
  wire signed [34:0] sum3_1; // sfix35_En30
  wire signed [34:0] add_signext_84; // sfix35_En30
  wire signed [34:0] add_signext_85; // sfix35_En30
  wire signed [35:0] add_temp_42; // sfix36_En30
  reg  signed [34:0] sumpipe3_1; // sfix35_En30
  wire signed [34:0] sum3_2; // sfix35_En30
  wire signed [34:0] add_signext_86; // sfix35_En30
  wire signed [34:0] add_signext_87; // sfix35_En30
  wire signed [35:0] add_temp_43; // sfix36_En30
  reg  signed [34:0] sumpipe3_2; // sfix35_En30
  wire signed [34:0] sum3_3; // sfix35_En30
  wire signed [34:0] add_signext_88; // sfix35_En30
  wire signed [34:0] add_signext_89; // sfix35_En30
  wire signed [35:0] add_temp_44; // sfix36_En30
  reg  signed [34:0] sumpipe3_3; // sfix35_En30
  wire signed [34:0] sum3_4; // sfix35_En30
  wire signed [34:0] add_signext_90; // sfix35_En30
  wire signed [34:0] add_signext_91; // sfix35_En30
  wire signed [35:0] add_temp_45; // sfix36_En30
  reg  signed [34:0] sumpipe3_4; // sfix35_En30
  wire signed [34:0] sum3_5; // sfix35_En30
  wire signed [34:0] add_signext_92; // sfix35_En30
  wire signed [34:0] add_signext_93; // sfix35_En30
  wire signed [35:0] add_temp_46; // sfix36_En30
  reg  signed [34:0] sumpipe3_5; // sfix35_En30
  wire signed [34:0] sum3_6; // sfix35_En30
  wire signed [34:0] add_signext_94; // sfix35_En30
  wire signed [34:0] add_signext_95; // sfix35_En30
  wire signed [35:0] add_temp_47; // sfix36_En30
  reg  signed [34:0] sumpipe3_6; // sfix35_En30
  wire signed [34:0] sum3_7; // sfix35_En30
  wire signed [34:0] add_signext_96; // sfix35_En30
  wire signed [34:0] add_signext_97; // sfix35_En30
  wire signed [35:0] add_temp_48; // sfix36_En30
  reg  signed [34:0] sumpipe3_7; // sfix35_En30
  reg  signed [30:0] sumpipe3_8; // sfix31_En30
  wire signed [34:0] sum4_1; // sfix35_En30
  wire signed [34:0] add_signext_98; // sfix35_En30
  wire signed [34:0] add_signext_99; // sfix35_En30
  wire signed [35:0] add_temp_49; // sfix36_En30
  reg  signed [34:0] sumpipe4_1; // sfix35_En30
  wire signed [34:0] sum4_2; // sfix35_En30
  wire signed [34:0] add_signext_100; // sfix35_En30
  wire signed [34:0] add_signext_101; // sfix35_En30
  wire signed [35:0] add_temp_50; // sfix36_En30
  reg  signed [34:0] sumpipe4_2; // sfix35_En30
  wire signed [34:0] sum4_3; // sfix35_En30
  wire signed [34:0] add_signext_102; // sfix35_En30
  wire signed [34:0] add_signext_103; // sfix35_En30
  wire signed [35:0] add_temp_51; // sfix36_En30
  reg  signed [34:0] sumpipe4_3; // sfix35_En30
  wire signed [34:0] sum4_4; // sfix35_En30
  wire signed [34:0] add_signext_104; // sfix35_En30
  wire signed [34:0] add_signext_105; // sfix35_En30
  wire signed [35:0] add_temp_52; // sfix36_En30
  reg  signed [34:0] sumpipe4_4; // sfix35_En30
  wire signed [34:0] sum5_1; // sfix35_En30
  wire signed [34:0] add_signext_106; // sfix35_En30
  wire signed [34:0] add_signext_107; // sfix35_En30
  wire signed [35:0] add_temp_53; // sfix36_En30
  reg  signed [34:0] sumpipe5_1; // sfix35_En30
  wire signed [34:0] sum5_2; // sfix35_En30
  wire signed [34:0] add_signext_108; // sfix35_En30
  wire signed [34:0] add_signext_109; // sfix35_En30
  wire signed [35:0] add_temp_54; // sfix36_En30
  reg  signed [34:0] sumpipe5_2; // sfix35_En30
  wire signed [34:0] sum6_1; // sfix35_En30
  wire signed [34:0] add_signext_110; // sfix35_En30
  wire signed [34:0] add_signext_111; // sfix35_En30
  wire signed [35:0] add_temp_55; // sfix36_En30
  reg  signed [34:0] sumpipe6_1; // sfix35_En30
  wire signed [15:0] output_typeconvert; // sfix16_En14
  reg  signed [15:0] output_register; // sfix16_En14

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
        delay_pipeline[53] <= 0;
        delay_pipeline[54] <= 0;
        delay_pipeline[55] <= 0;
        delay_pipeline[56] <= 0;
        delay_pipeline[57] <= 0;
        delay_pipeline[58] <= 0;
        delay_pipeline[59] <= 0;
        delay_pipeline[60] <= 0;
        delay_pipeline[61] <= 0;
        delay_pipeline[62] <= 0;
        delay_pipeline[63] <= 0;
        delay_pipeline[64] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
          delay_pipeline[53] <= delay_pipeline[52];
          delay_pipeline[54] <= delay_pipeline[53];
          delay_pipeline[55] <= delay_pipeline[54];
          delay_pipeline[56] <= delay_pipeline[55];
          delay_pipeline[57] <= delay_pipeline[56];
          delay_pipeline[58] <= delay_pipeline[57];
          delay_pipeline[59] <= delay_pipeline[58];
          delay_pipeline[60] <= delay_pipeline[59];
          delay_pipeline[61] <= delay_pipeline[60];
          delay_pipeline[62] <= delay_pipeline[61];
          delay_pipeline[63] <= delay_pipeline[62];
          delay_pipeline[64] <= delay_pipeline[63];
        end
      end
    end // Delay_Pipeline_process


  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        delay_pipeline_63_under_pipe <= 0;
        coeff64_pipe <= 0;
        product64_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_63_under_pipe <= delay_pipeline[63];
          coeff64_pipe <= coeff64;

          product64_pipe <= delay_pipeline_63_under_pipe * coeff64_pipe;

        end
      end
    end // temp_process1

  assign product64 = product64_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        delay_pipeline_62_under_pipe <= 0;
        coeff63_pipe <= 0;
        product63_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_62_under_pipe <= delay_pipeline[62];
          coeff63_pipe <= coeff63;

          product63_pipe <= delay_pipeline_62_under_pipe * coeff63_pipe;

        end
      end
    end // temp_process2

  assign product63 = product63_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        delay_pipeline_61_under_pipe <= 0;
        coeff62_pipe <= 0;
        product62_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_61_under_pipe <= delay_pipeline[61];
          coeff62_pipe <= coeff62;

          product62_pipe <= delay_pipeline_61_under_pipe * coeff62_pipe;

        end
      end
    end // temp_process3

  assign product62 = product62_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        delay_pipeline_60_under_pipe <= 0;
        coeff61_pipe <= 0;
        product61_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_60_under_pipe <= delay_pipeline[60];
          coeff61_pipe <= coeff61;

          product61_pipe <= delay_pipeline_60_under_pipe * coeff61_pipe;

        end
      end
    end // temp_process4

  assign product61 = product61_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        delay_pipeline_59_under_pipe <= 0;
        coeff60_pipe <= 0;
        product60_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_59_under_pipe <= delay_pipeline[59];
          coeff60_pipe <= coeff60;

          product60_pipe <= delay_pipeline_59_under_pipe * coeff60_pipe;

        end
      end
    end // temp_process5

  assign product60 = product60_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process6
      if (reset == 1'b1) begin
        delay_pipeline_58_under_pipe <= 0;
        coeff59_pipe <= 0;
        product59_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_58_under_pipe <= delay_pipeline[58];
          coeff59_pipe <= coeff59;

          product59_pipe <= delay_pipeline_58_under_pipe * coeff59_pipe;

        end
      end
    end // temp_process6

  assign product59 = product59_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process7
      if (reset == 1'b1) begin
        delay_pipeline_57_under_pipe <= 0;
        coeff58_pipe <= 0;
        product58_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_57_under_pipe <= delay_pipeline[57];
          coeff58_pipe <= coeff58;

          product58_pipe <= delay_pipeline_57_under_pipe * coeff58_pipe;

        end
      end
    end // temp_process7

  assign product58 = product58_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process8
      if (reset == 1'b1) begin
        delay_pipeline_55_under_pipe <= 0;
        coeff56_pipe <= 0;
        product56_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_55_under_pipe <= delay_pipeline[55];
          coeff56_pipe <= coeff56;

          product56_pipe <= delay_pipeline_55_under_pipe * coeff56_pipe;

        end
      end
    end // temp_process8

  assign product56 = product56_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process9
      if (reset == 1'b1) begin
        delay_pipeline_54_under_pipe <= 0;
        coeff55_pipe <= 0;
        product55_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_54_under_pipe <= delay_pipeline[54];
          coeff55_pipe <= coeff55;

          product55_pipe <= delay_pipeline_54_under_pipe * coeff55_pipe;

        end
      end
    end // temp_process9

  assign product55 = product55_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process10
      if (reset == 1'b1) begin
        delay_pipeline_53_under_pipe <= 0;
        coeff54_pipe <= 0;
        product54_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_53_under_pipe <= delay_pipeline[53];
          coeff54_pipe <= coeff54;

          product54_pipe <= delay_pipeline_53_under_pipe * coeff54_pipe;

        end
      end
    end // temp_process10

  assign product54 = product54_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process11
      if (reset == 1'b1) begin
        delay_pipeline_52_under_pipe <= 0;
        coeff53_pipe <= 0;
        product53_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_52_under_pipe <= delay_pipeline[52];
          coeff53_pipe <= coeff53;

          product53_pipe <= delay_pipeline_52_under_pipe * coeff53_pipe;

        end
      end
    end // temp_process11

  assign product53 = product53_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process12
      if (reset == 1'b1) begin
        delay_pipeline_51_under_pipe <= 0;
        coeff52_pipe <= 0;
        product52_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_51_under_pipe <= delay_pipeline[51];
          coeff52_pipe <= coeff52;

          product52_pipe <= delay_pipeline_51_under_pipe * coeff52_pipe;

        end
      end
    end // temp_process12

  assign product52 = product52_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process13
      if (reset == 1'b1) begin
        delay_pipeline_50_under_pipe <= 0;
        coeff51_pipe <= 0;
        product51_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_50_under_pipe <= delay_pipeline[50];
          coeff51_pipe <= coeff51;

          product51_pipe <= delay_pipeline_50_under_pipe * coeff51_pipe;

        end
      end
    end // temp_process13

  assign product51 = product51_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process14
      if (reset == 1'b1) begin
        delay_pipeline_49_under_pipe <= 0;
        coeff50_pipe <= 0;
        product50_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_49_under_pipe <= delay_pipeline[49];
          coeff50_pipe <= coeff50;

          product50_pipe <= delay_pipeline_49_under_pipe * coeff50_pipe;

        end
      end
    end // temp_process14

  assign product50 = product50_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process15
      if (reset == 1'b1) begin
        delay_pipeline_47_under_pipe <= 0;
        coeff48_pipe <= 0;
        product48_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_47_under_pipe <= delay_pipeline[47];
          coeff48_pipe <= coeff48;

          product48_pipe <= delay_pipeline_47_under_pipe * coeff48_pipe;

        end
      end
    end // temp_process15

  assign product48 = product48_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process16
      if (reset == 1'b1) begin
        delay_pipeline_46_under_pipe <= 0;
        coeff47_pipe <= 0;
        product47_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_46_under_pipe <= delay_pipeline[46];
          coeff47_pipe <= coeff47;

          product47_pipe <= delay_pipeline_46_under_pipe * coeff47_pipe;

        end
      end
    end // temp_process16

  assign product47 = product47_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process17
      if (reset == 1'b1) begin
        delay_pipeline_45_under_pipe <= 0;
        coeff46_pipe <= 0;
        product46_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_45_under_pipe <= delay_pipeline[45];
          coeff46_pipe <= coeff46;

          product46_pipe <= delay_pipeline_45_under_pipe * coeff46_pipe;

        end
      end
    end // temp_process17

  assign product46 = product46_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process18
      if (reset == 1'b1) begin
        delay_pipeline_44_under_pipe <= 0;
        coeff45_pipe <= 0;
        product45_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_44_under_pipe <= delay_pipeline[44];
          coeff45_pipe <= coeff45;

          product45_pipe <= delay_pipeline_44_under_pipe * coeff45_pipe;

        end
      end
    end // temp_process18

  assign product45 = product45_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process19
      if (reset == 1'b1) begin
        delay_pipeline_43_under_pipe <= 0;
        coeff44_pipe <= 0;
        product44_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_43_under_pipe <= delay_pipeline[43];
          coeff44_pipe <= coeff44;

          product44_pipe <= delay_pipeline_43_under_pipe * coeff44_pipe;

        end
      end
    end // temp_process19

  assign product44 = product44_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process20
      if (reset == 1'b1) begin
        delay_pipeline_42_under_pipe <= 0;
        coeff43_pipe <= 0;
        product43_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_42_under_pipe <= delay_pipeline[42];
          coeff43_pipe <= coeff43;

          product43_pipe <= delay_pipeline_42_under_pipe * coeff43_pipe;

        end
      end
    end // temp_process20

  assign product43 = product43_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process21
      if (reset == 1'b1) begin
        delay_pipeline_41_under_pipe <= 0;
        coeff42_pipe <= 0;
        product42_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_41_under_pipe <= delay_pipeline[41];
          coeff42_pipe <= coeff42;

          product42_pipe <= delay_pipeline_41_under_pipe * coeff42_pipe;

        end
      end
    end // temp_process21

  assign product42 = product42_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process22
      if (reset == 1'b1) begin
        delay_pipeline_39_under_pipe <= 0;
        coeff40_pipe <= 0;
        product40_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_39_under_pipe <= delay_pipeline[39];
          coeff40_pipe <= coeff40;

          product40_pipe <= delay_pipeline_39_under_pipe * coeff40_pipe;

        end
      end
    end // temp_process22

  assign product40 = product40_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process23
      if (reset == 1'b1) begin
        delay_pipeline_38_under_pipe <= 0;
        coeff39_pipe <= 0;
        product39_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_38_under_pipe <= delay_pipeline[38];
          coeff39_pipe <= coeff39;

          product39_pipe <= delay_pipeline_38_under_pipe * coeff39_pipe;

        end
      end
    end // temp_process23

  assign product39 = product39_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process24
      if (reset == 1'b1) begin
        delay_pipeline_37_under_pipe <= 0;
        coeff38_pipe <= 0;
        product38_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_37_under_pipe <= delay_pipeline[37];
          coeff38_pipe <= coeff38;

          product38_pipe <= delay_pipeline_37_under_pipe * coeff38_pipe;

        end
      end
    end // temp_process24

  assign product38 = product38_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process25
      if (reset == 1'b1) begin
        delay_pipeline_36_under_pipe <= 0;
        coeff37_pipe <= 0;
        product37_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_36_under_pipe <= delay_pipeline[36];
          coeff37_pipe <= coeff37;

          product37_pipe <= delay_pipeline_36_under_pipe * coeff37_pipe;

        end
      end
    end // temp_process25

  assign product37 = product37_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process26
      if (reset == 1'b1) begin
        delay_pipeline_35_under_pipe <= 0;
        coeff36_pipe <= 0;
        product36_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_35_under_pipe <= delay_pipeline[35];
          coeff36_pipe <= coeff36;

          product36_pipe <= delay_pipeline_35_under_pipe * coeff36_pipe;

        end
      end
    end // temp_process26

  assign product36 = product36_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process27
      if (reset == 1'b1) begin
        delay_pipeline_34_under_pipe <= 0;
        coeff35_pipe <= 0;
        product35_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_34_under_pipe <= delay_pipeline[34];
          coeff35_pipe <= coeff35;

          product35_pipe <= delay_pipeline_34_under_pipe * coeff35_pipe;

        end
      end
    end // temp_process27

  assign product35 = product35_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process28
      if (reset == 1'b1) begin
        delay_pipeline_33_under_pipe <= 0;
        coeff34_pipe <= 0;
        product34_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_33_under_pipe <= delay_pipeline[33];
          coeff34_pipe <= coeff34;

          product34_pipe <= delay_pipeline_33_under_pipe * coeff34_pipe;

        end
      end
    end // temp_process28

  assign product34 = product34_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process29
      if (reset == 1'b1) begin
        delay_pipeline_32_under_pipe <= 0;
        coeff33_pipe <= 0;
        product33_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_32_under_pipe <= delay_pipeline[32];
          coeff33_pipe <= coeff33;

          product33_pipe <= delay_pipeline_32_under_pipe * coeff33_pipe;

        end
      end
    end // temp_process29

  assign product33 = product33_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process30
      if (reset == 1'b1) begin
        delay_pipeline_31_under_pipe <= 0;
        coeff32_pipe <= 0;
        product32_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_31_under_pipe <= delay_pipeline[31];
          coeff32_pipe <= coeff32;

          product32_pipe <= delay_pipeline_31_under_pipe * coeff32_pipe;

        end
      end
    end // temp_process30

  assign product32 = product32_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process31
      if (reset == 1'b1) begin
        delay_pipeline_30_under_pipe <= 0;
        coeff31_pipe <= 0;
        product31_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_30_under_pipe <= delay_pipeline[30];
          coeff31_pipe <= coeff31;

          product31_pipe <= delay_pipeline_30_under_pipe * coeff31_pipe;

        end
      end
    end // temp_process31

  assign product31 = product31_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process32
      if (reset == 1'b1) begin
        delay_pipeline_29_under_pipe <= 0;
        coeff30_pipe <= 0;
        product30_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_29_under_pipe <= delay_pipeline[29];
          coeff30_pipe <= coeff30;

          product30_pipe <= delay_pipeline_29_under_pipe * coeff30_pipe;

        end
      end
    end // temp_process32

  assign product30 = product30_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process33
      if (reset == 1'b1) begin
        delay_pipeline_28_under_pipe <= 0;
        coeff29_pipe <= 0;
        product29_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_28_under_pipe <= delay_pipeline[28];
          coeff29_pipe <= coeff29;

          product29_pipe <= delay_pipeline_28_under_pipe * coeff29_pipe;

        end
      end
    end // temp_process33

  assign product29 = product29_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process34
      if (reset == 1'b1) begin
        delay_pipeline_27_under_pipe <= 0;
        coeff28_pipe <= 0;
        product28_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_27_under_pipe <= delay_pipeline[27];
          coeff28_pipe <= coeff28;

          product28_pipe <= delay_pipeline_27_under_pipe * coeff28_pipe;

        end
      end
    end // temp_process34

  assign product28 = product28_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process35
      if (reset == 1'b1) begin
        delay_pipeline_26_under_pipe <= 0;
        coeff27_pipe <= 0;
        product27_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_26_under_pipe <= delay_pipeline[26];
          coeff27_pipe <= coeff27;

          product27_pipe <= delay_pipeline_26_under_pipe * coeff27_pipe;

        end
      end
    end // temp_process35

  assign product27 = product27_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process36
      if (reset == 1'b1) begin
        delay_pipeline_25_under_pipe <= 0;
        coeff26_pipe <= 0;
        product26_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_25_under_pipe <= delay_pipeline[25];
          coeff26_pipe <= coeff26;

          product26_pipe <= delay_pipeline_25_under_pipe * coeff26_pipe;

        end
      end
    end // temp_process36

  assign product26 = product26_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process37
      if (reset == 1'b1) begin
        delay_pipeline_23_under_pipe <= 0;
        coeff24_pipe <= 0;
        product24_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_23_under_pipe <= delay_pipeline[23];
          coeff24_pipe <= coeff24;

          product24_pipe <= delay_pipeline_23_under_pipe * coeff24_pipe;

        end
      end
    end // temp_process37

  assign product24 = product24_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process38
      if (reset == 1'b1) begin
        delay_pipeline_22_under_pipe <= 0;
        coeff23_pipe <= 0;
        product23_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_22_under_pipe <= delay_pipeline[22];
          coeff23_pipe <= coeff23;

          product23_pipe <= delay_pipeline_22_under_pipe * coeff23_pipe;

        end
      end
    end // temp_process38

  assign product23 = product23_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process39
      if (reset == 1'b1) begin
        delay_pipeline_21_under_pipe <= 0;
        coeff22_pipe <= 0;
        product22_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_21_under_pipe <= delay_pipeline[21];
          coeff22_pipe <= coeff22;

          product22_pipe <= delay_pipeline_21_under_pipe * coeff22_pipe;

        end
      end
    end // temp_process39

  assign product22 = product22_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process40
      if (reset == 1'b1) begin
        delay_pipeline_20_under_pipe <= 0;
        coeff21_pipe <= 0;
        product21_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_20_under_pipe <= delay_pipeline[20];
          coeff21_pipe <= coeff21;

          product21_pipe <= delay_pipeline_20_under_pipe * coeff21_pipe;

        end
      end
    end // temp_process40

  assign product21 = product21_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process41
      if (reset == 1'b1) begin
        delay_pipeline_19_under_pipe <= 0;
        coeff20_pipe <= 0;
        product20_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_19_under_pipe <= delay_pipeline[19];
          coeff20_pipe <= coeff20;

          product20_pipe <= delay_pipeline_19_under_pipe * coeff20_pipe;

        end
      end
    end // temp_process41

  assign product20 = product20_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process42
      if (reset == 1'b1) begin
        delay_pipeline_18_under_pipe <= 0;
        coeff19_pipe <= 0;
        product19_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_18_under_pipe <= delay_pipeline[18];
          coeff19_pipe <= coeff19;

          product19_pipe <= delay_pipeline_18_under_pipe * coeff19_pipe;

        end
      end
    end // temp_process42

  assign product19 = product19_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process43
      if (reset == 1'b1) begin
        delay_pipeline_17_under_pipe <= 0;
        coeff18_pipe <= 0;
        product18_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_17_under_pipe <= delay_pipeline[17];
          coeff18_pipe <= coeff18;

          product18_pipe <= delay_pipeline_17_under_pipe * coeff18_pipe;

        end
      end
    end // temp_process43

  assign product18 = product18_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process44
      if (reset == 1'b1) begin
        delay_pipeline_15_under_pipe <= 0;
        coeff16_pipe <= 0;
        product16_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_15_under_pipe <= delay_pipeline[15];
          coeff16_pipe <= coeff16;

          product16_pipe <= delay_pipeline_15_under_pipe * coeff16_pipe;

        end
      end
    end // temp_process44

  assign product16 = product16_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process45
      if (reset == 1'b1) begin
        delay_pipeline_14_under_pipe <= 0;
        coeff15_pipe <= 0;
        product15_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_14_under_pipe <= delay_pipeline[14];
          coeff15_pipe <= coeff15;

          product15_pipe <= delay_pipeline_14_under_pipe * coeff15_pipe;

        end
      end
    end // temp_process45

  assign product15 = product15_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process46
      if (reset == 1'b1) begin
        delay_pipeline_13_under_pipe <= 0;
        coeff14_pipe <= 0;
        product14_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_13_under_pipe <= delay_pipeline[13];
          coeff14_pipe <= coeff14;

          product14_pipe <= delay_pipeline_13_under_pipe * coeff14_pipe;

        end
      end
    end // temp_process46

  assign product14 = product14_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process47
      if (reset == 1'b1) begin
        delay_pipeline_12_under_pipe <= 0;
        coeff13_pipe <= 0;
        product13_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_12_under_pipe <= delay_pipeline[12];
          coeff13_pipe <= coeff13;

          product13_pipe <= delay_pipeline_12_under_pipe * coeff13_pipe;

        end
      end
    end // temp_process47

  assign product13 = product13_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process48
      if (reset == 1'b1) begin
        delay_pipeline_11_under_pipe <= 0;
        coeff12_pipe <= 0;
        product12_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_11_under_pipe <= delay_pipeline[11];
          coeff12_pipe <= coeff12;

          product12_pipe <= delay_pipeline_11_under_pipe * coeff12_pipe;

        end
      end
    end // temp_process48

  assign product12 = product12_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process49
      if (reset == 1'b1) begin
        delay_pipeline_10_under_pipe <= 0;
        coeff11_pipe <= 0;
        product11_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_10_under_pipe <= delay_pipeline[10];
          coeff11_pipe <= coeff11;

          product11_pipe <= delay_pipeline_10_under_pipe * coeff11_pipe;

        end
      end
    end // temp_process49

  assign product11 = product11_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process50
      if (reset == 1'b1) begin
        delay_pipeline_9_under_pipe <= 0;
        coeff10_pipe <= 0;
        product10_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_9_under_pipe <= delay_pipeline[9];
          coeff10_pipe <= coeff10;

          product10_pipe <= delay_pipeline_9_under_pipe * coeff10_pipe;

        end
      end
    end // temp_process50

  assign product10 = product10_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process51
      if (reset == 1'b1) begin
        delay_pipeline_7_under_pipe <= 0;
        coeff8_pipe <= 0;
        product8_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_7_under_pipe <= delay_pipeline[7];
          coeff8_pipe <= coeff8;

          product8_pipe <= delay_pipeline_7_under_pipe * coeff8_pipe;

        end
      end
    end // temp_process51

  assign product8 = product8_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process52
      if (reset == 1'b1) begin
        delay_pipeline_6_under_pipe <= 0;
        coeff7_pipe <= 0;
        product7_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_6_under_pipe <= delay_pipeline[6];
          coeff7_pipe <= coeff7;

          product7_pipe <= delay_pipeline_6_under_pipe * coeff7_pipe;

        end
      end
    end // temp_process52

  assign product7 = product7_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process53
      if (reset == 1'b1) begin
        delay_pipeline_5_under_pipe <= 0;
        coeff6_pipe <= 0;
        product6_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_5_under_pipe <= delay_pipeline[5];
          coeff6_pipe <= coeff6;

          product6_pipe <= delay_pipeline_5_under_pipe * coeff6_pipe;

        end
      end
    end // temp_process53

  assign product6 = product6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process54
      if (reset == 1'b1) begin
        delay_pipeline_4_under_pipe <= 0;
        coeff5_pipe <= 0;
        product5_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_4_under_pipe <= delay_pipeline[4];
          coeff5_pipe <= coeff5;

          product5_pipe <= delay_pipeline_4_under_pipe * coeff5_pipe;

        end
      end
    end // temp_process54

  assign product5 = product5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process55
      if (reset == 1'b1) begin
        delay_pipeline_3_under_pipe <= 0;
        coeff4_pipe <= 0;
        product4_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_3_under_pipe <= delay_pipeline[3];
          coeff4_pipe <= coeff4;

          product4_pipe <= delay_pipeline_3_under_pipe * coeff4_pipe;

        end
      end
    end // temp_process55

  assign product4 = product4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process56
      if (reset == 1'b1) begin
        delay_pipeline_2_under_pipe <= 0;
        coeff3_pipe <= 0;
        product3_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_2_under_pipe <= delay_pipeline[2];
          coeff3_pipe <= coeff3;

          product3_pipe <= delay_pipeline_2_under_pipe * coeff3_pipe;

        end
      end
    end // temp_process56

  assign product3 = product3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process57
      if (reset == 1'b1) begin
        delay_pipeline_1_under_pipe <= 0;
        coeff2_pipe <= 0;
        product2_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_1_under_pipe <= delay_pipeline[1];
          coeff2_pipe <= coeff2;

          product2_pipe <= delay_pipeline_1_under_pipe * coeff2_pipe;

        end
      end
    end // temp_process57

  assign product2 = product2_pipe[30:0];

  assign add_signext = product64;
  assign add_signext_1 = product63;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{3{add_temp[31]}}, add_temp});

  assign add_signext_2 = product62;
  assign add_signext_3 = product61;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{3{add_temp_1[31]}}, add_temp_1});

  assign add_signext_4 = product60;
  assign add_signext_5 = product59;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{3{add_temp_2[31]}}, add_temp_2});

  assign add_signext_6 = product58;
  assign add_signext_7 = product56;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum1_4 = $signed({{3{add_temp_3[31]}}, add_temp_3});

  assign add_signext_8 = product55;
  assign add_signext_9 = product54;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum1_5 = $signed({{3{add_temp_4[31]}}, add_temp_4});

  assign add_signext_10 = product53;
  assign add_signext_11 = product52;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum1_6 = $signed({{3{add_temp_5[31]}}, add_temp_5});

  assign add_signext_12 = product51;
  assign add_signext_13 = product50;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum1_7 = $signed({{3{add_temp_6[31]}}, add_temp_6});

  assign add_signext_14 = product48;
  assign add_signext_15 = product47;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum1_8 = $signed({{3{add_temp_7[31]}}, add_temp_7});

  assign add_signext_16 = product46;
  assign add_signext_17 = product45;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum1_9 = $signed({{3{add_temp_8[31]}}, add_temp_8});

  assign add_signext_18 = product44;
  assign add_signext_19 = product43;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum1_10 = $signed({{3{add_temp_9[31]}}, add_temp_9});

  assign add_signext_20 = product42;
  assign add_signext_21 = product40;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum1_11 = $signed({{3{add_temp_10[31]}}, add_temp_10});

  assign add_signext_22 = product39;
  assign add_signext_23 = product38;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum1_12 = $signed({{3{add_temp_11[31]}}, add_temp_11});

  assign add_signext_24 = product37;
  assign add_signext_25 = product36;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum1_13 = $signed({{3{add_temp_12[31]}}, add_temp_12});

  assign add_signext_26 = product35;
  assign add_signext_27 = product34;
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum1_14 = $signed({{3{add_temp_13[31]}}, add_temp_13});

  assign add_signext_28 = product33;
  assign add_signext_29 = product32;
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum1_15 = $signed({{3{add_temp_14[31]}}, add_temp_14});

  assign add_signext_30 = product31;
  assign add_signext_31 = product30;
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum1_16 = $signed({{3{add_temp_15[31]}}, add_temp_15});

  assign add_signext_32 = product29;
  assign add_signext_33 = product28;
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum1_17 = $signed({{3{add_temp_16[31]}}, add_temp_16});

  assign add_signext_34 = product27;
  assign add_signext_35 = product26;
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum1_18 = $signed({{3{add_temp_17[31]}}, add_temp_17});

  assign add_signext_36 = product24;
  assign add_signext_37 = product23;
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum1_19 = $signed({{3{add_temp_18[31]}}, add_temp_18});

  assign add_signext_38 = product22;
  assign add_signext_39 = product21;
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum1_20 = $signed({{3{add_temp_19[31]}}, add_temp_19});

  assign add_signext_40 = product20;
  assign add_signext_41 = product19;
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum1_21 = $signed({{3{add_temp_20[31]}}, add_temp_20});

  assign add_signext_42 = product18;
  assign add_signext_43 = product16;
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum1_22 = $signed({{3{add_temp_21[31]}}, add_temp_21});

  assign add_signext_44 = product15;
  assign add_signext_45 = product14;
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum1_23 = $signed({{3{add_temp_22[31]}}, add_temp_22});

  assign add_signext_46 = product13;
  assign add_signext_47 = product12;
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum1_24 = $signed({{3{add_temp_23[31]}}, add_temp_23});

  assign add_signext_48 = product11;
  assign add_signext_49 = product10;
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum1_25 = $signed({{3{add_temp_24[31]}}, add_temp_24});

  assign add_signext_50 = product8;
  assign add_signext_51 = product7;
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum1_26 = $signed({{3{add_temp_25[31]}}, add_temp_25});

  assign add_signext_52 = product6;
  assign add_signext_53 = product5;
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum1_27 = $signed({{3{add_temp_26[31]}}, add_temp_26});

  assign add_signext_54 = product4;
  assign add_signext_55 = product3;
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum1_28 = $signed({{3{add_temp_27[31]}}, add_temp_27});

  always @ (posedge clk or posedge reset)
    begin: temp_process58
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
        sumpipe1_3 <= 0;
        sumpipe1_4 <= 0;
        sumpipe1_5 <= 0;
        sumpipe1_6 <= 0;
        sumpipe1_7 <= 0;
        sumpipe1_8 <= 0;
        sumpipe1_9 <= 0;
        sumpipe1_10 <= 0;
        sumpipe1_11 <= 0;
        sumpipe1_12 <= 0;
        sumpipe1_13 <= 0;
        sumpipe1_14 <= 0;
        sumpipe1_15 <= 0;
        sumpipe1_16 <= 0;
        sumpipe1_17 <= 0;
        sumpipe1_18 <= 0;
        sumpipe1_19 <= 0;
        sumpipe1_20 <= 0;
        sumpipe1_21 <= 0;
        sumpipe1_22 <= 0;
        sumpipe1_23 <= 0;
        sumpipe1_24 <= 0;
        sumpipe1_25 <= 0;
        sumpipe1_26 <= 0;
        sumpipe1_27 <= 0;
        sumpipe1_28 <= 0;
        sumpipe1_29 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
          sumpipe1_3 <= sum1_3;
          sumpipe1_4 <= sum1_4;
          sumpipe1_5 <= sum1_5;
          sumpipe1_6 <= sum1_6;
          sumpipe1_7 <= sum1_7;
          sumpipe1_8 <= sum1_8;
          sumpipe1_9 <= sum1_9;
          sumpipe1_10 <= sum1_10;
          sumpipe1_11 <= sum1_11;
          sumpipe1_12 <= sum1_12;
          sumpipe1_13 <= sum1_13;
          sumpipe1_14 <= sum1_14;
          sumpipe1_15 <= sum1_15;
          sumpipe1_16 <= sum1_16;
          sumpipe1_17 <= sum1_17;
          sumpipe1_18 <= sum1_18;
          sumpipe1_19 <= sum1_19;
          sumpipe1_20 <= sum1_20;
          sumpipe1_21 <= sum1_21;
          sumpipe1_22 <= sum1_22;
          sumpipe1_23 <= sum1_23;
          sumpipe1_24 <= sum1_24;
          sumpipe1_25 <= sum1_25;
          sumpipe1_26 <= sum1_26;
          sumpipe1_27 <= sum1_27;
          sumpipe1_28 <= sum1_28;
          sumpipe1_29 <= product2;
        end
      end
    end // temp_process58

  assign add_signext_56 = sumpipe1_1;
  assign add_signext_57 = sumpipe1_2;
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum2_1 = add_temp_28[34:0];

  assign add_signext_58 = sumpipe1_3;
  assign add_signext_59 = sumpipe1_4;
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum2_2 = add_temp_29[34:0];

  assign add_signext_60 = sumpipe1_5;
  assign add_signext_61 = sumpipe1_6;
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum2_3 = add_temp_30[34:0];

  assign add_signext_62 = sumpipe1_7;
  assign add_signext_63 = sumpipe1_8;
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum2_4 = add_temp_31[34:0];

  assign add_signext_64 = sumpipe1_9;
  assign add_signext_65 = sumpipe1_10;
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum2_5 = add_temp_32[34:0];

  assign add_signext_66 = sumpipe1_11;
  assign add_signext_67 = sumpipe1_12;
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum2_6 = add_temp_33[34:0];

  assign add_signext_68 = sumpipe1_13;
  assign add_signext_69 = sumpipe1_14;
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum2_7 = add_temp_34[34:0];

  assign add_signext_70 = sumpipe1_15;
  assign add_signext_71 = sumpipe1_16;
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum2_8 = add_temp_35[34:0];

  assign add_signext_72 = sumpipe1_17;
  assign add_signext_73 = sumpipe1_18;
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum2_9 = add_temp_36[34:0];

  assign add_signext_74 = sumpipe1_19;
  assign add_signext_75 = sumpipe1_20;
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum2_10 = add_temp_37[34:0];

  assign add_signext_76 = sumpipe1_21;
  assign add_signext_77 = sumpipe1_22;
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum2_11 = add_temp_38[34:0];

  assign add_signext_78 = sumpipe1_23;
  assign add_signext_79 = sumpipe1_24;
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum2_12 = add_temp_39[34:0];

  assign add_signext_80 = sumpipe1_25;
  assign add_signext_81 = sumpipe1_26;
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum2_13 = add_temp_40[34:0];

  assign add_signext_82 = sumpipe1_27;
  assign add_signext_83 = sumpipe1_28;
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum2_14 = add_temp_41[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process59
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
        sumpipe2_2 <= 0;
        sumpipe2_3 <= 0;
        sumpipe2_4 <= 0;
        sumpipe2_5 <= 0;
        sumpipe2_6 <= 0;
        sumpipe2_7 <= 0;
        sumpipe2_8 <= 0;
        sumpipe2_9 <= 0;
        sumpipe2_10 <= 0;
        sumpipe2_11 <= 0;
        sumpipe2_12 <= 0;
        sumpipe2_13 <= 0;
        sumpipe2_14 <= 0;
        sumpipe2_15 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
          sumpipe2_2 <= sum2_2;
          sumpipe2_3 <= sum2_3;
          sumpipe2_4 <= sum2_4;
          sumpipe2_5 <= sum2_5;
          sumpipe2_6 <= sum2_6;
          sumpipe2_7 <= sum2_7;
          sumpipe2_8 <= sum2_8;
          sumpipe2_9 <= sum2_9;
          sumpipe2_10 <= sum2_10;
          sumpipe2_11 <= sum2_11;
          sumpipe2_12 <= sum2_12;
          sumpipe2_13 <= sum2_13;
          sumpipe2_14 <= sum2_14;
          sumpipe2_15 <= sumpipe1_29;
        end
      end
    end // temp_process59

  assign add_signext_84 = sumpipe2_1;
  assign add_signext_85 = sumpipe2_2;
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum3_1 = add_temp_42[34:0];

  assign add_signext_86 = sumpipe2_3;
  assign add_signext_87 = sumpipe2_4;
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum3_2 = add_temp_43[34:0];

  assign add_signext_88 = sumpipe2_5;
  assign add_signext_89 = sumpipe2_6;
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum3_3 = add_temp_44[34:0];

  assign add_signext_90 = sumpipe2_7;
  assign add_signext_91 = sumpipe2_8;
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum3_4 = add_temp_45[34:0];

  assign add_signext_92 = sumpipe2_9;
  assign add_signext_93 = sumpipe2_10;
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum3_5 = add_temp_46[34:0];

  assign add_signext_94 = sumpipe2_11;
  assign add_signext_95 = sumpipe2_12;
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum3_6 = add_temp_47[34:0];

  assign add_signext_96 = sumpipe2_13;
  assign add_signext_97 = sumpipe2_14;
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum3_7 = add_temp_48[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process60
      if (reset == 1'b1) begin
        sumpipe3_1 <= 0;
        sumpipe3_2 <= 0;
        sumpipe3_3 <= 0;
        sumpipe3_4 <= 0;
        sumpipe3_5 <= 0;
        sumpipe3_6 <= 0;
        sumpipe3_7 <= 0;
        sumpipe3_8 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe3_1 <= sum3_1;
          sumpipe3_2 <= sum3_2;
          sumpipe3_3 <= sum3_3;
          sumpipe3_4 <= sum3_4;
          sumpipe3_5 <= sum3_5;
          sumpipe3_6 <= sum3_6;
          sumpipe3_7 <= sum3_7;
          sumpipe3_8 <= sumpipe2_15;
        end
      end
    end // temp_process60

  assign add_signext_98 = sumpipe3_1;
  assign add_signext_99 = sumpipe3_2;
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum4_1 = add_temp_49[34:0];

  assign add_signext_100 = sumpipe3_3;
  assign add_signext_101 = sumpipe3_4;
  assign add_temp_50 = add_signext_100 + add_signext_101;
  assign sum4_2 = add_temp_50[34:0];

  assign add_signext_102 = sumpipe3_5;
  assign add_signext_103 = sumpipe3_6;
  assign add_temp_51 = add_signext_102 + add_signext_103;
  assign sum4_3 = add_temp_51[34:0];

  assign add_signext_104 = sumpipe3_7;
  assign add_signext_105 = $signed({{4{sumpipe3_8[30]}}, sumpipe3_8});
  assign add_temp_52 = add_signext_104 + add_signext_105;
  assign sum4_4 = add_temp_52[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process61
      if (reset == 1'b1) begin
        sumpipe4_1 <= 0;
        sumpipe4_2 <= 0;
        sumpipe4_3 <= 0;
        sumpipe4_4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe4_1 <= sum4_1;
          sumpipe4_2 <= sum4_2;
          sumpipe4_3 <= sum4_3;
          sumpipe4_4 <= sum4_4;
        end
      end
    end // temp_process61

  assign add_signext_106 = sumpipe4_1;
  assign add_signext_107 = sumpipe4_2;
  assign add_temp_53 = add_signext_106 + add_signext_107;
  assign sum5_1 = add_temp_53[34:0];

  assign add_signext_108 = sumpipe4_3;
  assign add_signext_109 = sumpipe4_4;
  assign add_temp_54 = add_signext_108 + add_signext_109;
  assign sum5_2 = add_temp_54[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process62
      if (reset == 1'b1) begin
        sumpipe5_1 <= 0;
        sumpipe5_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe5_1 <= sum5_1;
          sumpipe5_2 <= sum5_2;
        end
      end
    end // temp_process62

  assign add_signext_110 = sumpipe5_1;
  assign add_signext_111 = sumpipe5_2;
  assign add_temp_55 = add_signext_110 + add_signext_111;
  assign sum6_1 = add_temp_55[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process63
      if (reset == 1'b1) begin
        sumpipe6_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe6_1 <= sum6_1;
        end
      end
    end // temp_process63

  assign sum_final = sumpipe6_1;

  assign output_typeconvert = (sum_final[31:0] + {sum_final[16], {15{~sum_final[16]}}})>>>16;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;

  // filter_out_valid: output sample valid, aligned with output_register.
  // Pipeline latency = 65 clk_enable events (64-tap + under_pipe +
  // product_pipe + output_register); delay clk_enable by the same depth.
  reg [64:0] ce_delay;
  always @(posedge clk or posedge reset) begin
    if (reset == 1'b1) begin
      ce_delay <= 0;
    end
    else if (clk_enable == 1'b1) begin
      ce_delay <= {ce_delay[63:0], 1'b1};
    end
  end
  assign filter_out_valid = clk_enable & ce_delay[64];
endmodule  // rcos_filter
