// -------------------------------------------------------------
//
// Module: anti_imaging_filter_10
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-08-27 11:44:35
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: hdlsrc/anti_imaging_filter_10
// AddPipelineRegisters: on
// Name: anti_imaging_filter_10
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 26
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// Input             : s16,15 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s16,15 -> [-1 1)
//   Product         : s31,30 -> [-1 1)
//   Accumulator     : s35,30 -> [-16 16)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------
// Multipliers           : 26



`timescale 1 ns / 1 ns

module anti_imaging_filter_10
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                filter_out_valid
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En15
  output  filter_out_valid;

////////////////////////////////////////////////////////////////
//Module Architecture: anti_imaging_filter_10
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000001000000001; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b0000010010100101; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b0000100101100000; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b0001000001110111; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b0001101000101011; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b0010011001110100; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b0011010011101111; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b0100010011011011; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b0101010100100010; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b0110010001111001; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b0111000110000010; //sfix16_En15
  parameter signed [15:0] coeff12 = 16'b0111101100000000; //sfix16_En15
  parameter signed [15:0] coeff13 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeff14 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeff15 = 16'b0111101100000000; //sfix16_En15
  parameter signed [15:0] coeff16 = 16'b0111000110000010; //sfix16_En15
  parameter signed [15:0] coeff17 = 16'b0110010001111001; //sfix16_En15
  parameter signed [15:0] coeff18 = 16'b0101010100100010; //sfix16_En15
  parameter signed [15:0] coeff19 = 16'b0100010011011011; //sfix16_En15
  parameter signed [15:0] coeff20 = 16'b0011010011101111; //sfix16_En15
  parameter signed [15:0] coeff21 = 16'b0010011001110100; //sfix16_En15
  parameter signed [15:0] coeff22 = 16'b0001101000101011; //sfix16_En15
  parameter signed [15:0] coeff23 = 16'b0001000001110111; //sfix16_En15
  parameter signed [15:0] coeff24 = 16'b0000100101100000; //sfix16_En15
  parameter signed [15:0] coeff25 = 16'b0000010010100101; //sfix16_En15
  parameter signed [15:0] coeff26 = 16'b0000001000000001; //sfix16_En15

  // Signals
  reg  signed [15:0] delay_pipeline [0:25] ; // sfix16_En15
  wire signed [30:0] product26; // sfix31_En30
  reg  signed [15:0] delay_pipeline_25_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff26_pipe; // sfix16_En15
  reg  signed [31:0] product26_pipe; // sfix32_En30
  wire signed [30:0] product25; // sfix31_En30
  reg  signed [15:0] delay_pipeline_24_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff25_pipe; // sfix16_En15
  reg  signed [31:0] product25_pipe; // sfix32_En30
  wire signed [30:0] product24; // sfix31_En30
  reg  signed [15:0] delay_pipeline_23_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff24_pipe; // sfix16_En15
  reg  signed [31:0] product24_pipe; // sfix32_En30
  wire signed [30:0] product23; // sfix31_En30
  reg  signed [15:0] delay_pipeline_22_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff23_pipe; // sfix16_En15
  reg  signed [31:0] product23_pipe; // sfix32_En30
  wire signed [30:0] product22; // sfix31_En30
  reg  signed [15:0] delay_pipeline_21_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff22_pipe; // sfix16_En15
  reg  signed [31:0] product22_pipe; // sfix32_En30
  wire signed [30:0] product21; // sfix31_En30
  reg  signed [15:0] delay_pipeline_20_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff21_pipe; // sfix16_En15
  reg  signed [31:0] product21_pipe; // sfix32_En30
  wire signed [30:0] product20; // sfix31_En30
  reg  signed [15:0] delay_pipeline_19_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff20_pipe; // sfix16_En15
  reg  signed [31:0] product20_pipe; // sfix32_En30
  wire signed [30:0] product19; // sfix31_En30
  reg  signed [15:0] delay_pipeline_18_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff19_pipe; // sfix16_En15
  reg  signed [31:0] product19_pipe; // sfix32_En30
  wire signed [30:0] product18; // sfix31_En30
  reg  signed [15:0] delay_pipeline_17_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff18_pipe; // sfix16_En15
  reg  signed [31:0] product18_pipe; // sfix32_En30
  wire signed [30:0] product17; // sfix31_En30
  reg  signed [15:0] delay_pipeline_16_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff17_pipe; // sfix16_En15
  reg  signed [31:0] product17_pipe; // sfix32_En30
  wire signed [30:0] product16; // sfix31_En30
  reg  signed [15:0] delay_pipeline_15_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff16_pipe; // sfix16_En15
  reg  signed [31:0] product16_pipe; // sfix32_En30
  wire signed [30:0] product15; // sfix31_En30
  reg  signed [15:0] delay_pipeline_14_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff15_pipe; // sfix16_En15
  reg  signed [31:0] product15_pipe; // sfix32_En30
  wire signed [30:0] product14; // sfix31_En30
  reg  signed [15:0] delay_pipeline_13_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff14_pipe; // sfix16_En15
  reg  signed [31:0] product14_pipe; // sfix32_En30
  wire signed [30:0] product13; // sfix31_En30
  reg  signed [15:0] delay_pipeline_12_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff13_pipe; // sfix16_En15
  reg  signed [31:0] product13_pipe; // sfix32_En30
  wire signed [30:0] product12; // sfix31_En30
  reg  signed [15:0] delay_pipeline_11_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff12_pipe; // sfix16_En15
  reg  signed [31:0] product12_pipe; // sfix32_En30
  wire signed [30:0] product11; // sfix31_En30
  reg  signed [15:0] delay_pipeline_10_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff11_pipe; // sfix16_En15
  reg  signed [31:0] product11_pipe; // sfix32_En30
  wire signed [30:0] product10; // sfix31_En30
  reg  signed [15:0] delay_pipeline_9_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff10_pipe; // sfix16_En15
  reg  signed [31:0] product10_pipe; // sfix32_En30
  wire signed [30:0] product9; // sfix31_En30
  reg  signed [15:0] delay_pipeline_8_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff9_pipe; // sfix16_En15
  reg  signed [31:0] product9_pipe; // sfix32_En30
  wire signed [30:0] product8; // sfix31_En30
  reg  signed [15:0] delay_pipeline_7_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff8_pipe; // sfix16_En15
  reg  signed [31:0] product8_pipe; // sfix32_En30
  wire signed [30:0] product7; // sfix31_En30
  reg  signed [15:0] delay_pipeline_6_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff7_pipe; // sfix16_En15
  reg  signed [31:0] product7_pipe; // sfix32_En30
  wire signed [30:0] product6; // sfix31_En30
  reg  signed [15:0] delay_pipeline_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff6_pipe; // sfix16_En15
  reg  signed [31:0] product6_pipe; // sfix32_En30
  wire signed [30:0] product5; // sfix31_En30
  reg  signed [15:0] delay_pipeline_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff5_pipe; // sfix16_En15
  reg  signed [31:0] product5_pipe; // sfix32_En30
  wire signed [30:0] product4; // sfix31_En30
  reg  signed [15:0] delay_pipeline_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff4_pipe; // sfix16_En15
  reg  signed [31:0] product4_pipe; // sfix32_En30
  wire signed [30:0] product3; // sfix31_En30
  reg  signed [15:0] delay_pipeline_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff3_pipe; // sfix16_En15
  reg  signed [31:0] product3_pipe; // sfix32_En30
  wire signed [30:0] product2; // sfix31_En30
  reg  signed [15:0] delay_pipeline_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff2_pipe; // sfix16_En15
  reg  signed [31:0] product2_pipe; // sfix32_En30
  wire signed [30:0] product1; // sfix31_En30
  reg  signed [15:0] delay_pipeline_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff1_pipe; // sfix16_En15
  reg  signed [31:0] product1_pipe; // sfix32_En30
  wire signed [34:0] sum_final; // sfix35_En30
  wire signed [34:0] sum1_1; // sfix35_En30
  wire signed [30:0] add_signext; // sfix31_En30
  wire signed [30:0] add_signext_1; // sfix31_En30
  wire signed [31:0] add_temp; // sfix32_En30
  reg  signed [34:0] sumpipe1_1; // sfix35_En30
  wire signed [34:0] sum1_2; // sfix35_En30
  wire signed [30:0] add_signext_2; // sfix31_En30
  wire signed [30:0] add_signext_3; // sfix31_En30
  wire signed [31:0] add_temp_1; // sfix32_En30
  reg  signed [34:0] sumpipe1_2; // sfix35_En30
  wire signed [34:0] sum1_3; // sfix35_En30
  wire signed [30:0] add_signext_4; // sfix31_En30
  wire signed [30:0] add_signext_5; // sfix31_En30
  wire signed [31:0] add_temp_2; // sfix32_En30
  reg  signed [34:0] sumpipe1_3; // sfix35_En30
  wire signed [34:0] sum1_4; // sfix35_En30
  wire signed [30:0] add_signext_6; // sfix31_En30
  wire signed [30:0] add_signext_7; // sfix31_En30
  wire signed [31:0] add_temp_3; // sfix32_En30
  reg  signed [34:0] sumpipe1_4; // sfix35_En30
  wire signed [34:0] sum1_5; // sfix35_En30
  wire signed [30:0] add_signext_8; // sfix31_En30
  wire signed [30:0] add_signext_9; // sfix31_En30
  wire signed [31:0] add_temp_4; // sfix32_En30
  reg  signed [34:0] sumpipe1_5; // sfix35_En30
  wire signed [34:0] sum1_6; // sfix35_En30
  wire signed [30:0] add_signext_10; // sfix31_En30
  wire signed [30:0] add_signext_11; // sfix31_En30
  wire signed [31:0] add_temp_5; // sfix32_En30
  reg  signed [34:0] sumpipe1_6; // sfix35_En30
  wire signed [34:0] sum1_7; // sfix35_En30
  wire signed [30:0] add_signext_12; // sfix31_En30
  wire signed [30:0] add_signext_13; // sfix31_En30
  wire signed [31:0] add_temp_6; // sfix32_En30
  reg  signed [34:0] sumpipe1_7; // sfix35_En30
  wire signed [34:0] sum1_8; // sfix35_En30
  wire signed [30:0] add_signext_14; // sfix31_En30
  wire signed [30:0] add_signext_15; // sfix31_En30
  wire signed [31:0] add_temp_7; // sfix32_En30
  reg  signed [34:0] sumpipe1_8; // sfix35_En30
  wire signed [34:0] sum1_9; // sfix35_En30
  wire signed [30:0] add_signext_16; // sfix31_En30
  wire signed [30:0] add_signext_17; // sfix31_En30
  wire signed [31:0] add_temp_8; // sfix32_En30
  reg  signed [34:0] sumpipe1_9; // sfix35_En30
  wire signed [34:0] sum1_10; // sfix35_En30
  wire signed [30:0] add_signext_18; // sfix31_En30
  wire signed [30:0] add_signext_19; // sfix31_En30
  wire signed [31:0] add_temp_9; // sfix32_En30
  reg  signed [34:0] sumpipe1_10; // sfix35_En30
  wire signed [34:0] sum1_11; // sfix35_En30
  wire signed [30:0] add_signext_20; // sfix31_En30
  wire signed [30:0] add_signext_21; // sfix31_En30
  wire signed [31:0] add_temp_10; // sfix32_En30
  reg  signed [34:0] sumpipe1_11; // sfix35_En30
  wire signed [34:0] sum1_12; // sfix35_En30
  wire signed [30:0] add_signext_22; // sfix31_En30
  wire signed [30:0] add_signext_23; // sfix31_En30
  wire signed [31:0] add_temp_11; // sfix32_En30
  reg  signed [34:0] sumpipe1_12; // sfix35_En30
  wire signed [34:0] sum1_13; // sfix35_En30
  wire signed [30:0] add_signext_24; // sfix31_En30
  wire signed [30:0] add_signext_25; // sfix31_En30
  wire signed [31:0] add_temp_12; // sfix32_En30
  reg  signed [34:0] sumpipe1_13; // sfix35_En30
  wire signed [34:0] sum2_1; // sfix35_En30
  wire signed [34:0] add_signext_26; // sfix35_En30
  wire signed [34:0] add_signext_27; // sfix35_En30
  wire signed [35:0] add_temp_13; // sfix36_En30
  reg  signed [34:0] sumpipe2_1; // sfix35_En30
  wire signed [34:0] sum2_2; // sfix35_En30
  wire signed [34:0] add_signext_28; // sfix35_En30
  wire signed [34:0] add_signext_29; // sfix35_En30
  wire signed [35:0] add_temp_14; // sfix36_En30
  reg  signed [34:0] sumpipe2_2; // sfix35_En30
  wire signed [34:0] sum2_3; // sfix35_En30
  wire signed [34:0] add_signext_30; // sfix35_En30
  wire signed [34:0] add_signext_31; // sfix35_En30
  wire signed [35:0] add_temp_15; // sfix36_En30
  reg  signed [34:0] sumpipe2_3; // sfix35_En30
  wire signed [34:0] sum2_4; // sfix35_En30
  wire signed [34:0] add_signext_32; // sfix35_En30
  wire signed [34:0] add_signext_33; // sfix35_En30
  wire signed [35:0] add_temp_16; // sfix36_En30
  reg  signed [34:0] sumpipe2_4; // sfix35_En30
  wire signed [34:0] sum2_5; // sfix35_En30
  wire signed [34:0] add_signext_34; // sfix35_En30
  wire signed [34:0] add_signext_35; // sfix35_En30
  wire signed [35:0] add_temp_17; // sfix36_En30
  reg  signed [34:0] sumpipe2_5; // sfix35_En30
  wire signed [34:0] sum2_6; // sfix35_En30
  wire signed [34:0] add_signext_36; // sfix35_En30
  wire signed [34:0] add_signext_37; // sfix35_En30
  wire signed [35:0] add_temp_18; // sfix36_En30
  reg  signed [34:0] sumpipe2_6; // sfix35_En30
  reg  signed [34:0] sumpipe2_7; // sfix35_En30
  wire signed [34:0] sum3_1; // sfix35_En30
  wire signed [34:0] add_signext_38; // sfix35_En30
  wire signed [34:0] add_signext_39; // sfix35_En30
  wire signed [35:0] add_temp_19; // sfix36_En30
  reg  signed [34:0] sumpipe3_1; // sfix35_En30
  wire signed [34:0] sum3_2; // sfix35_En30
  wire signed [34:0] add_signext_40; // sfix35_En30
  wire signed [34:0] add_signext_41; // sfix35_En30
  wire signed [35:0] add_temp_20; // sfix36_En30
  reg  signed [34:0] sumpipe3_2; // sfix35_En30
  wire signed [34:0] sum3_3; // sfix35_En30
  wire signed [34:0] add_signext_42; // sfix35_En30
  wire signed [34:0] add_signext_43; // sfix35_En30
  wire signed [35:0] add_temp_21; // sfix36_En30
  reg  signed [34:0] sumpipe3_3; // sfix35_En30
  reg  signed [34:0] sumpipe3_4; // sfix35_En30
  wire signed [34:0] sum4_1; // sfix35_En30
  wire signed [34:0] add_signext_44; // sfix35_En30
  wire signed [34:0] add_signext_45; // sfix35_En30
  wire signed [35:0] add_temp_22; // sfix36_En30
  reg  signed [34:0] sumpipe4_1; // sfix35_En30
  wire signed [34:0] sum4_2; // sfix35_En30
  wire signed [34:0] add_signext_46; // sfix35_En30
  wire signed [34:0] add_signext_47; // sfix35_En30
  wire signed [35:0] add_temp_23; // sfix36_En30
  reg  signed [34:0] sumpipe4_2; // sfix35_En30
  wire signed [34:0] sum5_1; // sfix35_En30
  wire signed [34:0] add_signext_48; // sfix35_En30
  wire signed [34:0] add_signext_49; // sfix35_En30
  wire signed [35:0] add_temp_24; // sfix36_En30
  reg  signed [34:0] sumpipe5_1; // sfix35_En30
  wire signed [15:0] output_typeconvert; // sfix16_En15
  reg  signed [15:0] output_register; // sfix16_En15

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
        end
      end
    end // Delay_Pipeline_process


  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        delay_pipeline_25_under_pipe <= 0;
        coeff26_pipe <= 0;
        product26_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_25_under_pipe <= delay_pipeline[25];
          coeff26_pipe <= coeff26;

          product26_pipe <= delay_pipeline_25_under_pipe * coeff26_pipe;

        end
      end
    end // temp_process1

  assign product26 = product26_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        delay_pipeline_24_under_pipe <= 0;
        coeff25_pipe <= 0;
        product25_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_24_under_pipe <= delay_pipeline[24];
          coeff25_pipe <= coeff25;

          product25_pipe <= delay_pipeline_24_under_pipe * coeff25_pipe;

        end
      end
    end // temp_process2

  assign product25 = product25_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        delay_pipeline_23_under_pipe <= 0;
        coeff24_pipe <= 0;
        product24_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_23_under_pipe <= delay_pipeline[23];
          coeff24_pipe <= coeff24;

          product24_pipe <= delay_pipeline_23_under_pipe * coeff24_pipe;

        end
      end
    end // temp_process3

  assign product24 = product24_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        delay_pipeline_22_under_pipe <= 0;
        coeff23_pipe <= 0;
        product23_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_22_under_pipe <= delay_pipeline[22];
          coeff23_pipe <= coeff23;

          product23_pipe <= delay_pipeline_22_under_pipe * coeff23_pipe;

        end
      end
    end // temp_process4

  assign product23 = product23_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        delay_pipeline_21_under_pipe <= 0;
        coeff22_pipe <= 0;
        product22_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_21_under_pipe <= delay_pipeline[21];
          coeff22_pipe <= coeff22;

          product22_pipe <= delay_pipeline_21_under_pipe * coeff22_pipe;

        end
      end
    end // temp_process5

  assign product22 = product22_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process6
      if (reset == 1'b1) begin
        delay_pipeline_20_under_pipe <= 0;
        coeff21_pipe <= 0;
        product21_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_20_under_pipe <= delay_pipeline[20];
          coeff21_pipe <= coeff21;

          product21_pipe <= delay_pipeline_20_under_pipe * coeff21_pipe;

        end
      end
    end // temp_process6

  assign product21 = product21_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process7
      if (reset == 1'b1) begin
        delay_pipeline_19_under_pipe <= 0;
        coeff20_pipe <= 0;
        product20_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_19_under_pipe <= delay_pipeline[19];
          coeff20_pipe <= coeff20;

          product20_pipe <= delay_pipeline_19_under_pipe * coeff20_pipe;

        end
      end
    end // temp_process7

  assign product20 = product20_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process8
      if (reset == 1'b1) begin
        delay_pipeline_18_under_pipe <= 0;
        coeff19_pipe <= 0;
        product19_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_18_under_pipe <= delay_pipeline[18];
          coeff19_pipe <= coeff19;

          product19_pipe <= delay_pipeline_18_under_pipe * coeff19_pipe;

        end
      end
    end // temp_process8

  assign product19 = product19_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process9
      if (reset == 1'b1) begin
        delay_pipeline_17_under_pipe <= 0;
        coeff18_pipe <= 0;
        product18_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_17_under_pipe <= delay_pipeline[17];
          coeff18_pipe <= coeff18;

          product18_pipe <= delay_pipeline_17_under_pipe * coeff18_pipe;

        end
      end
    end // temp_process9

  assign product18 = product18_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process10
      if (reset == 1'b1) begin
        delay_pipeline_16_under_pipe <= 0;
        coeff17_pipe <= 0;
        product17_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_16_under_pipe <= delay_pipeline[16];
          coeff17_pipe <= coeff17;

          product17_pipe <= delay_pipeline_16_under_pipe * coeff17_pipe;

        end
      end
    end // temp_process10

  assign product17 = product17_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process11
      if (reset == 1'b1) begin
        delay_pipeline_15_under_pipe <= 0;
        coeff16_pipe <= 0;
        product16_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_15_under_pipe <= delay_pipeline[15];
          coeff16_pipe <= coeff16;

          product16_pipe <= delay_pipeline_15_under_pipe * coeff16_pipe;

        end
      end
    end // temp_process11

  assign product16 = product16_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process12
      if (reset == 1'b1) begin
        delay_pipeline_14_under_pipe <= 0;
        coeff15_pipe <= 0;
        product15_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_14_under_pipe <= delay_pipeline[14];
          coeff15_pipe <= coeff15;

          product15_pipe <= delay_pipeline_14_under_pipe * coeff15_pipe;

        end
      end
    end // temp_process12

  assign product15 = product15_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process13
      if (reset == 1'b1) begin
        delay_pipeline_13_under_pipe <= 0;
        coeff14_pipe <= 0;
        product14_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_13_under_pipe <= delay_pipeline[13];
          coeff14_pipe <= coeff14;

          product14_pipe <= delay_pipeline_13_under_pipe * coeff14_pipe;

        end
      end
    end // temp_process13

  assign product14 = product14_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process14
      if (reset == 1'b1) begin
        delay_pipeline_12_under_pipe <= 0;
        coeff13_pipe <= 0;
        product13_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_12_under_pipe <= delay_pipeline[12];
          coeff13_pipe <= coeff13;

          product13_pipe <= delay_pipeline_12_under_pipe * coeff13_pipe;

        end
      end
    end // temp_process14

  assign product13 = product13_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process15
      if (reset == 1'b1) begin
        delay_pipeline_11_under_pipe <= 0;
        coeff12_pipe <= 0;
        product12_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_11_under_pipe <= delay_pipeline[11];
          coeff12_pipe <= coeff12;

          product12_pipe <= delay_pipeline_11_under_pipe * coeff12_pipe;

        end
      end
    end // temp_process15

  assign product12 = product12_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process16
      if (reset == 1'b1) begin
        delay_pipeline_10_under_pipe <= 0;
        coeff11_pipe <= 0;
        product11_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_10_under_pipe <= delay_pipeline[10];
          coeff11_pipe <= coeff11;

          product11_pipe <= delay_pipeline_10_under_pipe * coeff11_pipe;

        end
      end
    end // temp_process16

  assign product11 = product11_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process17
      if (reset == 1'b1) begin
        delay_pipeline_9_under_pipe <= 0;
        coeff10_pipe <= 0;
        product10_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_9_under_pipe <= delay_pipeline[9];
          coeff10_pipe <= coeff10;

          product10_pipe <= delay_pipeline_9_under_pipe * coeff10_pipe;

        end
      end
    end // temp_process17

  assign product10 = product10_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process18
      if (reset == 1'b1) begin
        delay_pipeline_8_under_pipe <= 0;
        coeff9_pipe <= 0;
        product9_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_8_under_pipe <= delay_pipeline[8];
          coeff9_pipe <= coeff9;

          product9_pipe <= delay_pipeline_8_under_pipe * coeff9_pipe;

        end
      end
    end // temp_process18

  assign product9 = product9_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process19
      if (reset == 1'b1) begin
        delay_pipeline_7_under_pipe <= 0;
        coeff8_pipe <= 0;
        product8_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_7_under_pipe <= delay_pipeline[7];
          coeff8_pipe <= coeff8;

          product8_pipe <= delay_pipeline_7_under_pipe * coeff8_pipe;

        end
      end
    end // temp_process19

  assign product8 = product8_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process20
      if (reset == 1'b1) begin
        delay_pipeline_6_under_pipe <= 0;
        coeff7_pipe <= 0;
        product7_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_6_under_pipe <= delay_pipeline[6];
          coeff7_pipe <= coeff7;

          product7_pipe <= delay_pipeline_6_under_pipe * coeff7_pipe;

        end
      end
    end // temp_process20

  assign product7 = product7_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process21
      if (reset == 1'b1) begin
        delay_pipeline_5_under_pipe <= 0;
        coeff6_pipe <= 0;
        product6_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_5_under_pipe <= delay_pipeline[5];
          coeff6_pipe <= coeff6;

          product6_pipe <= delay_pipeline_5_under_pipe * coeff6_pipe;

        end
      end
    end // temp_process21

  assign product6 = product6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process22
      if (reset == 1'b1) begin
        delay_pipeline_4_under_pipe <= 0;
        coeff5_pipe <= 0;
        product5_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_4_under_pipe <= delay_pipeline[4];
          coeff5_pipe <= coeff5;

          product5_pipe <= delay_pipeline_4_under_pipe * coeff5_pipe;

        end
      end
    end // temp_process22

  assign product5 = product5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process23
      if (reset == 1'b1) begin
        delay_pipeline_3_under_pipe <= 0;
        coeff4_pipe <= 0;
        product4_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_3_under_pipe <= delay_pipeline[3];
          coeff4_pipe <= coeff4;

          product4_pipe <= delay_pipeline_3_under_pipe * coeff4_pipe;

        end
      end
    end // temp_process23

  assign product4 = product4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process24
      if (reset == 1'b1) begin
        delay_pipeline_2_under_pipe <= 0;
        coeff3_pipe <= 0;
        product3_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_2_under_pipe <= delay_pipeline[2];
          coeff3_pipe <= coeff3;

          product3_pipe <= delay_pipeline_2_under_pipe * coeff3_pipe;

        end
      end
    end // temp_process24

  assign product3 = product3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process25
      if (reset == 1'b1) begin
        delay_pipeline_1_under_pipe <= 0;
        coeff2_pipe <= 0;
        product2_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_1_under_pipe <= delay_pipeline[1];
          coeff2_pipe <= coeff2;

          product2_pipe <= delay_pipeline_1_under_pipe * coeff2_pipe;

        end
      end
    end // temp_process25

  assign product2 = product2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process26
      if (reset == 1'b1) begin
        delay_pipeline_0_under_pipe <= 0;
        coeff1_pipe <= 0;
        product1_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_0_under_pipe <= delay_pipeline[0];
          coeff1_pipe <= coeff1;

          product1_pipe <= delay_pipeline_0_under_pipe * coeff1_pipe;

        end
      end
    end // temp_process26

  assign product1 = product1_pipe[30:0];

  assign add_signext = product26;
  assign add_signext_1 = product25;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{3{add_temp[31]}}, add_temp});

  assign add_signext_2 = product24;
  assign add_signext_3 = product23;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{3{add_temp_1[31]}}, add_temp_1});

  assign add_signext_4 = product22;
  assign add_signext_5 = product21;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{3{add_temp_2[31]}}, add_temp_2});

  assign add_signext_6 = product20;
  assign add_signext_7 = product19;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum1_4 = $signed({{3{add_temp_3[31]}}, add_temp_3});

  assign add_signext_8 = product18;
  assign add_signext_9 = product17;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum1_5 = $signed({{3{add_temp_4[31]}}, add_temp_4});

  assign add_signext_10 = product16;
  assign add_signext_11 = product15;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum1_6 = $signed({{3{add_temp_5[31]}}, add_temp_5});

  assign add_signext_12 = product14;
  assign add_signext_13 = product13;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum1_7 = $signed({{3{add_temp_6[31]}}, add_temp_6});

  assign add_signext_14 = product12;
  assign add_signext_15 = product11;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum1_8 = $signed({{3{add_temp_7[31]}}, add_temp_7});

  assign add_signext_16 = product10;
  assign add_signext_17 = product9;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum1_9 = $signed({{3{add_temp_8[31]}}, add_temp_8});

  assign add_signext_18 = product8;
  assign add_signext_19 = product7;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum1_10 = $signed({{3{add_temp_9[31]}}, add_temp_9});

  assign add_signext_20 = product6;
  assign add_signext_21 = product5;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum1_11 = $signed({{3{add_temp_10[31]}}, add_temp_10});

  assign add_signext_22 = product4;
  assign add_signext_23 = product3;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum1_12 = $signed({{3{add_temp_11[31]}}, add_temp_11});

  assign add_signext_24 = product2;
  assign add_signext_25 = product1;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum1_13 = $signed({{3{add_temp_12[31]}}, add_temp_12});

  always @ (posedge clk or posedge reset)
    begin: temp_process27
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
        sumpipe1_3 <= 0;
        sumpipe1_4 <= 0;
        sumpipe1_5 <= 0;
        sumpipe1_6 <= 0;
        sumpipe1_7 <= 0;
        sumpipe1_8 <= 0;
        sumpipe1_9 <= 0;
        sumpipe1_10 <= 0;
        sumpipe1_11 <= 0;
        sumpipe1_12 <= 0;
        sumpipe1_13 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
          sumpipe1_3 <= sum1_3;
          sumpipe1_4 <= sum1_4;
          sumpipe1_5 <= sum1_5;
          sumpipe1_6 <= sum1_6;
          sumpipe1_7 <= sum1_7;
          sumpipe1_8 <= sum1_8;
          sumpipe1_9 <= sum1_9;
          sumpipe1_10 <= sum1_10;
          sumpipe1_11 <= sum1_11;
          sumpipe1_12 <= sum1_12;
          sumpipe1_13 <= sum1_13;
        end
      end
    end // temp_process27

  assign add_signext_26 = sumpipe1_1;
  assign add_signext_27 = sumpipe1_2;
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum2_1 = add_temp_13[34:0];

  assign add_signext_28 = sumpipe1_3;
  assign add_signext_29 = sumpipe1_4;
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum2_2 = add_temp_14[34:0];

  assign add_signext_30 = sumpipe1_5;
  assign add_signext_31 = sumpipe1_6;
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum2_3 = add_temp_15[34:0];

  assign add_signext_32 = sumpipe1_7;
  assign add_signext_33 = sumpipe1_8;
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum2_4 = add_temp_16[34:0];

  assign add_signext_34 = sumpipe1_9;
  assign add_signext_35 = sumpipe1_10;
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum2_5 = add_temp_17[34:0];

  assign add_signext_36 = sumpipe1_11;
  assign add_signext_37 = sumpipe1_12;
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum2_6 = add_temp_18[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process28
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
        sumpipe2_2 <= 0;
        sumpipe2_3 <= 0;
        sumpipe2_4 <= 0;
        sumpipe2_5 <= 0;
        sumpipe2_6 <= 0;
        sumpipe2_7 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
          sumpipe2_2 <= sum2_2;
          sumpipe2_3 <= sum2_3;
          sumpipe2_4 <= sum2_4;
          sumpipe2_5 <= sum2_5;
          sumpipe2_6 <= sum2_6;
          sumpipe2_7 <= sumpipe1_13;
        end
      end
    end // temp_process28

  assign add_signext_38 = sumpipe2_1;
  assign add_signext_39 = sumpipe2_2;
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum3_1 = add_temp_19[34:0];

  assign add_signext_40 = sumpipe2_3;
  assign add_signext_41 = sumpipe2_4;
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum3_2 = add_temp_20[34:0];

  assign add_signext_42 = sumpipe2_5;
  assign add_signext_43 = sumpipe2_6;
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum3_3 = add_temp_21[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process29
      if (reset == 1'b1) begin
        sumpipe3_1 <= 0;
        sumpipe3_2 <= 0;
        sumpipe3_3 <= 0;
        sumpipe3_4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe3_1 <= sum3_1;
          sumpipe3_2 <= sum3_2;
          sumpipe3_3 <= sum3_3;
          sumpipe3_4 <= sumpipe2_7;
        end
      end
    end // temp_process29

  assign add_signext_44 = sumpipe3_1;
  assign add_signext_45 = sumpipe3_2;
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum4_1 = add_temp_22[34:0];

  assign add_signext_46 = sumpipe3_3;
  assign add_signext_47 = sumpipe3_4;
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum4_2 = add_temp_23[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process30
      if (reset == 1'b1) begin
        sumpipe4_1 <= 0;
        sumpipe4_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe4_1 <= sum4_1;
          sumpipe4_2 <= sum4_2;
        end
      end
    end // temp_process30

  assign add_signext_48 = sumpipe4_1;
  assign add_signext_49 = sumpipe4_2;
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum5_1 = add_temp_24[34:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process31
      if (reset == 1'b1) begin
        sumpipe5_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe5_1 <= sum5_1;
        end
      end
    end // temp_process31

  assign sum_final = sumpipe5_1;

  assign output_typeconvert = (sum_final[30:0] + {sum_final[15], {14{~sum_final[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;

  // filter_out_valid: output sample valid, aligned with output_register.
  // Pipeline latency = 27 clk_enable events (26-tap + under_pipe +
  // product_pipe + output_register); delay clk_enable by the same depth.
  reg [26:0] ce_delay;
  always @(posedge clk or posedge reset) begin
    if (reset == 1'b1) begin
      ce_delay <= 0;
    end
    else if (clk_enable == 1'b1) begin
      ce_delay <= {ce_delay[25:0], 1'b1};
    end
  end
  assign filter_out_valid = ce_delay[26];
endmodule  // anti_imaging_filter_10
