// -------------------------------------------------------------
//
// Module: d_8
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-09-18 23:47:06
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: hdlsrc/d_8
// AddPipelineRegisters: on
// Name: d_8
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp noise 
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure   : Direct-Form FIR Polyphase Decimator
// Decimation Factor  : 8
// Polyphase Length   : 7
// Filter Length      : 49
// Stable             : Yes
// Linear Phase       : Yes (Type 1)
//
// Arithmetic         : fixed
// Numerator          : s16,15 -> [-1 1)
// Input              : s16,15 -> [-1 1)
// Filter Internals   : Specify Precision
//   Output           : s16,10 -> [-32 32)
//   Product          : s31,30 -> [-1 1)
//   Accumulator      : s36,30 -> [-32 32)
//   Round Mode       : convergent
//   Overflow Mode    : wrap
// -------------------------------------------------------------
// Multipliers           : 49



`timescale 1 ns / 1 ns

module d_8
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En10
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: d_8
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b0000000010000001; //sfix16_En15
  parameter signed [15:0] coeffphase1_2 = 16'b0001000111111111; //sfix16_En15
  parameter signed [15:0] coeffphase1_3 = 16'b0101000110001010; //sfix16_En15
  parameter signed [15:0] coeffphase1_4 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeffphase1_5 = 16'b0101000110001010; //sfix16_En15
  parameter signed [15:0] coeffphase1_6 = 16'b0001000111111111; //sfix16_En15
  parameter signed [15:0] coeffphase1_7 = 16'b0000000010000001; //sfix16_En15
  parameter signed [15:0] coeffphase2_1 = 16'b0000000011101100; //sfix16_En15
  parameter signed [15:0] coeffphase2_2 = 16'b0001011101101101; //sfix16_En15
  parameter signed [15:0] coeffphase2_3 = 16'b0101101011001110; //sfix16_En15
  parameter signed [15:0] coeffphase2_4 = 16'b0111111100011111; //sfix16_En15
  parameter signed [15:0] coeffphase2_5 = 16'b0100100000010000; //sfix16_En15
  parameter signed [15:0] coeffphase2_6 = 16'b0000110101110010; //sfix16_En15
  parameter signed [15:0] coeffphase2_7 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase3_1 = 16'b0000000110110110; //sfix16_En15
  parameter signed [15:0] coeffphase3_2 = 16'b0001110110111111; //sfix16_En15
  parameter signed [15:0] coeffphase3_3 = 16'b0110001110010110; //sfix16_En15
  parameter signed [15:0] coeffphase3_4 = 16'b0111110010000101; //sfix16_En15
  parameter signed [15:0] coeffphase3_5 = 16'b0011111010100100; //sfix16_En15
  parameter signed [15:0] coeffphase3_6 = 16'b0000100110111101; //sfix16_En15
  parameter signed [15:0] coeffphase3_7 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase4_1 = 16'b0000001011100011; //sfix16_En15
  parameter signed [15:0] coeffphase4_2 = 16'b0010010011101101; //sfix16_En15
  parameter signed [15:0] coeffphase4_3 = 16'b0110101110011001; //sfix16_En15
  parameter signed [15:0] coeffphase4_4 = 16'b0111100001001010; //sfix16_En15
  parameter signed [15:0] coeffphase4_5 = 16'b0011010110000100; //sfix16_En15
  parameter signed [15:0] coeffphase4_6 = 16'b0000011011001101; //sfix16_En15
  parameter signed [15:0] coeffphase4_7 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase5_1 = 16'b0000010010001101; //sfix16_En15
  parameter signed [15:0] coeffphase5_2 = 16'b0010110011100100; //sfix16_En15
  parameter signed [15:0] coeffphase5_3 = 16'b0111001010010101; //sfix16_En15
  parameter signed [15:0] coeffphase5_4 = 16'b0111001010010101; //sfix16_En15
  parameter signed [15:0] coeffphase5_5 = 16'b0010110011100100; //sfix16_En15
  parameter signed [15:0] coeffphase5_6 = 16'b0000010010001101; //sfix16_En15
  parameter signed [15:0] coeffphase5_7 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase6_1 = 16'b0000011011001101; //sfix16_En15
  parameter signed [15:0] coeffphase6_2 = 16'b0011010110000100; //sfix16_En15
  parameter signed [15:0] coeffphase6_3 = 16'b0111100001001010; //sfix16_En15
  parameter signed [15:0] coeffphase6_4 = 16'b0110101110011001; //sfix16_En15
  parameter signed [15:0] coeffphase6_5 = 16'b0010010011101101; //sfix16_En15
  parameter signed [15:0] coeffphase6_6 = 16'b0000001011100011; //sfix16_En15
  parameter signed [15:0] coeffphase6_7 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase7_1 = 16'b0000100110111101; //sfix16_En15
  parameter signed [15:0] coeffphase7_2 = 16'b0011111010100100; //sfix16_En15
  parameter signed [15:0] coeffphase7_3 = 16'b0111110010000101; //sfix16_En15
  parameter signed [15:0] coeffphase7_4 = 16'b0110001110010110; //sfix16_En15
  parameter signed [15:0] coeffphase7_5 = 16'b0001110110111111; //sfix16_En15
  parameter signed [15:0] coeffphase7_6 = 16'b0000000110110110; //sfix16_En15
  parameter signed [15:0] coeffphase7_7 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase8_1 = 16'b0000110101110010; //sfix16_En15
  parameter signed [15:0] coeffphase8_2 = 16'b0100100000010000; //sfix16_En15
  parameter signed [15:0] coeffphase8_3 = 16'b0111111100011111; //sfix16_En15
  parameter signed [15:0] coeffphase8_4 = 16'b0101101011001110; //sfix16_En15
  parameter signed [15:0] coeffphase8_5 = 16'b0001011101101101; //sfix16_En15
  parameter signed [15:0] coeffphase8_6 = 16'b0000000011101100; //sfix16_En15
  parameter signed [15:0] coeffphase8_7 = 16'b0000000000000000; //sfix16_En15

  // Signals
  reg  [7:0] ring_count; // ufix8
  wire phase_0; // boolean
  wire phase_1; // boolean
  wire phase_2; // boolean
  wire phase_3; // boolean
  wire phase_4; // boolean
  wire phase_5; // boolean
  wire phase_6; // boolean
  wire phase_7; // boolean
  reg  ce_out_reg; // boolean
  reg  signed [15:0] input_register; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase0 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase1 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase2 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase3 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase4 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase5 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase6 [0:5] ; // sfix16_En15
  reg  signed [15:0] input_pipeline_phase7 [0:5] ; // sfix16_En15
  wire signed [16:0] tapsum1; // sfix17_En15
  wire signed [15:0] add_signext; // sfix16_En15
  wire signed [15:0] add_signext_1; // sfix16_En15
  wire signed [16:0] tapsum2; // sfix17_En15
  wire signed [15:0] add_signext_2; // sfix16_En15
  wire signed [15:0] add_signext_3; // sfix16_En15
  wire signed [16:0] tapsum3; // sfix17_En15
  wire signed [15:0] add_signext_4; // sfix16_En15
  wire signed [15:0] add_signext_5; // sfix16_En15
  wire signed [30:0] product_phase0_1; // sfix31_En30
  reg  signed [15:0] input_register_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase0_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase0_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase0_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase0_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase0_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase0_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase0_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase0_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase0_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase0_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase0_7; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase0_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase1_7_pipe; // sfix16_En15
  reg  signed [31:0] product_phase0_7_pipe; // sfix32_En30
  wire signed [30:0] product_phase1_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase1_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase2_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase1_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase1_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase1_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase2_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase1_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase1_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase1_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase2_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase1_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase1_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase1_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase2_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase1_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase1_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase1_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase2_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase1_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase1_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase1_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase2_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase1_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase2_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase2_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase3_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase2_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase2_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase2_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase3_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase2_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase2_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase2_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase3_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase2_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase2_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase2_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase3_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase2_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase2_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase2_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase3_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase2_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase2_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase2_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase3_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase2_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase3_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase3_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase4_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase3_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase3_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase3_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase4_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase3_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase3_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase3_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase4_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase3_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase3_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase3_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase4_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase3_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase3_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase3_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase4_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase3_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase3_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase3_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase4_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase3_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase4_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase4_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase5_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase4_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase4_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase4_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase5_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase4_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase4_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase4_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase5_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase4_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase4_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase4_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase5_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase4_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase4_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase4_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase5_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase4_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase4_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase4_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase5_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase4_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase5_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase5_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase6_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase5_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase5_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase5_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase6_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase5_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase5_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase5_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase6_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase5_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase5_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase5_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase6_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase5_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase5_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase5_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase6_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase5_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase5_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase5_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase6_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase5_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase6_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase6_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase7_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase6_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase6_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase6_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase7_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase6_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase6_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase6_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase7_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase6_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase6_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase6_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase7_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase6_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase6_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase6_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase7_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase6_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase6_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase6_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase7_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase6_6_pipe; // sfix32_En30
  wire signed [30:0] product_phase7_1; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase7_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase8_1_pipe; // sfix16_En15
  reg  signed [31:0] product_phase7_1_pipe; // sfix32_En30
  wire signed [30:0] product_phase7_2; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase7_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase8_2_pipe; // sfix16_En15
  reg  signed [31:0] product_phase7_2_pipe; // sfix32_En30
  wire signed [30:0] product_phase7_3; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase7_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase8_3_pipe; // sfix16_En15
  reg  signed [31:0] product_phase7_3_pipe; // sfix32_En30
  wire signed [30:0] product_phase7_4; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase7_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase8_4_pipe; // sfix16_En15
  reg  signed [31:0] product_phase7_4_pipe; // sfix32_En30
  wire signed [30:0] product_phase7_5; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase7_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase8_5_pipe; // sfix16_En15
  reg  signed [31:0] product_phase7_5_pipe; // sfix32_En30
  wire signed [30:0] product_phase7_6; // sfix31_En30
  reg  signed [15:0] input_pipeline_phase7_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeffphase8_6_pipe; // sfix16_En15
  reg  signed [31:0] product_phase7_6_pipe; // sfix32_En30
  reg  signed [30:0] product_pipeline_phase0_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase0_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase0_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase0_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase0_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase0_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase0_7; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase1_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase1_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase1_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase1_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase1_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase1_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase2_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase2_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase2_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase2_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase2_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase2_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase3_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase3_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase3_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase3_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase3_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase3_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase4_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase4_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase4_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase4_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase4_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase4_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase5_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase5_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase5_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase5_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase5_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase5_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase6_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase6_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase6_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase6_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase6_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase6_6; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase7_1; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase7_2; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase7_3; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase7_4; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase7_5; // sfix31_En30
  reg  signed [30:0] product_pipeline_phase7_6; // sfix31_En30
  wire signed [35:0] sumvector1 [0:24] ; // sfix36_En30
  wire signed [30:0] add_signext_6; // sfix31_En30
  wire signed [30:0] add_signext_7; // sfix31_En30
  wire signed [31:0] add_temp; // sfix32_En30
  wire signed [30:0] add_signext_8; // sfix31_En30
  wire signed [30:0] add_signext_9; // sfix31_En30
  wire signed [31:0] add_temp_1; // sfix32_En30
  wire signed [30:0] add_signext_10; // sfix31_En30
  wire signed [30:0] add_signext_11; // sfix31_En30
  wire signed [31:0] add_temp_2; // sfix32_En30
  wire signed [30:0] add_signext_12; // sfix31_En30
  wire signed [30:0] add_signext_13; // sfix31_En30
  wire signed [31:0] add_temp_3; // sfix32_En30
  wire signed [30:0] add_signext_14; // sfix31_En30
  wire signed [30:0] add_signext_15; // sfix31_En30
  wire signed [31:0] add_temp_4; // sfix32_En30
  wire signed [30:0] add_signext_16; // sfix31_En30
  wire signed [30:0] add_signext_17; // sfix31_En30
  wire signed [31:0] add_temp_5; // sfix32_En30
  wire signed [30:0] add_signext_18; // sfix31_En30
  wire signed [30:0] add_signext_19; // sfix31_En30
  wire signed [31:0] add_temp_6; // sfix32_En30
  wire signed [30:0] add_signext_20; // sfix31_En30
  wire signed [30:0] add_signext_21; // sfix31_En30
  wire signed [31:0] add_temp_7; // sfix32_En30
  wire signed [30:0] add_signext_22; // sfix31_En30
  wire signed [30:0] add_signext_23; // sfix31_En30
  wire signed [31:0] add_temp_8; // sfix32_En30
  wire signed [30:0] add_signext_24; // sfix31_En30
  wire signed [30:0] add_signext_25; // sfix31_En30
  wire signed [31:0] add_temp_9; // sfix32_En30
  wire signed [30:0] add_signext_26; // sfix31_En30
  wire signed [30:0] add_signext_27; // sfix31_En30
  wire signed [31:0] add_temp_10; // sfix32_En30
  wire signed [30:0] add_signext_28; // sfix31_En30
  wire signed [30:0] add_signext_29; // sfix31_En30
  wire signed [31:0] add_temp_11; // sfix32_En30
  wire signed [30:0] add_signext_30; // sfix31_En30
  wire signed [30:0] add_signext_31; // sfix31_En30
  wire signed [31:0] add_temp_12; // sfix32_En30
  wire signed [30:0] add_signext_32; // sfix31_En30
  wire signed [30:0] add_signext_33; // sfix31_En30
  wire signed [31:0] add_temp_13; // sfix32_En30
  wire signed [30:0] add_signext_34; // sfix31_En30
  wire signed [30:0] add_signext_35; // sfix31_En30
  wire signed [31:0] add_temp_14; // sfix32_En30
  wire signed [30:0] add_signext_36; // sfix31_En30
  wire signed [30:0] add_signext_37; // sfix31_En30
  wire signed [31:0] add_temp_15; // sfix32_En30
  wire signed [30:0] add_signext_38; // sfix31_En30
  wire signed [30:0] add_signext_39; // sfix31_En30
  wire signed [31:0] add_temp_16; // sfix32_En30
  wire signed [30:0] add_signext_40; // sfix31_En30
  wire signed [30:0] add_signext_41; // sfix31_En30
  wire signed [31:0] add_temp_17; // sfix32_En30
  wire signed [30:0] add_signext_42; // sfix31_En30
  wire signed [30:0] add_signext_43; // sfix31_En30
  wire signed [31:0] add_temp_18; // sfix32_En30
  wire signed [30:0] add_signext_44; // sfix31_En30
  wire signed [30:0] add_signext_45; // sfix31_En30
  wire signed [31:0] add_temp_19; // sfix32_En30
  wire signed [30:0] add_signext_46; // sfix31_En30
  wire signed [30:0] add_signext_47; // sfix31_En30
  wire signed [31:0] add_temp_20; // sfix32_En30
  wire signed [30:0] add_signext_48; // sfix31_En30
  wire signed [30:0] add_signext_49; // sfix31_En30
  wire signed [31:0] add_temp_21; // sfix32_En30
  wire signed [30:0] add_signext_50; // sfix31_En30
  wire signed [30:0] add_signext_51; // sfix31_En30
  wire signed [31:0] add_temp_22; // sfix32_En30
  wire signed [30:0] add_signext_52; // sfix31_En30
  wire signed [30:0] add_signext_53; // sfix31_En30
  wire signed [31:0] add_temp_23; // sfix32_En30
  reg  signed [35:0] sumdelay_pipeline1 [0:24] ; // sfix36_En30
  wire signed [35:0] sumvector2 [0:12] ; // sfix36_En30
  wire signed [35:0] add_signext_54; // sfix36_En30
  wire signed [35:0] add_signext_55; // sfix36_En30
  wire signed [36:0] add_temp_24; // sfix37_En30
  wire signed [35:0] add_signext_56; // sfix36_En30
  wire signed [35:0] add_signext_57; // sfix36_En30
  wire signed [36:0] add_temp_25; // sfix37_En30
  wire signed [35:0] add_signext_58; // sfix36_En30
  wire signed [35:0] add_signext_59; // sfix36_En30
  wire signed [36:0] add_temp_26; // sfix37_En30
  wire signed [35:0] add_signext_60; // sfix36_En30
  wire signed [35:0] add_signext_61; // sfix36_En30
  wire signed [36:0] add_temp_27; // sfix37_En30
  wire signed [35:0] add_signext_62; // sfix36_En30
  wire signed [35:0] add_signext_63; // sfix36_En30
  wire signed [36:0] add_temp_28; // sfix37_En30
  wire signed [35:0] add_signext_64; // sfix36_En30
  wire signed [35:0] add_signext_65; // sfix36_En30
  wire signed [36:0] add_temp_29; // sfix37_En30
  wire signed [35:0] add_signext_66; // sfix36_En30
  wire signed [35:0] add_signext_67; // sfix36_En30
  wire signed [36:0] add_temp_30; // sfix37_En30
  wire signed [35:0] add_signext_68; // sfix36_En30
  wire signed [35:0] add_signext_69; // sfix36_En30
  wire signed [36:0] add_temp_31; // sfix37_En30
  wire signed [35:0] add_signext_70; // sfix36_En30
  wire signed [35:0] add_signext_71; // sfix36_En30
  wire signed [36:0] add_temp_32; // sfix37_En30
  wire signed [35:0] add_signext_72; // sfix36_En30
  wire signed [35:0] add_signext_73; // sfix36_En30
  wire signed [36:0] add_temp_33; // sfix37_En30
  wire signed [35:0] add_signext_74; // sfix36_En30
  wire signed [35:0] add_signext_75; // sfix36_En30
  wire signed [36:0] add_temp_34; // sfix37_En30
  wire signed [35:0] add_signext_76; // sfix36_En30
  wire signed [35:0] add_signext_77; // sfix36_En30
  wire signed [36:0] add_temp_35; // sfix37_En30
  reg  signed [35:0] sumdelay_pipeline2 [0:12] ; // sfix36_En30
  wire signed [35:0] sumvector3 [0:6] ; // sfix36_En30
  wire signed [35:0] add_signext_78; // sfix36_En30
  wire signed [35:0] add_signext_79; // sfix36_En30
  wire signed [36:0] add_temp_36; // sfix37_En30
  wire signed [35:0] add_signext_80; // sfix36_En30
  wire signed [35:0] add_signext_81; // sfix36_En30
  wire signed [36:0] add_temp_37; // sfix37_En30
  wire signed [35:0] add_signext_82; // sfix36_En30
  wire signed [35:0] add_signext_83; // sfix36_En30
  wire signed [36:0] add_temp_38; // sfix37_En30
  wire signed [35:0] add_signext_84; // sfix36_En30
  wire signed [35:0] add_signext_85; // sfix36_En30
  wire signed [36:0] add_temp_39; // sfix37_En30
  wire signed [35:0] add_signext_86; // sfix36_En30
  wire signed [35:0] add_signext_87; // sfix36_En30
  wire signed [36:0] add_temp_40; // sfix37_En30
  wire signed [35:0] add_signext_88; // sfix36_En30
  wire signed [35:0] add_signext_89; // sfix36_En30
  wire signed [36:0] add_temp_41; // sfix37_En30
  reg  signed [35:0] sumdelay_pipeline3 [0:6] ; // sfix36_En30
  wire signed [35:0] sumvector4 [0:3] ; // sfix36_En30
  wire signed [35:0] add_signext_90; // sfix36_En30
  wire signed [35:0] add_signext_91; // sfix36_En30
  wire signed [36:0] add_temp_42; // sfix37_En30
  wire signed [35:0] add_signext_92; // sfix36_En30
  wire signed [35:0] add_signext_93; // sfix36_En30
  wire signed [36:0] add_temp_43; // sfix37_En30
  wire signed [35:0] add_signext_94; // sfix36_En30
  wire signed [35:0] add_signext_95; // sfix36_En30
  wire signed [36:0] add_temp_44; // sfix37_En30
  reg  signed [35:0] sumdelay_pipeline4 [0:3] ; // sfix36_En30
  wire signed [35:0] sumvector5 [0:1] ; // sfix36_En30
  wire signed [35:0] add_signext_96; // sfix36_En30
  wire signed [35:0] add_signext_97; // sfix36_En30
  wire signed [36:0] add_temp_45; // sfix37_En30
  wire signed [35:0] add_signext_98; // sfix36_En30
  wire signed [35:0] add_signext_99; // sfix36_En30
  wire signed [36:0] add_temp_46; // sfix37_En30
  reg  signed [35:0] sumdelay_pipeline5 [0:1] ; // sfix36_En30
  wire signed [35:0] sum6; // sfix36_En30
  wire signed [35:0] add_signext_100; // sfix36_En30
  wire signed [35:0] add_signext_101; // sfix36_En30
  wire signed [36:0] add_temp_47; // sfix37_En30
  wire signed [15:0] output_typeconvert; // sfix16_En10
  reg  ce_delayline1; // boolean
  reg  ce_delayline2; // boolean
  reg  ce_delayline3; // boolean
  reg  ce_delayline4; // boolean
  reg  ce_delayline5; // boolean
  reg  ce_delayline6; // boolean
  reg  ce_delayline7; // boolean
  reg  ce_delayline8; // boolean
  reg  ce_delayline9; // boolean
  reg  ce_delayline10; // boolean
  reg  ce_delayline11; // boolean
  reg  ce_delayline12; // boolean
  reg  ce_delayline13; // boolean
  reg  ce_delayline14; // boolean
  reg  ce_delayline15; // boolean
  reg  ce_delayline16; // boolean
  reg  ce_delayline17; // boolean
  reg  ce_delayline18; // boolean
  reg  ce_delayline19; // boolean
  reg  ce_delayline20; // boolean
  reg  ce_delayline21; // boolean
  reg  ce_delayline22; // boolean
  reg  ce_delayline23; // boolean
  reg  ce_delayline24; // boolean
  reg  ce_delayline25; // boolean
  reg  ce_delayline26; // boolean
  reg  ce_delayline27; // boolean
  reg  ce_delayline28; // boolean
  reg  ce_delayline29; // boolean
  reg  ce_delayline30; // boolean
  reg  ce_delayline31; // boolean
  reg  ce_delayline32; // boolean
  reg  ce_delayline33; // boolean
  reg  ce_delayline34; // boolean
  reg  ce_delayline35; // boolean
  reg  ce_delayline36; // boolean
  reg  ce_delayline37; // boolean
  reg  ce_delayline38; // boolean
  reg  ce_delayline39; // boolean
  reg  ce_delayline40; // boolean
  reg  ce_delayline41; // boolean
  reg  ce_delayline42; // boolean
  reg  ce_delayline43; // boolean
  reg  ce_delayline44; // boolean
  reg  ce_delayline45; // boolean
  reg  ce_delayline46; // boolean
  reg  ce_delayline47; // boolean
  reg  ce_delayline48; // boolean
  reg  ce_delayline49; // boolean
  reg  ce_delayline50; // boolean
  reg  ce_delayline51; // boolean
  reg  ce_delayline52; // boolean
  reg  ce_delayline53; // boolean
  reg  ce_delayline54; // boolean
  reg  ce_delayline55; // boolean
  reg  ce_delayline56; // boolean
  reg  ce_delayline57; // boolean
  reg  ce_delayline58; // boolean
  reg  ce_delayline59; // boolean
  reg  ce_delayline60; // boolean
  reg  ce_delayline61; // boolean
  reg  ce_delayline62; // boolean
  reg  ce_delayline63; // boolean
  reg  ce_delayline64; // boolean
  reg  ce_delayline65; // boolean
  reg  ce_delayline66; // boolean
  wire ce_gated; // boolean
  reg  signed [15:0] output_register; // sfix16_En10

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        ring_count <= 1;
      end
      else begin
                if (clk_enable == 1'b1) begin
        ring_count <= {ring_count[0], ring_count[7 : 1]};
              end
            end
    end // ce_output

  assign  phase_0 = ring_count[0]  && clk_enable;

  assign  phase_1 = ring_count[1]  && clk_enable;

  assign  phase_2 = ring_count[2]  && clk_enable;

  assign  phase_3 = ring_count[3]  && clk_enable;

  assign  phase_4 = ring_count[4]  && clk_enable;

  assign  phase_5 = ring_count[5]  && clk_enable;

  assign  phase_6 = ring_count[6]  && clk_enable;

  assign  phase_7 = ring_count[7]  && clk_enable;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_7;
      end
    end // ce_output_register

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase0_process
      if (reset == 1'b1) begin
        input_pipeline_phase0[0] <= 0;
        input_pipeline_phase0[1] <= 0;
        input_pipeline_phase0[2] <= 0;
        input_pipeline_phase0[3] <= 0;
        input_pipeline_phase0[4] <= 0;
        input_pipeline_phase0[5] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0[0] <= input_register;
          input_pipeline_phase0[1] <= input_pipeline_phase0[0];
          input_pipeline_phase0[2] <= input_pipeline_phase0[1];
          input_pipeline_phase0[3] <= input_pipeline_phase0[2];
          input_pipeline_phase0[4] <= input_pipeline_phase0[3];
          input_pipeline_phase0[5] <= input_pipeline_phase0[4];
        end
      end
    end // Delay_Pipeline_Phase0_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase1_process
      if (reset == 1'b1) begin
        input_pipeline_phase1[0] <= 0;
        input_pipeline_phase1[1] <= 0;
        input_pipeline_phase1[2] <= 0;
        input_pipeline_phase1[3] <= 0;
        input_pipeline_phase1[4] <= 0;
        input_pipeline_phase1[5] <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          input_pipeline_phase1[0] <= input_register;
          input_pipeline_phase1[1] <= input_pipeline_phase1[0];
          input_pipeline_phase1[2] <= input_pipeline_phase1[1];
          input_pipeline_phase1[3] <= input_pipeline_phase1[2];
          input_pipeline_phase1[4] <= input_pipeline_phase1[3];
          input_pipeline_phase1[5] <= input_pipeline_phase1[4];
        end
      end
    end // Delay_Pipeline_Phase1_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase2_process
      if (reset == 1'b1) begin
        input_pipeline_phase2[0] <= 0;
        input_pipeline_phase2[1] <= 0;
        input_pipeline_phase2[2] <= 0;
        input_pipeline_phase2[3] <= 0;
        input_pipeline_phase2[4] <= 0;
        input_pipeline_phase2[5] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          input_pipeline_phase2[0] <= input_register;
          input_pipeline_phase2[1] <= input_pipeline_phase2[0];
          input_pipeline_phase2[2] <= input_pipeline_phase2[1];
          input_pipeline_phase2[3] <= input_pipeline_phase2[2];
          input_pipeline_phase2[4] <= input_pipeline_phase2[3];
          input_pipeline_phase2[5] <= input_pipeline_phase2[4];
        end
      end
    end // Delay_Pipeline_Phase2_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase3_process
      if (reset == 1'b1) begin
        input_pipeline_phase3[0] <= 0;
        input_pipeline_phase3[1] <= 0;
        input_pipeline_phase3[2] <= 0;
        input_pipeline_phase3[3] <= 0;
        input_pipeline_phase3[4] <= 0;
        input_pipeline_phase3[5] <= 0;
      end
      else begin
        if (phase_2 == 1'b1) begin
          input_pipeline_phase3[0] <= input_register;
          input_pipeline_phase3[1] <= input_pipeline_phase3[0];
          input_pipeline_phase3[2] <= input_pipeline_phase3[1];
          input_pipeline_phase3[3] <= input_pipeline_phase3[2];
          input_pipeline_phase3[4] <= input_pipeline_phase3[3];
          input_pipeline_phase3[5] <= input_pipeline_phase3[4];
        end
      end
    end // Delay_Pipeline_Phase3_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase4_process
      if (reset == 1'b1) begin
        input_pipeline_phase4[0] <= 0;
        input_pipeline_phase4[1] <= 0;
        input_pipeline_phase4[2] <= 0;
        input_pipeline_phase4[3] <= 0;
        input_pipeline_phase4[4] <= 0;
        input_pipeline_phase4[5] <= 0;
      end
      else begin
        if (phase_3 == 1'b1) begin
          input_pipeline_phase4[0] <= input_register;
          input_pipeline_phase4[1] <= input_pipeline_phase4[0];
          input_pipeline_phase4[2] <= input_pipeline_phase4[1];
          input_pipeline_phase4[3] <= input_pipeline_phase4[2];
          input_pipeline_phase4[4] <= input_pipeline_phase4[3];
          input_pipeline_phase4[5] <= input_pipeline_phase4[4];
        end
      end
    end // Delay_Pipeline_Phase4_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase5_process
      if (reset == 1'b1) begin
        input_pipeline_phase5[0] <= 0;
        input_pipeline_phase5[1] <= 0;
        input_pipeline_phase5[2] <= 0;
        input_pipeline_phase5[3] <= 0;
        input_pipeline_phase5[4] <= 0;
        input_pipeline_phase5[5] <= 0;
      end
      else begin
        if (phase_4 == 1'b1) begin
          input_pipeline_phase5[0] <= input_register;
          input_pipeline_phase5[1] <= input_pipeline_phase5[0];
          input_pipeline_phase5[2] <= input_pipeline_phase5[1];
          input_pipeline_phase5[3] <= input_pipeline_phase5[2];
          input_pipeline_phase5[4] <= input_pipeline_phase5[3];
          input_pipeline_phase5[5] <= input_pipeline_phase5[4];
        end
      end
    end // Delay_Pipeline_Phase5_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase6_process
      if (reset == 1'b1) begin
        input_pipeline_phase6[0] <= 0;
        input_pipeline_phase6[1] <= 0;
        input_pipeline_phase6[2] <= 0;
        input_pipeline_phase6[3] <= 0;
        input_pipeline_phase6[4] <= 0;
        input_pipeline_phase6[5] <= 0;
      end
      else begin
        if (phase_5 == 1'b1) begin
          input_pipeline_phase6[0] <= input_register;
          input_pipeline_phase6[1] <= input_pipeline_phase6[0];
          input_pipeline_phase6[2] <= input_pipeline_phase6[1];
          input_pipeline_phase6[3] <= input_pipeline_phase6[2];
          input_pipeline_phase6[4] <= input_pipeline_phase6[3];
          input_pipeline_phase6[5] <= input_pipeline_phase6[4];
        end
      end
    end // Delay_Pipeline_Phase6_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase7_process
      if (reset == 1'b1) begin
        input_pipeline_phase7[0] <= 0;
        input_pipeline_phase7[1] <= 0;
        input_pipeline_phase7[2] <= 0;
        input_pipeline_phase7[3] <= 0;
        input_pipeline_phase7[4] <= 0;
        input_pipeline_phase7[5] <= 0;
      end
      else begin
        if (phase_6 == 1'b1) begin
          input_pipeline_phase7[0] <= input_register;
          input_pipeline_phase7[1] <= input_pipeline_phase7[0];
          input_pipeline_phase7[2] <= input_pipeline_phase7[1];
          input_pipeline_phase7[3] <= input_pipeline_phase7[2];
          input_pipeline_phase7[4] <= input_pipeline_phase7[3];
          input_pipeline_phase7[5] <= input_pipeline_phase7[4];
        end
      end
    end // Delay_Pipeline_Phase7_process


  assign add_signext = input_register;
  assign add_signext_1 = input_pipeline_phase0[5];
  assign tapsum1 = add_signext + add_signext_1;

  assign add_signext_2 = input_pipeline_phase0[0];
  assign add_signext_3 = input_pipeline_phase0[4];
  assign tapsum2 = add_signext_2 + add_signext_3;

  assign add_signext_4 = input_pipeline_phase0[1];
  assign add_signext_5 = input_pipeline_phase0[3];
  assign tapsum3 = add_signext_4 + add_signext_5;

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        input_register_pipe <= 0;
        coeffphase1_1_pipe <= 0;
        product_phase0_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_register_pipe <= input_register;
          coeffphase1_1_pipe <= coeffphase1_1;

          product_phase0_1_pipe <= input_register_pipe * coeffphase1_1_pipe;

        end
      end
    end // temp_process1

  assign product_phase0_1 = product_phase0_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        input_pipeline_phase0_0_under_pipe <= 0;
        coeffphase1_2_pipe <= 0;
        product_phase0_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0_0_under_pipe <= input_pipeline_phase0[0];
          coeffphase1_2_pipe <= coeffphase1_2;

          product_phase0_2_pipe <= input_pipeline_phase0_0_under_pipe * coeffphase1_2_pipe;

        end
      end
    end // temp_process2

  assign product_phase0_2 = product_phase0_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        input_pipeline_phase0_1_under_pipe <= 0;
        coeffphase1_3_pipe <= 0;
        product_phase0_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0_1_under_pipe <= input_pipeline_phase0[1];
          coeffphase1_3_pipe <= coeffphase1_3;

          product_phase0_3_pipe <= input_pipeline_phase0_1_under_pipe * coeffphase1_3_pipe;

        end
      end
    end // temp_process3

  assign product_phase0_3 = product_phase0_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        input_pipeline_phase0_2_under_pipe <= 0;
        coeffphase1_4_pipe <= 0;
        product_phase0_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0_2_under_pipe <= input_pipeline_phase0[2];
          coeffphase1_4_pipe <= coeffphase1_4;

          product_phase0_4_pipe <= input_pipeline_phase0_2_under_pipe * coeffphase1_4_pipe;

        end
      end
    end // temp_process4

  assign product_phase0_4 = product_phase0_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        input_pipeline_phase0_3_under_pipe <= 0;
        coeffphase1_5_pipe <= 0;
        product_phase0_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0_3_under_pipe <= input_pipeline_phase0[3];
          coeffphase1_5_pipe <= coeffphase1_5;

          product_phase0_5_pipe <= input_pipeline_phase0_3_under_pipe * coeffphase1_5_pipe;

        end
      end
    end // temp_process5

  assign product_phase0_5 = product_phase0_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process6
      if (reset == 1'b1) begin
        input_pipeline_phase0_4_under_pipe <= 0;
        coeffphase1_6_pipe <= 0;
        product_phase0_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0_4_under_pipe <= input_pipeline_phase0[4];
          coeffphase1_6_pipe <= coeffphase1_6;

          product_phase0_6_pipe <= input_pipeline_phase0_4_under_pipe * coeffphase1_6_pipe;

        end
      end
    end // temp_process6

  assign product_phase0_6 = product_phase0_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process7
      if (reset == 1'b1) begin
        input_pipeline_phase0_5_under_pipe <= 0;
        coeffphase1_7_pipe <= 0;
        product_phase0_7_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase0_5_under_pipe <= input_pipeline_phase0[5];
          coeffphase1_7_pipe <= coeffphase1_7;

          product_phase0_7_pipe <= input_pipeline_phase0_5_under_pipe * coeffphase1_7_pipe;

        end
      end
    end // temp_process7

  assign product_phase0_7 = product_phase0_7_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process8
      if (reset == 1'b1) begin
        input_pipeline_phase1_0_under_pipe <= 0;
        coeffphase2_1_pipe <= 0;
        product_phase1_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase1_0_under_pipe <= input_pipeline_phase1[0];
          coeffphase2_1_pipe <= coeffphase2_1;

          product_phase1_1_pipe <= input_pipeline_phase1_0_under_pipe * coeffphase2_1_pipe;

        end
      end
    end // temp_process8

  assign product_phase1_1 = product_phase1_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process9
      if (reset == 1'b1) begin
        input_pipeline_phase1_1_under_pipe <= 0;
        coeffphase2_2_pipe <= 0;
        product_phase1_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase1_1_under_pipe <= input_pipeline_phase1[1];
          coeffphase2_2_pipe <= coeffphase2_2;

          product_phase1_2_pipe <= input_pipeline_phase1_1_under_pipe * coeffphase2_2_pipe;

        end
      end
    end // temp_process9

  assign product_phase1_2 = product_phase1_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process10
      if (reset == 1'b1) begin
        input_pipeline_phase1_2_under_pipe <= 0;
        coeffphase2_3_pipe <= 0;
        product_phase1_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase1_2_under_pipe <= input_pipeline_phase1[2];
          coeffphase2_3_pipe <= coeffphase2_3;

          product_phase1_3_pipe <= input_pipeline_phase1_2_under_pipe * coeffphase2_3_pipe;

        end
      end
    end // temp_process10

  assign product_phase1_3 = product_phase1_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process11
      if (reset == 1'b1) begin
        input_pipeline_phase1_3_under_pipe <= 0;
        coeffphase2_4_pipe <= 0;
        product_phase1_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase1_3_under_pipe <= input_pipeline_phase1[3];
          coeffphase2_4_pipe <= coeffphase2_4;

          product_phase1_4_pipe <= input_pipeline_phase1_3_under_pipe * coeffphase2_4_pipe;

        end
      end
    end // temp_process11

  assign product_phase1_4 = product_phase1_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process12
      if (reset == 1'b1) begin
        input_pipeline_phase1_4_under_pipe <= 0;
        coeffphase2_5_pipe <= 0;
        product_phase1_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase1_4_under_pipe <= input_pipeline_phase1[4];
          coeffphase2_5_pipe <= coeffphase2_5;

          product_phase1_5_pipe <= input_pipeline_phase1_4_under_pipe * coeffphase2_5_pipe;

        end
      end
    end // temp_process12

  assign product_phase1_5 = product_phase1_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process13
      if (reset == 1'b1) begin
        input_pipeline_phase1_5_under_pipe <= 0;
        coeffphase2_6_pipe <= 0;
        product_phase1_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase1_5_under_pipe <= input_pipeline_phase1[5];
          coeffphase2_6_pipe <= coeffphase2_6;

          product_phase1_6_pipe <= input_pipeline_phase1_5_under_pipe * coeffphase2_6_pipe;

        end
      end
    end // temp_process13

  assign product_phase1_6 = product_phase1_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process14
      if (reset == 1'b1) begin
        input_pipeline_phase2_0_under_pipe <= 0;
        coeffphase3_1_pipe <= 0;
        product_phase2_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase2_0_under_pipe <= input_pipeline_phase2[0];
          coeffphase3_1_pipe <= coeffphase3_1;

          product_phase2_1_pipe <= input_pipeline_phase2_0_under_pipe * coeffphase3_1_pipe;

        end
      end
    end // temp_process14

  assign product_phase2_1 = product_phase2_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process15
      if (reset == 1'b1) begin
        input_pipeline_phase2_1_under_pipe <= 0;
        coeffphase3_2_pipe <= 0;
        product_phase2_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase2_1_under_pipe <= input_pipeline_phase2[1];
          coeffphase3_2_pipe <= coeffphase3_2;

          product_phase2_2_pipe <= input_pipeline_phase2_1_under_pipe * coeffphase3_2_pipe;

        end
      end
    end // temp_process15

  assign product_phase2_2 = product_phase2_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process16
      if (reset == 1'b1) begin
        input_pipeline_phase2_2_under_pipe <= 0;
        coeffphase3_3_pipe <= 0;
        product_phase2_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase2_2_under_pipe <= input_pipeline_phase2[2];
          coeffphase3_3_pipe <= coeffphase3_3;

          product_phase2_3_pipe <= input_pipeline_phase2_2_under_pipe * coeffphase3_3_pipe;

        end
      end
    end // temp_process16

  assign product_phase2_3 = product_phase2_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process17
      if (reset == 1'b1) begin
        input_pipeline_phase2_3_under_pipe <= 0;
        coeffphase3_4_pipe <= 0;
        product_phase2_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase2_3_under_pipe <= input_pipeline_phase2[3];
          coeffphase3_4_pipe <= coeffphase3_4;

          product_phase2_4_pipe <= input_pipeline_phase2_3_under_pipe * coeffphase3_4_pipe;

        end
      end
    end // temp_process17

  assign product_phase2_4 = product_phase2_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process18
      if (reset == 1'b1) begin
        input_pipeline_phase2_4_under_pipe <= 0;
        coeffphase3_5_pipe <= 0;
        product_phase2_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase2_4_under_pipe <= input_pipeline_phase2[4];
          coeffphase3_5_pipe <= coeffphase3_5;

          product_phase2_5_pipe <= input_pipeline_phase2_4_under_pipe * coeffphase3_5_pipe;

        end
      end
    end // temp_process18

  assign product_phase2_5 = product_phase2_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process19
      if (reset == 1'b1) begin
        input_pipeline_phase2_5_under_pipe <= 0;
        coeffphase3_6_pipe <= 0;
        product_phase2_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase2_5_under_pipe <= input_pipeline_phase2[5];
          coeffphase3_6_pipe <= coeffphase3_6;

          product_phase2_6_pipe <= input_pipeline_phase2_5_under_pipe * coeffphase3_6_pipe;

        end
      end
    end // temp_process19

  assign product_phase2_6 = product_phase2_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process20
      if (reset == 1'b1) begin
        input_pipeline_phase3_0_under_pipe <= 0;
        coeffphase4_1_pipe <= 0;
        product_phase3_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase3_0_under_pipe <= input_pipeline_phase3[0];
          coeffphase4_1_pipe <= coeffphase4_1;

          product_phase3_1_pipe <= input_pipeline_phase3_0_under_pipe * coeffphase4_1_pipe;

        end
      end
    end // temp_process20

  assign product_phase3_1 = product_phase3_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process21
      if (reset == 1'b1) begin
        input_pipeline_phase3_1_under_pipe <= 0;
        coeffphase4_2_pipe <= 0;
        product_phase3_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase3_1_under_pipe <= input_pipeline_phase3[1];
          coeffphase4_2_pipe <= coeffphase4_2;

          product_phase3_2_pipe <= input_pipeline_phase3_1_under_pipe * coeffphase4_2_pipe;

        end
      end
    end // temp_process21

  assign product_phase3_2 = product_phase3_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process22
      if (reset == 1'b1) begin
        input_pipeline_phase3_2_under_pipe <= 0;
        coeffphase4_3_pipe <= 0;
        product_phase3_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase3_2_under_pipe <= input_pipeline_phase3[2];
          coeffphase4_3_pipe <= coeffphase4_3;

          product_phase3_3_pipe <= input_pipeline_phase3_2_under_pipe * coeffphase4_3_pipe;

        end
      end
    end // temp_process22

  assign product_phase3_3 = product_phase3_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process23
      if (reset == 1'b1) begin
        input_pipeline_phase3_3_under_pipe <= 0;
        coeffphase4_4_pipe <= 0;
        product_phase3_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase3_3_under_pipe <= input_pipeline_phase3[3];
          coeffphase4_4_pipe <= coeffphase4_4;

          product_phase3_4_pipe <= input_pipeline_phase3_3_under_pipe * coeffphase4_4_pipe;

        end
      end
    end // temp_process23

  assign product_phase3_4 = product_phase3_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process24
      if (reset == 1'b1) begin
        input_pipeline_phase3_4_under_pipe <= 0;
        coeffphase4_5_pipe <= 0;
        product_phase3_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase3_4_under_pipe <= input_pipeline_phase3[4];
          coeffphase4_5_pipe <= coeffphase4_5;

          product_phase3_5_pipe <= input_pipeline_phase3_4_under_pipe * coeffphase4_5_pipe;

        end
      end
    end // temp_process24

  assign product_phase3_5 = product_phase3_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process25
      if (reset == 1'b1) begin
        input_pipeline_phase3_5_under_pipe <= 0;
        coeffphase4_6_pipe <= 0;
        product_phase3_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase3_5_under_pipe <= input_pipeline_phase3[5];
          coeffphase4_6_pipe <= coeffphase4_6;

          product_phase3_6_pipe <= input_pipeline_phase3_5_under_pipe * coeffphase4_6_pipe;

        end
      end
    end // temp_process25

  assign product_phase3_6 = product_phase3_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process26
      if (reset == 1'b1) begin
        input_pipeline_phase4_0_under_pipe <= 0;
        coeffphase5_1_pipe <= 0;
        product_phase4_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase4_0_under_pipe <= input_pipeline_phase4[0];
          coeffphase5_1_pipe <= coeffphase5_1;

          product_phase4_1_pipe <= input_pipeline_phase4_0_under_pipe * coeffphase5_1_pipe;

        end
      end
    end // temp_process26

  assign product_phase4_1 = product_phase4_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process27
      if (reset == 1'b1) begin
        input_pipeline_phase4_1_under_pipe <= 0;
        coeffphase5_2_pipe <= 0;
        product_phase4_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase4_1_under_pipe <= input_pipeline_phase4[1];
          coeffphase5_2_pipe <= coeffphase5_2;

          product_phase4_2_pipe <= input_pipeline_phase4_1_under_pipe * coeffphase5_2_pipe;

        end
      end
    end // temp_process27

  assign product_phase4_2 = product_phase4_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process28
      if (reset == 1'b1) begin
        input_pipeline_phase4_2_under_pipe <= 0;
        coeffphase5_3_pipe <= 0;
        product_phase4_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase4_2_under_pipe <= input_pipeline_phase4[2];
          coeffphase5_3_pipe <= coeffphase5_3;

          product_phase4_3_pipe <= input_pipeline_phase4_2_under_pipe * coeffphase5_3_pipe;

        end
      end
    end // temp_process28

  assign product_phase4_3 = product_phase4_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process29
      if (reset == 1'b1) begin
        input_pipeline_phase4_3_under_pipe <= 0;
        coeffphase5_4_pipe <= 0;
        product_phase4_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase4_3_under_pipe <= input_pipeline_phase4[3];
          coeffphase5_4_pipe <= coeffphase5_4;

          product_phase4_4_pipe <= input_pipeline_phase4_3_under_pipe * coeffphase5_4_pipe;

        end
      end
    end // temp_process29

  assign product_phase4_4 = product_phase4_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process30
      if (reset == 1'b1) begin
        input_pipeline_phase4_4_under_pipe <= 0;
        coeffphase5_5_pipe <= 0;
        product_phase4_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase4_4_under_pipe <= input_pipeline_phase4[4];
          coeffphase5_5_pipe <= coeffphase5_5;

          product_phase4_5_pipe <= input_pipeline_phase4_4_under_pipe * coeffphase5_5_pipe;

        end
      end
    end // temp_process30

  assign product_phase4_5 = product_phase4_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process31
      if (reset == 1'b1) begin
        input_pipeline_phase4_5_under_pipe <= 0;
        coeffphase5_6_pipe <= 0;
        product_phase4_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase4_5_under_pipe <= input_pipeline_phase4[5];
          coeffphase5_6_pipe <= coeffphase5_6;

          product_phase4_6_pipe <= input_pipeline_phase4_5_under_pipe * coeffphase5_6_pipe;

        end
      end
    end // temp_process31

  assign product_phase4_6 = product_phase4_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process32
      if (reset == 1'b1) begin
        input_pipeline_phase5_0_under_pipe <= 0;
        coeffphase6_1_pipe <= 0;
        product_phase5_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase5_0_under_pipe <= input_pipeline_phase5[0];
          coeffphase6_1_pipe <= coeffphase6_1;

          product_phase5_1_pipe <= input_pipeline_phase5_0_under_pipe * coeffphase6_1_pipe;

        end
      end
    end // temp_process32

  assign product_phase5_1 = product_phase5_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process33
      if (reset == 1'b1) begin
        input_pipeline_phase5_1_under_pipe <= 0;
        coeffphase6_2_pipe <= 0;
        product_phase5_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase5_1_under_pipe <= input_pipeline_phase5[1];
          coeffphase6_2_pipe <= coeffphase6_2;

          product_phase5_2_pipe <= input_pipeline_phase5_1_under_pipe * coeffphase6_2_pipe;

        end
      end
    end // temp_process33

  assign product_phase5_2 = product_phase5_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process34
      if (reset == 1'b1) begin
        input_pipeline_phase5_2_under_pipe <= 0;
        coeffphase6_3_pipe <= 0;
        product_phase5_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase5_2_under_pipe <= input_pipeline_phase5[2];
          coeffphase6_3_pipe <= coeffphase6_3;

          product_phase5_3_pipe <= input_pipeline_phase5_2_under_pipe * coeffphase6_3_pipe;

        end
      end
    end // temp_process34

  assign product_phase5_3 = product_phase5_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process35
      if (reset == 1'b1) begin
        input_pipeline_phase5_3_under_pipe <= 0;
        coeffphase6_4_pipe <= 0;
        product_phase5_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase5_3_under_pipe <= input_pipeline_phase5[3];
          coeffphase6_4_pipe <= coeffphase6_4;

          product_phase5_4_pipe <= input_pipeline_phase5_3_under_pipe * coeffphase6_4_pipe;

        end
      end
    end // temp_process35

  assign product_phase5_4 = product_phase5_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process36
      if (reset == 1'b1) begin
        input_pipeline_phase5_4_under_pipe <= 0;
        coeffphase6_5_pipe <= 0;
        product_phase5_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase5_4_under_pipe <= input_pipeline_phase5[4];
          coeffphase6_5_pipe <= coeffphase6_5;

          product_phase5_5_pipe <= input_pipeline_phase5_4_under_pipe * coeffphase6_5_pipe;

        end
      end
    end // temp_process36

  assign product_phase5_5 = product_phase5_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process37
      if (reset == 1'b1) begin
        input_pipeline_phase5_5_under_pipe <= 0;
        coeffphase6_6_pipe <= 0;
        product_phase5_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase5_5_under_pipe <= input_pipeline_phase5[5];
          coeffphase6_6_pipe <= coeffphase6_6;

          product_phase5_6_pipe <= input_pipeline_phase5_5_under_pipe * coeffphase6_6_pipe;

        end
      end
    end // temp_process37

  assign product_phase5_6 = product_phase5_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process38
      if (reset == 1'b1) begin
        input_pipeline_phase6_0_under_pipe <= 0;
        coeffphase7_1_pipe <= 0;
        product_phase6_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase6_0_under_pipe <= input_pipeline_phase6[0];
          coeffphase7_1_pipe <= coeffphase7_1;

          product_phase6_1_pipe <= input_pipeline_phase6_0_under_pipe * coeffphase7_1_pipe;

        end
      end
    end // temp_process38

  assign product_phase6_1 = product_phase6_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process39
      if (reset == 1'b1) begin
        input_pipeline_phase6_1_under_pipe <= 0;
        coeffphase7_2_pipe <= 0;
        product_phase6_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase6_1_under_pipe <= input_pipeline_phase6[1];
          coeffphase7_2_pipe <= coeffphase7_2;

          product_phase6_2_pipe <= input_pipeline_phase6_1_under_pipe * coeffphase7_2_pipe;

        end
      end
    end // temp_process39

  assign product_phase6_2 = product_phase6_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process40
      if (reset == 1'b1) begin
        input_pipeline_phase6_2_under_pipe <= 0;
        coeffphase7_3_pipe <= 0;
        product_phase6_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase6_2_under_pipe <= input_pipeline_phase6[2];
          coeffphase7_3_pipe <= coeffphase7_3;

          product_phase6_3_pipe <= input_pipeline_phase6_2_under_pipe * coeffphase7_3_pipe;

        end
      end
    end // temp_process40

  assign product_phase6_3 = product_phase6_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process41
      if (reset == 1'b1) begin
        input_pipeline_phase6_3_under_pipe <= 0;
        coeffphase7_4_pipe <= 0;
        product_phase6_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase6_3_under_pipe <= input_pipeline_phase6[3];
          coeffphase7_4_pipe <= coeffphase7_4;

          product_phase6_4_pipe <= input_pipeline_phase6_3_under_pipe * coeffphase7_4_pipe;

        end
      end
    end // temp_process41

  assign product_phase6_4 = product_phase6_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process42
      if (reset == 1'b1) begin
        input_pipeline_phase6_4_under_pipe <= 0;
        coeffphase7_5_pipe <= 0;
        product_phase6_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase6_4_under_pipe <= input_pipeline_phase6[4];
          coeffphase7_5_pipe <= coeffphase7_5;

          product_phase6_5_pipe <= input_pipeline_phase6_4_under_pipe * coeffphase7_5_pipe;

        end
      end
    end // temp_process42

  assign product_phase6_5 = product_phase6_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process43
      if (reset == 1'b1) begin
        input_pipeline_phase6_5_under_pipe <= 0;
        coeffphase7_6_pipe <= 0;
        product_phase6_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase6_5_under_pipe <= input_pipeline_phase6[5];
          coeffphase7_6_pipe <= coeffphase7_6;

          product_phase6_6_pipe <= input_pipeline_phase6_5_under_pipe * coeffphase7_6_pipe;

        end
      end
    end // temp_process43

  assign product_phase6_6 = product_phase6_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process44
      if (reset == 1'b1) begin
        input_pipeline_phase7_0_under_pipe <= 0;
        coeffphase8_1_pipe <= 0;
        product_phase7_1_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7_0_under_pipe <= input_pipeline_phase7[0];
          coeffphase8_1_pipe <= coeffphase8_1;

          product_phase7_1_pipe <= input_pipeline_phase7_0_under_pipe * coeffphase8_1_pipe;

        end
      end
    end // temp_process44

  assign product_phase7_1 = product_phase7_1_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process45
      if (reset == 1'b1) begin
        input_pipeline_phase7_1_under_pipe <= 0;
        coeffphase8_2_pipe <= 0;
        product_phase7_2_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7_1_under_pipe <= input_pipeline_phase7[1];
          coeffphase8_2_pipe <= coeffphase8_2;

          product_phase7_2_pipe <= input_pipeline_phase7_1_under_pipe * coeffphase8_2_pipe;

        end
      end
    end // temp_process45

  assign product_phase7_2 = product_phase7_2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process46
      if (reset == 1'b1) begin
        input_pipeline_phase7_2_under_pipe <= 0;
        coeffphase8_3_pipe <= 0;
        product_phase7_3_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7_2_under_pipe <= input_pipeline_phase7[2];
          coeffphase8_3_pipe <= coeffphase8_3;

          product_phase7_3_pipe <= input_pipeline_phase7_2_under_pipe * coeffphase8_3_pipe;

        end
      end
    end // temp_process46

  assign product_phase7_3 = product_phase7_3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process47
      if (reset == 1'b1) begin
        input_pipeline_phase7_3_under_pipe <= 0;
        coeffphase8_4_pipe <= 0;
        product_phase7_4_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7_3_under_pipe <= input_pipeline_phase7[3];
          coeffphase8_4_pipe <= coeffphase8_4;

          product_phase7_4_pipe <= input_pipeline_phase7_3_under_pipe * coeffphase8_4_pipe;

        end
      end
    end // temp_process47

  assign product_phase7_4 = product_phase7_4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process48
      if (reset == 1'b1) begin
        input_pipeline_phase7_4_under_pipe <= 0;
        coeffphase8_5_pipe <= 0;
        product_phase7_5_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7_4_under_pipe <= input_pipeline_phase7[4];
          coeffphase8_5_pipe <= coeffphase8_5;

          product_phase7_5_pipe <= input_pipeline_phase7_4_under_pipe * coeffphase8_5_pipe;

        end
      end
    end // temp_process48

  assign product_phase7_5 = product_phase7_5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process49
      if (reset == 1'b1) begin
        input_pipeline_phase7_5_under_pipe <= 0;
        coeffphase8_6_pipe <= 0;
        product_phase7_6_pipe <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          input_pipeline_phase7_5_under_pipe <= input_pipeline_phase7[5];
          coeffphase8_6_pipe <= coeffphase8_6;

          product_phase7_6_pipe <= input_pipeline_phase7_5_under_pipe * coeffphase8_6_pipe;

        end
      end
    end // temp_process49

  assign product_phase7_6 = product_phase7_6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: product_pipeline_process7
      if (reset == 1'b1) begin
        product_pipeline_phase0_1 <= 0;
        product_pipeline_phase1_1 <= 0;
        product_pipeline_phase2_1 <= 0;
        product_pipeline_phase3_1 <= 0;
        product_pipeline_phase4_1 <= 0;
        product_pipeline_phase5_1 <= 0;
        product_pipeline_phase6_1 <= 0;
        product_pipeline_phase7_1 <= 0;
        product_pipeline_phase0_2 <= 0;
        product_pipeline_phase1_2 <= 0;
        product_pipeline_phase2_2 <= 0;
        product_pipeline_phase3_2 <= 0;
        product_pipeline_phase4_2 <= 0;
        product_pipeline_phase5_2 <= 0;
        product_pipeline_phase6_2 <= 0;
        product_pipeline_phase7_2 <= 0;
        product_pipeline_phase0_3 <= 0;
        product_pipeline_phase1_3 <= 0;
        product_pipeline_phase2_3 <= 0;
        product_pipeline_phase3_3 <= 0;
        product_pipeline_phase4_3 <= 0;
        product_pipeline_phase5_3 <= 0;
        product_pipeline_phase6_3 <= 0;
        product_pipeline_phase7_3 <= 0;
        product_pipeline_phase0_4 <= 0;
        product_pipeline_phase1_4 <= 0;
        product_pipeline_phase2_4 <= 0;
        product_pipeline_phase3_4 <= 0;
        product_pipeline_phase4_4 <= 0;
        product_pipeline_phase5_4 <= 0;
        product_pipeline_phase6_4 <= 0;
        product_pipeline_phase7_4 <= 0;
        product_pipeline_phase0_5 <= 0;
        product_pipeline_phase1_5 <= 0;
        product_pipeline_phase2_5 <= 0;
        product_pipeline_phase3_5 <= 0;
        product_pipeline_phase4_5 <= 0;
        product_pipeline_phase5_5 <= 0;
        product_pipeline_phase6_5 <= 0;
        product_pipeline_phase7_5 <= 0;
        product_pipeline_phase0_6 <= 0;
        product_pipeline_phase1_6 <= 0;
        product_pipeline_phase2_6 <= 0;
        product_pipeline_phase3_6 <= 0;
        product_pipeline_phase4_6 <= 0;
        product_pipeline_phase5_6 <= 0;
        product_pipeline_phase6_6 <= 0;
        product_pipeline_phase7_6 <= 0;
        product_pipeline_phase0_7 <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          product_pipeline_phase0_1 <= product_phase0_1;
          product_pipeline_phase1_1 <= product_phase1_1;
          product_pipeline_phase2_1 <= product_phase2_1;
          product_pipeline_phase3_1 <= product_phase3_1;
          product_pipeline_phase4_1 <= product_phase4_1;
          product_pipeline_phase5_1 <= product_phase5_1;
          product_pipeline_phase6_1 <= product_phase6_1;
          product_pipeline_phase7_1 <= product_phase7_1;
          product_pipeline_phase0_2 <= product_phase0_2;
          product_pipeline_phase1_2 <= product_phase1_2;
          product_pipeline_phase2_2 <= product_phase2_2;
          product_pipeline_phase3_2 <= product_phase3_2;
          product_pipeline_phase4_2 <= product_phase4_2;
          product_pipeline_phase5_2 <= product_phase5_2;
          product_pipeline_phase6_2 <= product_phase6_2;
          product_pipeline_phase7_2 <= product_phase7_2;
          product_pipeline_phase0_3 <= product_phase0_3;
          product_pipeline_phase1_3 <= product_phase1_3;
          product_pipeline_phase2_3 <= product_phase2_3;
          product_pipeline_phase3_3 <= product_phase3_3;
          product_pipeline_phase4_3 <= product_phase4_3;
          product_pipeline_phase5_3 <= product_phase5_3;
          product_pipeline_phase6_3 <= product_phase6_3;
          product_pipeline_phase7_3 <= product_phase7_3;
          product_pipeline_phase0_4 <= product_phase0_4;
          product_pipeline_phase1_4 <= product_phase1_4;
          product_pipeline_phase2_4 <= product_phase2_4;
          product_pipeline_phase3_4 <= product_phase3_4;
          product_pipeline_phase4_4 <= product_phase4_4;
          product_pipeline_phase5_4 <= product_phase5_4;
          product_pipeline_phase6_4 <= product_phase6_4;
          product_pipeline_phase7_4 <= product_phase7_4;
          product_pipeline_phase0_5 <= product_phase0_5;
          product_pipeline_phase1_5 <= product_phase1_5;
          product_pipeline_phase2_5 <= product_phase2_5;
          product_pipeline_phase3_5 <= product_phase3_5;
          product_pipeline_phase4_5 <= product_phase4_5;
          product_pipeline_phase5_5 <= product_phase5_5;
          product_pipeline_phase6_5 <= product_phase6_5;
          product_pipeline_phase7_5 <= product_phase7_5;
          product_pipeline_phase0_6 <= product_phase0_6;
          product_pipeline_phase1_6 <= product_phase1_6;
          product_pipeline_phase2_6 <= product_phase2_6;
          product_pipeline_phase3_6 <= product_phase3_6;
          product_pipeline_phase4_6 <= product_phase4_6;
          product_pipeline_phase5_6 <= product_phase5_6;
          product_pipeline_phase6_6 <= product_phase6_6;
          product_pipeline_phase7_6 <= product_phase7_6;
          product_pipeline_phase0_7 <= product_phase0_7;
        end
      end
    end // product_pipeline_process7

  assign add_signext_6 = product_pipeline_phase7_1;
  assign add_signext_7 = product_pipeline_phase7_2;
  assign add_temp = add_signext_6 + add_signext_7;
  assign sumvector1[0] = $signed({{4{add_temp[31]}}, add_temp});

  assign add_signext_8 = product_pipeline_phase7_3;
  assign add_signext_9 = product_pipeline_phase7_4;
  assign add_temp_1 = add_signext_8 + add_signext_9;
  assign sumvector1[1] = $signed({{4{add_temp_1[31]}}, add_temp_1});

  assign add_signext_10 = product_pipeline_phase7_5;
  assign add_signext_11 = product_pipeline_phase7_6;
  assign add_temp_2 = add_signext_10 + add_signext_11;
  assign sumvector1[2] = $signed({{4{add_temp_2[31]}}, add_temp_2});

  assign add_signext_12 = product_pipeline_phase6_1;
  assign add_signext_13 = product_pipeline_phase6_2;
  assign add_temp_3 = add_signext_12 + add_signext_13;
  assign sumvector1[3] = $signed({{4{add_temp_3[31]}}, add_temp_3});

  assign add_signext_14 = product_pipeline_phase6_3;
  assign add_signext_15 = product_pipeline_phase6_4;
  assign add_temp_4 = add_signext_14 + add_signext_15;
  assign sumvector1[4] = $signed({{4{add_temp_4[31]}}, add_temp_4});

  assign add_signext_16 = product_pipeline_phase6_5;
  assign add_signext_17 = product_pipeline_phase6_6;
  assign add_temp_5 = add_signext_16 + add_signext_17;
  assign sumvector1[5] = $signed({{4{add_temp_5[31]}}, add_temp_5});

  assign add_signext_18 = product_pipeline_phase5_1;
  assign add_signext_19 = product_pipeline_phase5_2;
  assign add_temp_6 = add_signext_18 + add_signext_19;
  assign sumvector1[6] = $signed({{4{add_temp_6[31]}}, add_temp_6});

  assign add_signext_20 = product_pipeline_phase5_3;
  assign add_signext_21 = product_pipeline_phase5_4;
  assign add_temp_7 = add_signext_20 + add_signext_21;
  assign sumvector1[7] = $signed({{4{add_temp_7[31]}}, add_temp_7});

  assign add_signext_22 = product_pipeline_phase5_5;
  assign add_signext_23 = product_pipeline_phase5_6;
  assign add_temp_8 = add_signext_22 + add_signext_23;
  assign sumvector1[8] = $signed({{4{add_temp_8[31]}}, add_temp_8});

  assign add_signext_24 = product_pipeline_phase4_1;
  assign add_signext_25 = product_pipeline_phase4_2;
  assign add_temp_9 = add_signext_24 + add_signext_25;
  assign sumvector1[9] = $signed({{4{add_temp_9[31]}}, add_temp_9});

  assign add_signext_26 = product_pipeline_phase4_3;
  assign add_signext_27 = product_pipeline_phase4_4;
  assign add_temp_10 = add_signext_26 + add_signext_27;
  assign sumvector1[10] = $signed({{4{add_temp_10[31]}}, add_temp_10});

  assign add_signext_28 = product_pipeline_phase4_5;
  assign add_signext_29 = product_pipeline_phase4_6;
  assign add_temp_11 = add_signext_28 + add_signext_29;
  assign sumvector1[11] = $signed({{4{add_temp_11[31]}}, add_temp_11});

  assign add_signext_30 = product_pipeline_phase3_1;
  assign add_signext_31 = product_pipeline_phase3_2;
  assign add_temp_12 = add_signext_30 + add_signext_31;
  assign sumvector1[12] = $signed({{4{add_temp_12[31]}}, add_temp_12});

  assign add_signext_32 = product_pipeline_phase3_3;
  assign add_signext_33 = product_pipeline_phase3_4;
  assign add_temp_13 = add_signext_32 + add_signext_33;
  assign sumvector1[13] = $signed({{4{add_temp_13[31]}}, add_temp_13});

  assign add_signext_34 = product_pipeline_phase3_5;
  assign add_signext_35 = product_pipeline_phase3_6;
  assign add_temp_14 = add_signext_34 + add_signext_35;
  assign sumvector1[14] = $signed({{4{add_temp_14[31]}}, add_temp_14});

  assign add_signext_36 = product_pipeline_phase2_1;
  assign add_signext_37 = product_pipeline_phase2_2;
  assign add_temp_15 = add_signext_36 + add_signext_37;
  assign sumvector1[15] = $signed({{4{add_temp_15[31]}}, add_temp_15});

  assign add_signext_38 = product_pipeline_phase2_3;
  assign add_signext_39 = product_pipeline_phase2_4;
  assign add_temp_16 = add_signext_38 + add_signext_39;
  assign sumvector1[16] = $signed({{4{add_temp_16[31]}}, add_temp_16});

  assign add_signext_40 = product_pipeline_phase2_5;
  assign add_signext_41 = product_pipeline_phase2_6;
  assign add_temp_17 = add_signext_40 + add_signext_41;
  assign sumvector1[17] = $signed({{4{add_temp_17[31]}}, add_temp_17});

  assign add_signext_42 = product_pipeline_phase1_1;
  assign add_signext_43 = product_pipeline_phase1_2;
  assign add_temp_18 = add_signext_42 + add_signext_43;
  assign sumvector1[18] = $signed({{4{add_temp_18[31]}}, add_temp_18});

  assign add_signext_44 = product_pipeline_phase1_3;
  assign add_signext_45 = product_pipeline_phase1_4;
  assign add_temp_19 = add_signext_44 + add_signext_45;
  assign sumvector1[19] = $signed({{4{add_temp_19[31]}}, add_temp_19});

  assign add_signext_46 = product_pipeline_phase1_5;
  assign add_signext_47 = product_pipeline_phase1_6;
  assign add_temp_20 = add_signext_46 + add_signext_47;
  assign sumvector1[20] = $signed({{4{add_temp_20[31]}}, add_temp_20});

  assign add_signext_48 = product_pipeline_phase0_1;
  assign add_signext_49 = product_pipeline_phase0_2;
  assign add_temp_21 = add_signext_48 + add_signext_49;
  assign sumvector1[21] = $signed({{4{add_temp_21[31]}}, add_temp_21});

  assign add_signext_50 = product_pipeline_phase0_3;
  assign add_signext_51 = product_pipeline_phase0_4;
  assign add_temp_22 = add_signext_50 + add_signext_51;
  assign sumvector1[22] = $signed({{4{add_temp_22[31]}}, add_temp_22});

  assign add_signext_52 = product_pipeline_phase0_5;
  assign add_signext_53 = product_pipeline_phase0_6;
  assign add_temp_23 = add_signext_52 + add_signext_53;
  assign sumvector1[23] = $signed({{4{add_temp_23[31]}}, add_temp_23});

  assign sumvector1[24] = $signed({{5{product_pipeline_phase0_7[30]}}, product_pipeline_phase0_7});

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process1
      if (reset == 1'b1) begin
        sumdelay_pipeline1[0] <= 0;
        sumdelay_pipeline1[1] <= 0;
        sumdelay_pipeline1[2] <= 0;
        sumdelay_pipeline1[3] <= 0;
        sumdelay_pipeline1[4] <= 0;
        sumdelay_pipeline1[5] <= 0;
        sumdelay_pipeline1[6] <= 0;
        sumdelay_pipeline1[7] <= 0;
        sumdelay_pipeline1[8] <= 0;
        sumdelay_pipeline1[9] <= 0;
        sumdelay_pipeline1[10] <= 0;
        sumdelay_pipeline1[11] <= 0;
        sumdelay_pipeline1[12] <= 0;
        sumdelay_pipeline1[13] <= 0;
        sumdelay_pipeline1[14] <= 0;
        sumdelay_pipeline1[15] <= 0;
        sumdelay_pipeline1[16] <= 0;
        sumdelay_pipeline1[17] <= 0;
        sumdelay_pipeline1[18] <= 0;
        sumdelay_pipeline1[19] <= 0;
        sumdelay_pipeline1[20] <= 0;
        sumdelay_pipeline1[21] <= 0;
        sumdelay_pipeline1[22] <= 0;
        sumdelay_pipeline1[23] <= 0;
        sumdelay_pipeline1[24] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          sumdelay_pipeline1[0] <= sumvector1[0];
          sumdelay_pipeline1[1] <= sumvector1[1];
          sumdelay_pipeline1[2] <= sumvector1[2];
          sumdelay_pipeline1[3] <= sumvector1[3];
          sumdelay_pipeline1[4] <= sumvector1[4];
          sumdelay_pipeline1[5] <= sumvector1[5];
          sumdelay_pipeline1[6] <= sumvector1[6];
          sumdelay_pipeline1[7] <= sumvector1[7];
          sumdelay_pipeline1[8] <= sumvector1[8];
          sumdelay_pipeline1[9] <= sumvector1[9];
          sumdelay_pipeline1[10] <= sumvector1[10];
          sumdelay_pipeline1[11] <= sumvector1[11];
          sumdelay_pipeline1[12] <= sumvector1[12];
          sumdelay_pipeline1[13] <= sumvector1[13];
          sumdelay_pipeline1[14] <= sumvector1[14];
          sumdelay_pipeline1[15] <= sumvector1[15];
          sumdelay_pipeline1[16] <= sumvector1[16];
          sumdelay_pipeline1[17] <= sumvector1[17];
          sumdelay_pipeline1[18] <= sumvector1[18];
          sumdelay_pipeline1[19] <= sumvector1[19];
          sumdelay_pipeline1[20] <= sumvector1[20];
          sumdelay_pipeline1[21] <= sumvector1[21];
          sumdelay_pipeline1[22] <= sumvector1[22];
          sumdelay_pipeline1[23] <= sumvector1[23];
          sumdelay_pipeline1[24] <= sumvector1[24];
        end
      end
    end // sumdelay_pipeline_process1

  assign add_signext_54 = sumdelay_pipeline1[0];
  assign add_signext_55 = sumdelay_pipeline1[1];
  assign add_temp_24 = add_signext_54 + add_signext_55;
  assign sumvector2[0] = add_temp_24[35:0];

  assign add_signext_56 = sumdelay_pipeline1[2];
  assign add_signext_57 = sumdelay_pipeline1[3];
  assign add_temp_25 = add_signext_56 + add_signext_57;
  assign sumvector2[1] = add_temp_25[35:0];

  assign add_signext_58 = sumdelay_pipeline1[4];
  assign add_signext_59 = sumdelay_pipeline1[5];
  assign add_temp_26 = add_signext_58 + add_signext_59;
  assign sumvector2[2] = add_temp_26[35:0];

  assign add_signext_60 = sumdelay_pipeline1[6];
  assign add_signext_61 = sumdelay_pipeline1[7];
  assign add_temp_27 = add_signext_60 + add_signext_61;
  assign sumvector2[3] = add_temp_27[35:0];

  assign add_signext_62 = sumdelay_pipeline1[8];
  assign add_signext_63 = sumdelay_pipeline1[9];
  assign add_temp_28 = add_signext_62 + add_signext_63;
  assign sumvector2[4] = add_temp_28[35:0];

  assign add_signext_64 = sumdelay_pipeline1[10];
  assign add_signext_65 = sumdelay_pipeline1[11];
  assign add_temp_29 = add_signext_64 + add_signext_65;
  assign sumvector2[5] = add_temp_29[35:0];

  assign add_signext_66 = sumdelay_pipeline1[12];
  assign add_signext_67 = sumdelay_pipeline1[13];
  assign add_temp_30 = add_signext_66 + add_signext_67;
  assign sumvector2[6] = add_temp_30[35:0];

  assign add_signext_68 = sumdelay_pipeline1[14];
  assign add_signext_69 = sumdelay_pipeline1[15];
  assign add_temp_31 = add_signext_68 + add_signext_69;
  assign sumvector2[7] = add_temp_31[35:0];

  assign add_signext_70 = sumdelay_pipeline1[16];
  assign add_signext_71 = sumdelay_pipeline1[17];
  assign add_temp_32 = add_signext_70 + add_signext_71;
  assign sumvector2[8] = add_temp_32[35:0];

  assign add_signext_72 = sumdelay_pipeline1[18];
  assign add_signext_73 = sumdelay_pipeline1[19];
  assign add_temp_33 = add_signext_72 + add_signext_73;
  assign sumvector2[9] = add_temp_33[35:0];

  assign add_signext_74 = sumdelay_pipeline1[20];
  assign add_signext_75 = sumdelay_pipeline1[21];
  assign add_temp_34 = add_signext_74 + add_signext_75;
  assign sumvector2[10] = add_temp_34[35:0];

  assign add_signext_76 = sumdelay_pipeline1[22];
  assign add_signext_77 = sumdelay_pipeline1[23];
  assign add_temp_35 = add_signext_76 + add_signext_77;
  assign sumvector2[11] = add_temp_35[35:0];

  assign sumvector2[12] = sumdelay_pipeline1[24];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process2
      if (reset == 1'b1) begin
        sumdelay_pipeline2[0] <= 0;
        sumdelay_pipeline2[1] <= 0;
        sumdelay_pipeline2[2] <= 0;
        sumdelay_pipeline2[3] <= 0;
        sumdelay_pipeline2[4] <= 0;
        sumdelay_pipeline2[5] <= 0;
        sumdelay_pipeline2[6] <= 0;
        sumdelay_pipeline2[7] <= 0;
        sumdelay_pipeline2[8] <= 0;
        sumdelay_pipeline2[9] <= 0;
        sumdelay_pipeline2[10] <= 0;
        sumdelay_pipeline2[11] <= 0;
        sumdelay_pipeline2[12] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          sumdelay_pipeline2[0] <= sumvector2[0];
          sumdelay_pipeline2[1] <= sumvector2[1];
          sumdelay_pipeline2[2] <= sumvector2[2];
          sumdelay_pipeline2[3] <= sumvector2[3];
          sumdelay_pipeline2[4] <= sumvector2[4];
          sumdelay_pipeline2[5] <= sumvector2[5];
          sumdelay_pipeline2[6] <= sumvector2[6];
          sumdelay_pipeline2[7] <= sumvector2[7];
          sumdelay_pipeline2[8] <= sumvector2[8];
          sumdelay_pipeline2[9] <= sumvector2[9];
          sumdelay_pipeline2[10] <= sumvector2[10];
          sumdelay_pipeline2[11] <= sumvector2[11];
          sumdelay_pipeline2[12] <= sumvector2[12];
        end
      end
    end // sumdelay_pipeline_process2

  assign add_signext_78 = sumdelay_pipeline2[0];
  assign add_signext_79 = sumdelay_pipeline2[1];
  assign add_temp_36 = add_signext_78 + add_signext_79;
  assign sumvector3[0] = add_temp_36[35:0];

  assign add_signext_80 = sumdelay_pipeline2[2];
  assign add_signext_81 = sumdelay_pipeline2[3];
  assign add_temp_37 = add_signext_80 + add_signext_81;
  assign sumvector3[1] = add_temp_37[35:0];

  assign add_signext_82 = sumdelay_pipeline2[4];
  assign add_signext_83 = sumdelay_pipeline2[5];
  assign add_temp_38 = add_signext_82 + add_signext_83;
  assign sumvector3[2] = add_temp_38[35:0];

  assign add_signext_84 = sumdelay_pipeline2[6];
  assign add_signext_85 = sumdelay_pipeline2[7];
  assign add_temp_39 = add_signext_84 + add_signext_85;
  assign sumvector3[3] = add_temp_39[35:0];

  assign add_signext_86 = sumdelay_pipeline2[8];
  assign add_signext_87 = sumdelay_pipeline2[9];
  assign add_temp_40 = add_signext_86 + add_signext_87;
  assign sumvector3[4] = add_temp_40[35:0];

  assign add_signext_88 = sumdelay_pipeline2[10];
  assign add_signext_89 = sumdelay_pipeline2[11];
  assign add_temp_41 = add_signext_88 + add_signext_89;
  assign sumvector3[5] = add_temp_41[35:0];

  assign sumvector3[6] = sumdelay_pipeline2[12];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process3
      if (reset == 1'b1) begin
        sumdelay_pipeline3[0] <= 0;
        sumdelay_pipeline3[1] <= 0;
        sumdelay_pipeline3[2] <= 0;
        sumdelay_pipeline3[3] <= 0;
        sumdelay_pipeline3[4] <= 0;
        sumdelay_pipeline3[5] <= 0;
        sumdelay_pipeline3[6] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          sumdelay_pipeline3[0] <= sumvector3[0];
          sumdelay_pipeline3[1] <= sumvector3[1];
          sumdelay_pipeline3[2] <= sumvector3[2];
          sumdelay_pipeline3[3] <= sumvector3[3];
          sumdelay_pipeline3[4] <= sumvector3[4];
          sumdelay_pipeline3[5] <= sumvector3[5];
          sumdelay_pipeline3[6] <= sumvector3[6];
        end
      end
    end // sumdelay_pipeline_process3

  assign add_signext_90 = sumdelay_pipeline3[0];
  assign add_signext_91 = sumdelay_pipeline3[1];
  assign add_temp_42 = add_signext_90 + add_signext_91;
  assign sumvector4[0] = add_temp_42[35:0];

  assign add_signext_92 = sumdelay_pipeline3[2];
  assign add_signext_93 = sumdelay_pipeline3[3];
  assign add_temp_43 = add_signext_92 + add_signext_93;
  assign sumvector4[1] = add_temp_43[35:0];

  assign add_signext_94 = sumdelay_pipeline3[4];
  assign add_signext_95 = sumdelay_pipeline3[5];
  assign add_temp_44 = add_signext_94 + add_signext_95;
  assign sumvector4[2] = add_temp_44[35:0];

  assign sumvector4[3] = sumdelay_pipeline3[6];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process4
      if (reset == 1'b1) begin
        sumdelay_pipeline4[0] <= 0;
        sumdelay_pipeline4[1] <= 0;
        sumdelay_pipeline4[2] <= 0;
        sumdelay_pipeline4[3] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          sumdelay_pipeline4[0] <= sumvector4[0];
          sumdelay_pipeline4[1] <= sumvector4[1];
          sumdelay_pipeline4[2] <= sumvector4[2];
          sumdelay_pipeline4[3] <= sumvector4[3];
        end
      end
    end // sumdelay_pipeline_process4

  assign add_signext_96 = sumdelay_pipeline4[0];
  assign add_signext_97 = sumdelay_pipeline4[1];
  assign add_temp_45 = add_signext_96 + add_signext_97;
  assign sumvector5[0] = add_temp_45[35:0];

  assign add_signext_98 = sumdelay_pipeline4[2];
  assign add_signext_99 = sumdelay_pipeline4[3];
  assign add_temp_46 = add_signext_98 + add_signext_99;
  assign sumvector5[1] = add_temp_46[35:0];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process5
      if (reset == 1'b1) begin
        sumdelay_pipeline5[0] <= 0;
        sumdelay_pipeline5[1] <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          sumdelay_pipeline5[0] <= sumvector5[0];
          sumdelay_pipeline5[1] <= sumvector5[1];
        end
      end
    end // sumdelay_pipeline_process5

  assign add_signext_100 = sumdelay_pipeline5[0];
  assign add_signext_101 = sumdelay_pipeline5[1];
  assign add_temp_47 = add_signext_100 + add_signext_101;
  assign sum6 = add_temp_47[35:0];

  assign output_typeconvert = (sum6[35:0] + {sum6[20], {19{~sum6[20]}}})>>>20;

  always @ (posedge clk or posedge reset)
    begin: ce_delay
      if (reset == 1'b1) begin
        ce_delayline1 <= 1'b0;
        ce_delayline2 <= 1'b0;
        ce_delayline3 <= 1'b0;
        ce_delayline4 <= 1'b0;
        ce_delayline5 <= 1'b0;
        ce_delayline6 <= 1'b0;
        ce_delayline7 <= 1'b0;
        ce_delayline8 <= 1'b0;
        ce_delayline9 <= 1'b0;
        ce_delayline10 <= 1'b0;
        ce_delayline11 <= 1'b0;
        ce_delayline12 <= 1'b0;
        ce_delayline13 <= 1'b0;
        ce_delayline14 <= 1'b0;
        ce_delayline15 <= 1'b0;
        ce_delayline16 <= 1'b0;
        ce_delayline17 <= 1'b0;
        ce_delayline18 <= 1'b0;
        ce_delayline19 <= 1'b0;
        ce_delayline20 <= 1'b0;
        ce_delayline21 <= 1'b0;
        ce_delayline22 <= 1'b0;
        ce_delayline23 <= 1'b0;
        ce_delayline24 <= 1'b0;
        ce_delayline25 <= 1'b0;
        ce_delayline26 <= 1'b0;
        ce_delayline27 <= 1'b0;
        ce_delayline28 <= 1'b0;
        ce_delayline29 <= 1'b0;
        ce_delayline30 <= 1'b0;
        ce_delayline31 <= 1'b0;
        ce_delayline32 <= 1'b0;
        ce_delayline33 <= 1'b0;
        ce_delayline34 <= 1'b0;
        ce_delayline35 <= 1'b0;
        ce_delayline36 <= 1'b0;
        ce_delayline37 <= 1'b0;
        ce_delayline38 <= 1'b0;
        ce_delayline39 <= 1'b0;
        ce_delayline40 <= 1'b0;
        ce_delayline41 <= 1'b0;
        ce_delayline42 <= 1'b0;
        ce_delayline43 <= 1'b0;
        ce_delayline44 <= 1'b0;
        ce_delayline45 <= 1'b0;
        ce_delayline46 <= 1'b0;
        ce_delayline47 <= 1'b0;
        ce_delayline48 <= 1'b0;
        ce_delayline49 <= 1'b0;
        ce_delayline50 <= 1'b0;
        ce_delayline51 <= 1'b0;
        ce_delayline52 <= 1'b0;
        ce_delayline53 <= 1'b0;
        ce_delayline54 <= 1'b0;
        ce_delayline55 <= 1'b0;
        ce_delayline56 <= 1'b0;
        ce_delayline57 <= 1'b0;
        ce_delayline58 <= 1'b0;
        ce_delayline59 <= 1'b0;
        ce_delayline60 <= 1'b0;
        ce_delayline61 <= 1'b0;
        ce_delayline62 <= 1'b0;
        ce_delayline63 <= 1'b0;
        ce_delayline64 <= 1'b0;
        ce_delayline65 <= 1'b0;
        ce_delayline66 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          ce_delayline1 <= clk_enable;
          ce_delayline2 <= ce_delayline1;
          ce_delayline3 <= ce_delayline2;
          ce_delayline4 <= ce_delayline3;
          ce_delayline5 <= ce_delayline4;
          ce_delayline6 <= ce_delayline5;
          ce_delayline7 <= ce_delayline6;
          ce_delayline8 <= ce_delayline7;
          ce_delayline9 <= ce_delayline8;
          ce_delayline10 <= ce_delayline9;
          ce_delayline11 <= ce_delayline10;
          ce_delayline12 <= ce_delayline11;
          ce_delayline13 <= ce_delayline12;
          ce_delayline14 <= ce_delayline13;
          ce_delayline15 <= ce_delayline14;
          ce_delayline16 <= ce_delayline15;
          ce_delayline17 <= ce_delayline16;
          ce_delayline18 <= ce_delayline17;
          ce_delayline19 <= ce_delayline18;
          ce_delayline20 <= ce_delayline19;
          ce_delayline21 <= ce_delayline20;
          ce_delayline22 <= ce_delayline21;
          ce_delayline23 <= ce_delayline22;
          ce_delayline24 <= ce_delayline23;
          ce_delayline25 <= ce_delayline24;
          ce_delayline26 <= ce_delayline25;
          ce_delayline27 <= ce_delayline26;
          ce_delayline28 <= ce_delayline27;
          ce_delayline29 <= ce_delayline28;
          ce_delayline30 <= ce_delayline29;
          ce_delayline31 <= ce_delayline30;
          ce_delayline32 <= ce_delayline31;
          ce_delayline33 <= ce_delayline32;
          ce_delayline34 <= ce_delayline33;
          ce_delayline35 <= ce_delayline34;
          ce_delayline36 <= ce_delayline35;
          ce_delayline37 <= ce_delayline36;
          ce_delayline38 <= ce_delayline37;
          ce_delayline39 <= ce_delayline38;
          ce_delayline40 <= ce_delayline39;
          ce_delayline41 <= ce_delayline40;
          ce_delayline42 <= ce_delayline41;
          ce_delayline43 <= ce_delayline42;
          ce_delayline44 <= ce_delayline43;
          ce_delayline45 <= ce_delayline44;
          ce_delayline46 <= ce_delayline45;
          ce_delayline47 <= ce_delayline46;
          ce_delayline48 <= ce_delayline47;
          ce_delayline49 <= ce_delayline48;
          ce_delayline50 <= ce_delayline49;
          ce_delayline51 <= ce_delayline50;
          ce_delayline52 <= ce_delayline51;
          ce_delayline53 <= ce_delayline52;
          ce_delayline54 <= ce_delayline53;
          ce_delayline55 <= ce_delayline54;
          ce_delayline56 <= ce_delayline55;
          ce_delayline57 <= ce_delayline56;
          ce_delayline58 <= ce_delayline57;
          ce_delayline59 <= ce_delayline58;
          ce_delayline60 <= ce_delayline59;
          ce_delayline61 <= ce_delayline60;
          ce_delayline62 <= ce_delayline61;
          ce_delayline63 <= ce_delayline62;
          ce_delayline64 <= ce_delayline63;
          ce_delayline65 <= ce_delayline64;
          ce_delayline66 <= ce_delayline65;
        end
      end
    end // ce_delay

  assign ce_gated =  ce_delayline66 & ce_out_reg;

  always @ (posedge clk or posedge reset)
    begin: output_register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_7 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_register_process

  // Assignment Statements
  assign ce_out = ce_gated;
  assign filter_out = output_register;
endmodule  // d_8
