function d_8_generatehdl(filtobj)
%  D_8_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
%  Generated on: 2026-09-18 23:47:11
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  FIRAdderStyle: tree
%  MultiplierInputPipeline: 1
%  MultiplierOutputPipeline: 1
%  OptimizeForHDL: on
%  TargetDirectory: hdlsrc/d_8
%  AddPipelineRegisters: on
%  Name: d_8
%  TargetLanguage: Verilog
%  TestBenchStimulus: step ramp chirp noise 
%  LoopUnrolling: on
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Multirate Filter (real)
%  -----------------------------------------
%  Filter Structure   : Direct-Form FIR Polyphase Decimator
%  Decimation Factor  : 8
%  Polyphase Length   : 7
%  Filter Length      : 49
%  Stable             : Yes
%  Linear Phase       : Yes (Type 1)
%
%  Arithmetic         : fixed
%  Numerator          : s16,15 -> [-1 1)
%  Input              : s16,15 -> [-1 1)
%  Filter Internals   : Specify Precision
%    Output           : s16,10 -> [-32 32)
%    Product          : s31,30 -> [-1 1)
%    Accumulator      : s36,30 -> [-32 32)
%    Round Mode       : convergent
%    Overflow Mode    : wrap

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'FIRAdderStyle', 'tree',... 
               'MultiplierInputPipeline', 1,... 
               'MultiplierOutputPipeline', 1,... 
               'OptimizeForHDL', 'on',... 
               'TargetDirectory', 'hdlsrc/d_8',... 
               'AddPipelineRegisters', 'on',... 
               'Name', 'd_8',... 
               'TargetLanguage', 'Verilog',... 
               'TestBenchStimulus',  {'step', 'ramp', 'chirp', 'noise'},... 
               'LoopUnrolling', 'on',... 
               'GenerateHDLTestbench', 'on');

% [EOF]
