function rcos_9_generatehdl(filtobj)
%  RCOS_9_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
%  Generated on: 2026-09-14 10:17:47
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  FIRAdderStyle: tree
%  MultiplierInputPipeline: 1
%  MultiplierOutputPipeline: 1
%  OptimizeForHDL: on
%  AddPipelineRegisters: on
%  Name: rcos_9
%  TargetLanguage: Verilog
%  TestBenchStimulus: impulse step ramp chirp noise 
%  LoopUnrolling: on
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Filter (real)
%  -------------------------------
%  Filter Structure  : Direct-Form FIR
%  Filter Length     : 73
%  Stable            : Yes
%  Linear Phase      : Yes (Type 1)
%  Arithmetic        : fixed
%  Numerator         : s16,15 -> [-1 1)
%  Input             : s16,15 -> [-1 1)
%  Filter Internals  : Specify Precision
%    Output          : s16,14 -> [-2 2)
%    Product         : s31,30 -> [-1 1)
%    Accumulator     : s35,30 -> [-16 16)
%    Round Mode      : convergent
%    Overflow Mode   : wrap

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'FIRAdderStyle', 'tree',... 
               'MultiplierInputPipeline', 1,... 
               'MultiplierOutputPipeline', 1,... 
               'OptimizeForHDL', 'on',... 
               'AddPipelineRegisters', 'on',... 
               'Name', 'rcos_9',... 
               'TargetLanguage', 'Verilog',... 
               'TestBenchStimulus',  {'impulse', 'step', 'ramp', 'chirp', 'noise'},... 
               'LoopUnrolling', 'on',... 
               'GenerateHDLTestbench', 'on');

% [EOF]
