// -------------------------------------------------------------
//
// Module: filter_3
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-09-14 10:54:36
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: hdlsrc/filter_3
// AddPipelineRegisters: on
// Name: filter_3
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 7
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// Input             : s16,15 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s16,13 -> [-4 4)
//   Product         : s31,30 -> [-1 1)
//   Accumulator     : s33,30 -> [-4 4)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------
// Multipliers           : 7



`timescale 1 ns / 1 ns

module filter_3
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En13

////////////////////////////////////////////////////////////////
//Module Architecture: filter_3
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000110001010101; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b0011001010101110; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b0110011010111011; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b0111111111111111; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b0110011010111011; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b0011001010101110; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b0000110001010101; //sfix16_En15

  // Signals
  reg  signed [15:0] delay_pipeline [0:6] ; // sfix16_En15
  wire signed [30:0] product7; // sfix31_En30
  reg  signed [15:0] delay_pipeline_6_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff7_pipe; // sfix16_En15
  reg  signed [31:0] product7_pipe; // sfix32_En30
  wire signed [30:0] product6; // sfix31_En30
  reg  signed [15:0] delay_pipeline_5_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff6_pipe; // sfix16_En15
  reg  signed [31:0] product6_pipe; // sfix32_En30
  wire signed [30:0] product5; // sfix31_En30
  reg  signed [15:0] delay_pipeline_4_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff5_pipe; // sfix16_En15
  reg  signed [31:0] product5_pipe; // sfix32_En30
  wire signed [30:0] product4; // sfix31_En30
  reg  signed [15:0] delay_pipeline_3_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff4_pipe; // sfix16_En15
  reg  signed [31:0] product4_pipe; // sfix32_En30
  wire signed [30:0] product3; // sfix31_En30
  reg  signed [15:0] delay_pipeline_2_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff3_pipe; // sfix16_En15
  reg  signed [31:0] product3_pipe; // sfix32_En30
  wire signed [30:0] product2; // sfix31_En30
  reg  signed [15:0] delay_pipeline_1_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff2_pipe; // sfix16_En15
  reg  signed [31:0] product2_pipe; // sfix32_En30
  wire signed [30:0] product1; // sfix31_En30
  reg  signed [15:0] delay_pipeline_0_under_pipe; // sfix16_En15
  reg  signed [15:0] coeff1_pipe; // sfix16_En15
  reg  signed [31:0] product1_pipe; // sfix32_En30
  wire signed [32:0] sum_final; // sfix33_En30
  wire signed [32:0] sum1_1; // sfix33_En30
  wire signed [30:0] add_signext; // sfix31_En30
  wire signed [30:0] add_signext_1; // sfix31_En30
  wire signed [31:0] add_temp; // sfix32_En30
  reg  signed [32:0] sumpipe1_1; // sfix33_En30
  wire signed [32:0] sum1_2; // sfix33_En30
  wire signed [30:0] add_signext_2; // sfix31_En30
  wire signed [30:0] add_signext_3; // sfix31_En30
  wire signed [31:0] add_temp_1; // sfix32_En30
  reg  signed [32:0] sumpipe1_2; // sfix33_En30
  wire signed [32:0] sum1_3; // sfix33_En30
  wire signed [30:0] add_signext_4; // sfix31_En30
  wire signed [30:0] add_signext_5; // sfix31_En30
  wire signed [31:0] add_temp_2; // sfix32_En30
  reg  signed [32:0] sumpipe1_3; // sfix33_En30
  reg  signed [30:0] sumpipe1_4; // sfix31_En30
  wire signed [32:0] sum2_1; // sfix33_En30
  wire signed [32:0] add_signext_6; // sfix33_En30
  wire signed [32:0] add_signext_7; // sfix33_En30
  wire signed [33:0] add_temp_3; // sfix34_En30
  reg  signed [32:0] sumpipe2_1; // sfix33_En30
  wire signed [32:0] sum2_2; // sfix33_En30
  wire signed [32:0] add_signext_8; // sfix33_En30
  wire signed [32:0] add_signext_9; // sfix33_En30
  wire signed [33:0] add_temp_4; // sfix34_En30
  reg  signed [32:0] sumpipe2_2; // sfix33_En30
  wire signed [32:0] sum3_1; // sfix33_En30
  wire signed [32:0] add_signext_10; // sfix33_En30
  wire signed [32:0] add_signext_11; // sfix33_En30
  wire signed [33:0] add_temp_5; // sfix34_En30
  reg  signed [32:0] sumpipe3_1; // sfix33_En30
  wire signed [15:0] output_typeconvert; // sfix16_En13
  reg  signed [15:0] output_register; // sfix16_En13

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
        end
      end
    end // Delay_Pipeline_process


  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        delay_pipeline_6_under_pipe <= 0;
        coeff7_pipe <= 0;
        product7_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_6_under_pipe <= delay_pipeline[6];
          coeff7_pipe <= coeff7;

          product7_pipe <= delay_pipeline_6_under_pipe * coeff7_pipe;

        end
      end
    end // temp_process1

  assign product7 = product7_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        delay_pipeline_5_under_pipe <= 0;
        coeff6_pipe <= 0;
        product6_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_5_under_pipe <= delay_pipeline[5];
          coeff6_pipe <= coeff6;

          product6_pipe <= delay_pipeline_5_under_pipe * coeff6_pipe;

        end
      end
    end // temp_process2

  assign product6 = product6_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        delay_pipeline_4_under_pipe <= 0;
        coeff5_pipe <= 0;
        product5_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_4_under_pipe <= delay_pipeline[4];
          coeff5_pipe <= coeff5;

          product5_pipe <= delay_pipeline_4_under_pipe * coeff5_pipe;

        end
      end
    end // temp_process3

  assign product5 = product5_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        delay_pipeline_3_under_pipe <= 0;
        coeff4_pipe <= 0;
        product4_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_3_under_pipe <= delay_pipeline[3];
          coeff4_pipe <= coeff4;

          product4_pipe <= delay_pipeline_3_under_pipe * coeff4_pipe;

        end
      end
    end // temp_process4

  assign product4 = product4_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        delay_pipeline_2_under_pipe <= 0;
        coeff3_pipe <= 0;
        product3_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_2_under_pipe <= delay_pipeline[2];
          coeff3_pipe <= coeff3;

          product3_pipe <= delay_pipeline_2_under_pipe * coeff3_pipe;

        end
      end
    end // temp_process5

  assign product3 = product3_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process6
      if (reset == 1'b1) begin
        delay_pipeline_1_under_pipe <= 0;
        coeff2_pipe <= 0;
        product2_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_1_under_pipe <= delay_pipeline[1];
          coeff2_pipe <= coeff2;

          product2_pipe <= delay_pipeline_1_under_pipe * coeff2_pipe;

        end
      end
    end // temp_process6

  assign product2 = product2_pipe[30:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process7
      if (reset == 1'b1) begin
        delay_pipeline_0_under_pipe <= 0;
        coeff1_pipe <= 0;
        product1_pipe <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline_0_under_pipe <= delay_pipeline[0];
          coeff1_pipe <= coeff1;

          product1_pipe <= delay_pipeline_0_under_pipe * coeff1_pipe;

        end
      end
    end // temp_process7

  assign product1 = product1_pipe[30:0];

  assign add_signext = product7;
  assign add_signext_1 = product6;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{1{add_temp[31]}}, add_temp});

  assign add_signext_2 = product5;
  assign add_signext_3 = product4;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{1{add_temp_1[31]}}, add_temp_1});

  assign add_signext_4 = product3;
  assign add_signext_5 = product2;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{1{add_temp_2[31]}}, add_temp_2});

  always @ (posedge clk or posedge reset)
    begin: temp_process8
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
        sumpipe1_3 <= 0;
        sumpipe1_4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
          sumpipe1_3 <= sum1_3;
          sumpipe1_4 <= product1;
        end
      end
    end // temp_process8

  assign add_signext_6 = sumpipe1_1;
  assign add_signext_7 = sumpipe1_2;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum2_1 = add_temp_3[32:0];

  assign add_signext_8 = sumpipe1_3;
  assign add_signext_9 = $signed({{2{sumpipe1_4[30]}}, sumpipe1_4});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum2_2 = add_temp_4[32:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process9
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
        sumpipe2_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
          sumpipe2_2 <= sum2_2;
        end
      end
    end // temp_process9

  assign add_signext_10 = sumpipe2_1;
  assign add_signext_11 = sumpipe2_2;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum3_1 = add_temp_5[32:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process10
      if (reset == 1'b1) begin
        sumpipe3_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe3_1 <= sum3_1;
        end
      end
    end // temp_process10

  assign sum_final = sumpipe3_1;

  assign output_typeconvert = (sum_final[32:0] + {sum_final[17], {16{~sum_final[17]}}})>>>17;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter_3
